// Autogenerated from KST: please remove this line if doing any edits by hand!

use kaitai_struct::KaitaiStruct;
use kaitai_test_suite::enum_int_range_u::EnumIntRangeU;

#[test]
fn test_enum_int_range_u() {
    let r = EnumIntRangeU::from_file("../../src/enum_int_range_u.bin").expect("file for parsing is not found");

    assert_eq!(r.f1, EnumIntRangeU__Constants::ZERO);
    assert_eq!(r.f2, EnumIntRangeU__Constants::INT_MAX);
}
