// Autogenerated from KST: please remove this line if doing any edits by hand!

extern crate kaitai_struct;
extern crate rust;

use kaitai_struct::KaitaiStruct;
use rust::meta_tags::MetaTags;

#[test]
fn test_meta_tags() {
    let r = MetaTags::from_file("../../src/fixed_struct.bin").expect("file for parsing is not found");

}
