// Autogenerated from KST: please remove this line if doing any edits by hand!

extern crate kaitai_struct;
extern crate rust;

use kaitai_struct::KaitaiStruct;
use rust::params_pass_usertype::ParamsPassUsertype;

#[test]
fn test_params_pass_usertype() {
    let r = ParamsPassUsertype::from_file("../../src/position_in_seq.bin").expect("file for parsing is not found");

    assert_eq!(r.first.foo, 1);
    assert_eq!(r.one.buf, vec!([0x2]));
}
