// Autogenerated from KST: please remove this line if doing any edits by hand!

use kaitai_struct::KaitaiStruct;
use kaitai_test_suite::position_in_seq::PositionInSeq;

#[test]
fn test_position_in_seq() {
    let r = PositionInSeq::from_file("../../src/position_in_seq.bin").expect("file for parsing is not found");

    assert_eq!(r.numbers, [0 + 1, 2, 3]);
}
