// Autogenerated from KST: please remove this line if doing any edits by hand!

extern crate kaitai_struct;
extern crate rust;

use kaitai_struct::KaitaiStruct;
use rust::process_coerce_bytes::ProcessCoerceBytes;

#[test]
fn test_process_coerce_bytes() {
    let r = ProcessCoerceBytes::from_file("../../src/process_coerce_bytes.bin").expect("file for parsing is not found");

    assert_eq!(r.records[0].flag, 0);
    assert_eq!(r.records[0].buf, vec!([0x41, 0x41, 0x41, 0x41]));
    assert_eq!(r.records[1].flag, 1);
    assert_eq!(r.records[1].buf, vec!([0x42, 0x42, 0x42, 0x42]));
}
