// Autogenerated from KST: please remove this line if doing any edits by hand!

extern crate kaitai_struct;
extern crate rust;

use kaitai_struct::KaitaiStruct;
use rust::repeat_eos_u4::RepeatEosU4;

#[test]
fn test_repeat_eos_u4() {
    let r = RepeatEosU4::from_file("../../src/repeat_eos_struct.bin").expect("file for parsing is not found");

    assert_eq!(r.numbers, [0, 66, 66, 2069]);
}
