// Autogenerated from KST: please remove this line if doing any edits by hand!

extern crate kaitai_struct;
extern crate rust;

use kaitai_struct::KaitaiStruct;
use rust::StrPadTermEmpty;

#[test]
fn test_str_pad_term_empty() {
    if let Ok(r) = StrPadTermEmpty::from_file("src/str_pad_term_empty.bin") {
        assert_eq!(r.str_pad, "");
        assert_eq!(r.str_term, "");
        assert_eq!(r.str_term_and_pad, "");
        assert_eq!(r.str_term_include, "@");
    }
}
