// Autogenerated from KST: please remove this line if doing any edits by hand!

use kaitai_struct::KaitaiStruct;
use kaitai_test_suite::switch_repeat_expr::SwitchRepeatExpr;

#[test]
fn test_switch_repeat_expr() {
    let r = SwitchRepeatExpr::from_file("../../src/switch_tlv.bin").expect("file for parsing is not found");

    assert_eq!(r.code, 17);
    assert_eq!(r.size, 9);
    assert_eq!(r.body[0].first, vec!([0x53, 0x74, 0x75, 0x66, 0x66, 0x0, 0x4d, 0x65, 0x0]));
}
