// Autogenerated from KST: please remove this line if doing any edits by hand!

#![allow(unused_variables)]
#![allow(unused_assignments)]
#![allow(overflowing_literals)]
use std::fs;
extern crate kaitai;
use self::kaitai::*;
#[path = "../formats/mod.rs"] mod formats;
use formats::imports0::*;
use formats::hello_world::*;

#[test]
fn test_imports0() {
    let bytes = fs::read("../../src/fixed_struct.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let res: KResult<OptRc<Imports0>> = Imports0::read_into(&_io, None, None);
    let r : OptRc<Imports0>;

    if let Err(err) = res {
        panic!("{:?}", err);
    } else {
        r = res.unwrap();
    }

    assert_eq!(*r.two(), 80);
    assert_eq!(*r.hw().one(), 65);
    assert_eq!(*r.hw_one().expect("error reading"), 65);
}
