// Autogenerated from KST: please remove this line if doing any edits by hand!

use kaitai::{BytesReader, KStruct, KStructUnit};
use kaitai_test::io_local_var::*;
use std::fs;

#[test]
fn test_io_local_var() {
    let data = fs::read("../../src/full256.bin").expect("Unable to read data.");
    let reader = BytesReader::new(&data[..]);
    let mut r = IoLocalVar::default();
    r.read(&reader, None, KStructUnit::parent_stack()).expect("Unable to parse data.");
    assert_eq!(r.skip, &[0x0, 0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8, 0x9, 0xa, 0xb, 0xc, 0xd, 0xe, 0xf, 0x10, 0x11, 0x12, 0x13]);
    assert_eq!(r.followup, 20);
}
