// Autogenerated from KST: please remove this line if doing any edits by hand!

use std::fs;
extern crate kaitai;
use self::kaitai::*;
use rust::formats::enum_int_range_s::*;

#[test]
fn test_enum_int_range_s() -> KResult<()> {
    let bytes = fs::read("../../src/enum_int_range_s.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let r: OptRc<EnumIntRangeS> = EnumIntRangeS::read_into(&_io, None, None)?;

    assert_eq!(*r.f1(), EnumIntRangeS_Constants::IntMin);
    assert_eq!(*r.f2(), EnumIntRangeS_Constants::Zero);
    assert_eq!(*r.f3(), EnumIntRangeS_Constants::IntMax);
    Ok(())
}
