// Autogenerated from KST: please remove this line if doing any edits by hand!

use kaitai::{BytesReader, KStruct, KStructUnit};
use kaitai_test::expr_sizeof_value_sized::ExprSizeofValueSized;
use std::fs;

#[test]
fn test_expr_sizeof_value_sized() {
    let data = fs::read("../../src/fixed_struct.bin").expect("Unable to read data.");
    let reader = BytesReader::new(&data[..]);
    let r = ExprSizeofValueSized::default().read(&reader, None, KStructUnit::parent_stack()).unwrap();
    // assert_eq!(r.self_sizeof, (12 + 2));
    // assert_eq!(r.sizeof_block, 12);
    // assert_eq!(r.sizeof_block_a, 1);
    // assert_eq!(r.sizeof_block_b, 4);
    // assert_eq!(r.sizeof_block_c, 2);
}
