// Autogenerated from KST: please remove this line if doing any edits by hand!

use std::fs;
extern crate kaitai;
use self::kaitai::*;
use rust::formats::eos_exception_unsigned_loop::*;

#[test]
fn test_eos_exception_unsigned_loop() -> KResult<()> {
    let bytes = fs::read("../../src/high_bit_u4_loop_count.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let res: KResult<OptRc<EosExceptionUnsignedLoop>> = EosExceptionUnsignedLoop::read_into(&_io, None, None);
    let err = res.expect_err("expected Err representing EndOfStreamError, but got Ok");
    assert!(
        matches!(err, KError::Eof { .. }),
        "expected: {}\n but got: {:?}",
        "KError::Eof { .. }", err
    );
    Ok(())
}
