// Autogenerated from KST: please remove this line if doing any edits by hand!

use std::fs;
extern crate kaitai;
use self::kaitai::*;
use rust::formats::expr_int_div::*;

#[test]
fn test_expr_int_div() -> KResult<()> {
    let bytes = fs::read("../../src/fixed_struct.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let r: OptRc<ExprIntDiv> = ExprIntDiv::read_into(&_io, None, None)?;

    assert_eq!(*r.int_u(), 1262698832);
    assert_eq!(*r.int_s(), -52947);
    assert_eq!(*r.div_pos_const()?, 756);
    assert_eq!(*r.div_neg_const()?, -757);
    assert_eq!(*r.div_pos_seq()?, 97130679);
    assert_eq!(*r.div_neg_seq()?, -4073);
    Ok(())
}
