// Autogenerated from KST: please remove this line if doing any edits by hand!

use std::fs;
extern crate kaitai;
use self::kaitai::*;
use rust::formats::valid_switch::*;

#[test]
fn test_valid_switch() -> KResult<()> {
    let bytes = fs::read("../../src/fixed_struct.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let r: OptRc<ValidSwitch> = ValidSwitch::read_into(&_io, None, None)?;

    Ok(())
}
