// Autogenerated from KST: please remove this line if doing any edits by hand!

use std::fs;
extern crate kaitai;
use self::kaitai::*;
use rust::formats::name_clash_import_vs_inst::*;

#[test]
fn test_name_clash_import_vs_inst() -> KResult<()> {
    let bytes = fs::read("../../src/fixed_struct.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let r: OptRc<NameClashImportVsInst> = NameClashImportVsInst::read_into(&_io, None, None)?;
    assert_eq!(*r.integers()?.uint8(), 255);
    assert_eq!(*r.std()?, 3);
    Ok(())
}
