// Autogenerated from KST: please remove this line if doing any edits by hand!

extern crate kaitai_struct;
extern crate rust;

use kaitai_struct::KaitaiStruct;
use rust::Docstrings;

#[test]
fn test_docstrings() {
    if let Ok(r) = Docstrings::from_file("src/fixed_struct.bin") {
    }
}
