// Autogenerated from KST: please remove this line if doing any edits by hand!

use kaitai::{BytesReader, KStruct, KStructUnit};
use kaitai_test::nav_parent_false2::NavParentFalse2;
use std::fs;

#[test]
fn test_nav_parent_false2() {
    let data = fs::read("../../src/fixed_struct.bin").expect("Unable to read data.");
    let reader = BytesReader::new(&data[..]);
    let r = NavParentFalse2::default().read(&reader, None, KStructUnit::parent_stack()).unwrap();
    // assert_eq!(r.parentless.foo, 80);
}
