// Autogenerated from KST: please remove this line if doing any edits by hand!

use kaitai::{BytesReader, KStruct, KStructUnit};
use kaitai_test::str_literals2::StrLiterals2;
use std::fs;

#[test]
fn test_str_literals2() {
    let data = fs::read("src/fixed_struct.bin").expect("Unable to read data.");
    let reader = BytesReader::new(&data[..]);
    let r = StrLiterals2::default().read(&reader, None, KStructUnit::parent_stack()).unwrap();
    // assert_eq!(r.dollar1, "$foo");
    // assert_eq!(r.dollar2, "${foo}");
    // assert_eq!(r.hash, "#{foo}");
    // assert_eq!(r.at_sign, "@foo");
}
