// Autogenerated from KST: please remove this line if doing any edits by hand!

#![allow(unused_variables)]
#![allow(unused_assignments)]
#![allow(overflowing_literals)]
use std::fs;
extern crate kaitai;
use self::kaitai::*;
#[path = "../formats/mod.rs"] mod formats;
use formats::index_sizes::*;

#[test]
fn test_index_sizes() {
    let bytes = fs::read("../../src/index_sizes.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let res: KResult<OptRc<IndexSizes>> = IndexSizes::read_into(&_io, None, None);
    let r : OptRc<IndexSizes>;

    if let Err(err) = res {
        panic!("{:?}", err);
    } else {
        r = res.unwrap();
    }

    assert_eq!(*r.qty(), 3);
    assert_eq!(r.sizes()[0 as usize], 1);
    assert_eq!(r.sizes()[1 as usize], 8);
    assert_eq!(r.sizes()[2 as usize], 4);
    assert_eq!(r.bufs()[0 as usize], "A");
    assert_eq!(r.bufs()[1 as usize], "BBBBBBBB");
    assert_eq!(r.bufs()[2 as usize], "CCCC");
}
