// Autogenerated from KST: please remove this line if doing any edits by hand!

use std::fs;
extern crate kaitai;
use self::kaitai::*;
use rust::formats::bits_byte_aligned::*;

#[test]
fn test_bits_byte_aligned() -> KResult<()> {
    let bytes = fs::read("../../src/fixed_struct.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let r: OptRc<BitsByteAligned> = BitsByteAligned::read_into(&_io, None, None)?;

    assert_eq!(*r.one(), 20);
    assert_eq!(*r.byte_1(), 65);
    assert_eq!(*r.two(), 2);
    assert_eq!(*r.three(), false);
    assert_eq!(*r.byte_2(), 75);
    assert_eq!(*r.four(), 2892);
    assert_eq!(*r.byte_3(), vec![0xffu8]);
    assert_eq!(*r.full_byte(), 255);
    assert_eq!(*r.byte_4(), 80);
    Ok(())
}
