// Autogenerated from KST: please remove this line if doing any edits by hand!

use std::fs;

extern crate kaitai;
use self::kaitai::*;
mod formats;
use formats::expr_bytes_non_literal::*;

#[test]
fn test_expr_bytes_non_literal() {
    let bytes = fs::read("../../src/enum_negative.bin").unwrap();
    let reader = BytesReader::new(&bytes);
    let mut r = ExprBytesNonLiteral::default();

    if let Err(err) = r.read(&reader, None, Some(KStructUnit::parent_stack())) {

        panic!("{:?}", err);
    }
    assert_eq!(r.calc_bytes(&reader).unwrap().len(), 2);
    assert_eq!(r.calc_bytes(&reader).unwrap()[0 as usize], 255);
    assert_eq!(r.calc_bytes(&reader).unwrap()[1 as usize], 1);
}
