// Autogenerated from KST: please remove this line if doing any edits by hand!

use kaitai::{BytesReader, KStruct, KStructUnit};
use kaitai_test::instance_std::InstanceStd;
use std::fs;

#[test]
fn test_instance_std() {
    let data = fs::read("../../src/str_encodings.bin").expect("Unable to read data.");
    let reader = BytesReader::new(&data[..]);
    let r = InstanceStd::default().read(&reader, None, KStructUnit::parent_stack()).unwrap();
    // assert_eq!(r.header, "Some ");
}
