// Autogenerated from KST: please remove this line if doing any edits by hand!

use kaitai::{BytesReader, KStruct, KStructUnit};
use kaitai_test::hello_world::HelloWorld;
use std::fs;

#[test]
fn test_hello_world() {
    let data = fs::read("src/fixed_struct.bin").expect("Unable to read data.");
    let reader = BytesReader::new(&data[..]);
    let r = HelloWorld::default().read(&reader, None, KStructUnit::parent_stack()).unwrap();
    // assert_eq!(r.one, 80);
}
