// Autogenerated from KST: please remove this line if doing any edits by hand!

use std::fs;
extern crate kaitai;
use self::kaitai::*;
use rust::formats::repeat_n_strz::*;

#[test]
fn test_repeat_n_strz() -> KResult<()> {
    let bytes = fs::read("../../src/repeat_n_strz.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let r: OptRc<RepeatNStrz> = RepeatNStrz::read_into(&_io, None, None)?;

    assert_eq!(*r.qty(), 2);
    assert_eq!(*r.lines(), vec!["foo".to_string(), "bar".to_string()]);
    Ok(())
}
