// Autogenerated from KST: please remove this line if doing any edits by hand!

use kaitai::{BytesReader, KStruct, KStructUnit};
use kaitai_test::multiple_use::MultipleUse;
use std::fs;

#[test]
fn test_multiple_use() {
    let data = fs::read("../../src/position_abs.bin").expect("Unable to read data.");
    let reader = BytesReader::new(&data[..]);
    let r = MultipleUse::default().read(&reader, None, KStructUnit::parent_stack()).unwrap();
    // assert_eq!(r.t1.first_use.value, 32);
    // assert_eq!(r.t2.second_use.value, 32);
}
