// Autogenerated from KST: please remove this line if doing any edits by hand!

use kaitai::{BytesReader, KStruct, KStructUnit};
use kaitai_test::expr_0::*;
use std::fs;

#[test]
fn test_expr_0() {
    let data = fs::read("../../src/str_encodings.bin").expect("Unable to read data.");
    let reader = BytesReader::new(&data[..]);
    let mut r = Expr0::default();
    r.read(&reader, None, KStructUnit::parent_stack()).expect("Unable to parse data.");
    // assert_eq!(Attribute(Name(identifier(q1w2e3)),identifier(must_be_f7)), IntNum(247))
    // assert_eq!(Attribute(Name(identifier(q1w2e3)),identifier(must_be_abc123)), Str(abc123))
}
