// Autogenerated from KST: please remove this line if doing any edits by hand!

use kaitai::{BytesReader, KStruct, KStructUnit};
use kaitai_test::expr_mod::ExprMod;
use std::fs;

#[test]
fn test_expr_mod() {
    let data = fs::read("../../src/fixed_struct.bin").expect("Unable to read data.");
    let reader = BytesReader::new(&data[..]);
    let r = ExprMod::default().read(&reader, None, KStructUnit::parent_stack()).unwrap();
    // assert_eq!(r.int_u, 1262698832);
    // assert_eq!(r.int_s, -52947);
    // assert_eq!(r.mod_pos_const, 9);
    // assert_eq!(r.mod_neg_const, 4);
    // assert_eq!(r.mod_pos_seq, 5);
    // assert_eq!(r.mod_neg_seq, 2);
}
