// Autogenerated from KST: please remove this line if doing any edits by hand!

#![allow(unused_variables)]
#![allow(unused_assignments)]
#![allow(overflowing_literals)]
use std::fs;
extern crate kaitai;
use self::kaitai::*;
use rust::formats::multiple_use::*;

#[test]
fn test_multiple_use() {
    let bytes = fs::read("../../src/position_abs.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let res: KResult<OptRc<MultipleUse>> = MultipleUse::read_into(&_io, None, None);
    let r : OptRc<MultipleUse>;

    if let Err(err) = res {
        panic!("{:?}", err);
    } else {
        r = res.unwrap();
    }

    assert_eq!(*r.t1().first_use().value(), 32);
    assert_eq!(*r.t2().second_use().expect("error reading").value(), 32);
}
