// Autogenerated from KST: please remove this line if doing any edits by hand!

use std::fs;
extern crate kaitai;
use self::kaitai::*;
use rust::formats::repeat_eos_bits_b4::*;

#[test]
fn test_repeat_eos_bits_b4() -> KResult<()> {
    let bytes = fs::read("../../src/enum_0.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let r: OptRc<RepeatEosBitsB4> = RepeatEosBitsB4::read_into(&_io, None, None)?;
    assert_eq!(r.nibbles().len(), 16);
    Ok(())
}
