// Autogenerated from KST: please remove this line if doing any edits by hand!

#![allow(unused_variables)]
#![allow(unused_assignments)]
#![allow(overflowing_literals)]
use std::fs;
extern crate kaitai;
use self::kaitai::*;
#[path = "../formats/mod.rs"] mod formats;
use formats::yaml_ints::*;

#[test]
fn test_yaml_ints() {
    let bytes = fs::read("../../src/fixed_struct.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let res: KResult<OptRc<YamlInts>> = YamlInts::read_into(&_io, None, None);
    let r : OptRc<YamlInts>;

    if let Err(err) = res {
        panic!("{:?}", err);
    } else {
        r = res.unwrap();
    }

    assert_eq!(*r.test_u4_dec().expect("error reading"), 4294967295);
    assert_eq!(*r.test_u4_hex().expect("error reading"), 4294967295);
    assert_eq!(*r.test_u8_dec().expect("error reading"), 18446744073709551615);
    assert_eq!(*r.test_u8_hex().expect("error reading"), 18446744073709551615);
}
