// Autogenerated from KST: please remove this line if doing any edits by hand!

extern crate kaitai_struct;
extern crate rust;

use kaitai_struct::KaitaiStruct;
use rust::SwitchManualIntSizeElse;

#[test]
fn test_switch_manual_int_size_else() {
    if let Ok(r) = SwitchManualIntSizeElse::from_file("src/switch_tlv.bin") {
        assert_eq!(r.chunks.len(), 4);
        assert_eq!(r.chunks[0].code, 17);
        assert_eq!(r.chunks[0].body.title, "Stuff");
        assert_eq!(r.chunks[0].body.author, "Me");
        assert_eq!(r.chunks[1].code, 34);
        assert_eq!(r.chunks[1].body.entries, ["AAAA", "BBBB", "CCCC"]);
        assert_eq!(r.chunks[2].code, 51);
        assert_eq!(r.chunks[2].body.rest, "\x10\x20\x30\x40\x50\x60\x70\x80");
        assert_eq!(r.chunks[3].code, 255);
        assert_eq!(r.chunks[3].body.rest, "");
    }
}
