// Autogenerated from KST: please remove this line if doing any edits by hand!

#![allow(unused_variables)]
#![allow(unused_assignments)]
#![allow(overflowing_literals)]
use std::fs;
extern crate kaitai;
use self::kaitai::*;
use rust::formats::enum_for_unknown_id::*;

#[test]
fn test_enum_for_unknown_id() {
    let bytes = fs::read("../../src/fixed_struct.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let res: KResult<OptRc<EnumForUnknownId>> = EnumForUnknownId::read_into(&_io, None, None);
    let r : OptRc<EnumForUnknownId>;

    if let Err(err) = res {
        panic!("{:?}", err);
    } else {
        r = res.unwrap();
    }

    let n : i64 = (&*r.one()).into();
    assert_eq!(n, 80);
}
