// Autogenerated from KST: please remove this line if doing any edits by hand!

use std::fs;
extern crate kaitai;
use self::kaitai::*;
use rust::formats::instance_std::*;

#[test]
fn test_instance_std() -> KResult<()> {
    let bytes = fs::read("../../src/str_encodings.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let r: OptRc<InstanceStd> = InstanceStd::read_into(&_io, None, None)?;

    assert_eq!(*r.header()?, "Some ");
    Ok(())
}
