// Autogenerated from KST: please remove this line if doing any edits by hand!

use std::fs;
extern crate kaitai;
use self::kaitai::*;
use rust::formats::str_pad_term::*;

#[test]
fn test_str_pad_term() -> KResult<()> {
    let bytes = fs::read("../../src/str_pad_term.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let r: OptRc<StrPadTerm> = StrPadTerm::read_into(&_io, None, None)?;

    assert_eq!(*r.str_pad(), "str1");
    assert_eq!(*r.str_term(), "str2foo");
    assert_eq!(*r.str_term_and_pad(), "str+++3bar+++");
    assert_eq!(*r.str_term_include(), "str4baz@");
    Ok(())
}
