// Autogenerated from KST: please remove this line if doing any edits by hand!

extern crate kaitai_struct;
extern crate rust;

use kaitai_struct::KaitaiStruct;
use rust::TermBytes;

#[test]
fn test_term_bytes() {
    if let Ok(r) = TermBytes::from_file("src/term_strz.bin") {
        assert_eq!(r.s1, "\x66\x6F\x6F");
        assert_eq!(r.s2, "\x62\x61\x72");
        assert_eq!(r.s3, "\x7C\x62\x61\x7A\x40");
    }
}
