// Autogenerated from KST: please remove this line if doing any edits by hand!

use std::fs;
extern crate kaitai;
use self::kaitai::*;
use rust::formats::bits_shift_by_b32_le::*;

#[test]
fn test_bits_shift_by_b32_le() -> KResult<()> {
    let bytes = fs::read("../../src/bits_shift_by_b32_le.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let r: OptRc<BitsShiftByB32Le> = BitsShiftByB32Le::read_into(&_io, None, None)?;

    assert_eq!(*r.a(), 4294967295);
    assert_eq!(*r.b(), 0);
    Ok(())
}
