// Autogenerated from KST: please remove this line if doing any edits by hand!

use std::fs;
extern crate kaitai;
use self::kaitai::*;
use rust::formats::type_ternary::*;

#[test]
fn test_type_ternary() -> KResult<()> {
    let bytes = fs::read("../../src/term_strz.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let r: OptRc<TypeTernary> = TypeTernary::read_into(&_io, None, None)?;

    assert_eq!(*r.dif()?.value(), 101);
    Ok(())
}
