// Autogenerated from KST: please remove this line if doing any edits by hand!

#![allow(unused_variables)]
#![allow(unused_assignments)]
#![allow(overflowing_literals)]
use std::fs;
extern crate kaitai;
use self::kaitai::*;
use rust::formats::cast_to_imported::*;
use rust::formats::hello_world::*;

#[test]
fn test_cast_to_imported() {
    let bytes = fs::read("../../src/fixed_struct.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let res: KResult<OptRc<CastToImported>> = CastToImported::read_into(&_io, None, None);
    let r : OptRc<CastToImported>;

    if let Err(err) = res {
        panic!("{:?}", err);
    } else {
        r = res.unwrap();
    }

    assert_eq!(*r.one().one(), 80);
    assert_eq!(*r.one_casted().expect("error reading").one(), 80);
}
