// Autogenerated from KST: please remove this line if doing any edits by hand!

use std::fs;

extern crate kaitai;
use self::kaitai::*;
mod formats;
use formats::valid_fail_expr::*;

#[test]
fn test_valid_fail_expr() {
    let bytes = fs::read("../../src/nav_parent_switch.bin").unwrap();
    let reader = BytesReader::new(&bytes);
    let mut r = ValidFailExpr::default();

    if let Err(err) = r.read(&reader, None, Some(KStructUnit::parent_stack())) {
        println!("expected err: {:?}, exception: ValidationExprError(IntMultiType(true,Width2,None))", err);
    } else {
        panic!("no expected exception: ValidationExprError(IntMultiType(true,Width2,None))");
    }
}
