// Autogenerated from KST: please remove this line if doing any edits by hand!

use std::fs;
extern crate kaitai;
use self::kaitai::*;
use rust::formats::nav_parent_override::*;

#[test]
fn test_nav_parent_override() -> KResult<()> {
    let bytes = fs::read("../../src/nav_parent_codes.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let r: OptRc<NavParentOverride> = NavParentOverride::read_into(&_io, None, None)?;

    assert_eq!(*r.child_size(), 3);
    assert_eq!(*r.child_1().data(), vec![0x49u8, 0x31u8, 0x32u8]);
    assert_eq!(*r.mediator_2().child_2().data(), vec![0x33u8, 0x42u8, 0x62u8]);
    Ok(())
}
