// Autogenerated from KST: please remove this line if doing any edits by hand!

use std::fs;
extern crate kaitai;
use self::kaitai::*;
use rust::formats::str_pad_term_empty::*;

#[test]
fn test_str_pad_term_empty() -> KResult<()> {
    let bytes = fs::read("../../src/str_pad_term_empty.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let r: OptRc<StrPadTermEmpty> = StrPadTermEmpty::read_into(&_io, None, None)?;

    assert_eq!(*r.str_pad(), "");
    assert_eq!(*r.str_term(), "");
    assert_eq!(*r.str_term_and_pad(), "");
    assert_eq!(*r.str_term_include(), "@");
    Ok(())
}
