// Autogenerated from KST: please remove this line if doing any edits by hand!

extern crate kaitai_struct;
extern crate rust;

use kaitai_struct::KaitaiStruct;
use rust::TypeTernary;

#[test]
fn test_type_ternary() {
    if let Ok(r) = TypeTernary::from_file("src/term_strz.bin") {
        assert_eq!(r.dif.value, 101);
    }
}
