// Autogenerated from KST: please remove this line if doing any edits by hand!

use kaitai_struct::KaitaiStruct;
use kaitai_test_suite::user_type::UserType;

#[test]
fn test_user_type() {
    let r = UserType::from_file("../../src/repeat_until_s4.bin").expect("file for parsing is not found");

    assert_eq!(r.one.width, 66);
    assert_eq!(r.one.height, 4919);
}
