# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.meta_xref import MetaXref

class TestMetaXref(unittest.TestCase):
    def test_meta_xref(self):
        with MetaXref.from_file('src/fixed_struct.bin') as r:
            pass
