# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.recursive_one import RecursiveOne

class TestRecursiveOne(unittest.TestCase):
    def test_recursive_one(self):
        with RecursiveOne.from_file('src/fixed_struct.bin') as r:
            self.assertEqual(r.one, 80)
            self.assertEqual(r.next.one, 65)
            self.assertEqual(r.next.next.one, 67)
            self.assertEqual(r.next.next.next.finisher, 11595)
