# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.valid_fail_eq_str import ValidFailEqStr
import kaitaistruct

class TestValidFailEqStr(unittest.TestCase):
    def test_valid_fail_eq_str(self):
        with self.assertRaises(kaitaistruct.ValidationNotEqualError):
            with ValidFailEqStr.from_file('src/fixed_struct.bin') as r:
                pass
