# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
import kaitaistruct

from testformats.eos_exception_bytes import EosExceptionBytes

class TestEosExceptionBytes(unittest.TestCase):
    def test_eos_exception_bytes(self):
        with self.assertRaisesRegexp(EOFError, u"^requested \\d+ bytes, but only \\d+ bytes available$"):
            with EosExceptionBytes.from_file('src/term_strz.bin') as r:
                pass
