# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.term_strz_utf16_v1 import TermStrzUtf16V1

class TestTermStrzUtf16V1(unittest.TestCase):
    def test_term_strz_utf16_v1(self):
        with TermStrzUtf16V1.from_file('src/term_strz_utf16.bin') as r:
            self.assertEqual(r.s1, u"a\u0200b")
            self.assertEqual(r.s2, u"c\u0200d")
            self.assertEqual(r.term, 0)
            self.assertEqual(r.s3, u"e\u0200f\000")
