# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest

from testformats.instance_in_repeat_expr import InstanceInRepeatExpr

class TestInstanceInRepeatExpr(unittest.TestCase):
    def test_instance_in_repeat_expr(self):
        with InstanceInRepeatExpr.from_file('src/instance_in_repeat_expr.bin') as r:

            self.assertEqual(len(r.chunks), 2)
            self.assertEqual(r.chunks[0].offset, 16)
            self.assertEqual(r.chunks[0].len, 8312)
            self.assertEqual(r.chunks[1].offset, 8328)
            self.assertEqual(r.chunks[1].len, 15)
