# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.integers_double_overflow import IntegersDoubleOverflow

class TestIntegersDoubleOverflow(unittest.TestCase):
    def test_integers_double_overflow(self):
        with IntegersDoubleOverflow.from_file('src/integers_double_overflow.bin') as r:
            self.assertEqual(r.signed_safe_min_be, -9007199254740991)
            self.assertEqual(r.signed_safe_min_le, -9007199254740991)
            self.assertEqual(r.signed_safe_max_be, 9007199254740991)
            self.assertEqual(r.signed_safe_max_le, 9007199254740991)
            self.assertEqual(str(r.signed_unsafe_neg_be), u"-9007199254740993")
            self.assertEqual(str(r.signed_unsafe_neg_le), u"-9007199254740993")
            self.assertEqual(str(r.signed_unsafe_pos_be), u"9007199254740993")
            self.assertEqual(str(r.signed_unsafe_pos_be), u"9007199254740993")
