# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.params_pass_bool import ParamsPassBool

class TestParamsPassBool(unittest.TestCase):
    def test_params_pass_bool(self):
        with ParamsPassBool.from_file('src/term_strz.bin') as r:
            self.assertEqual(r.s_false, False)
            self.assertEqual(r.s_true, True)
            self.assertEqual(r.seq_b1.arg, True)
            self.assertEqual(len(r.seq_b1.foo), 1)
            self.assertEqual(r.seq_bool.arg, False)
            self.assertEqual(len(r.seq_bool.foo), 2)
            self.assertEqual(r.literal_b1.arg, False)
            self.assertEqual(len(r.literal_b1.foo), 2)
            self.assertEqual(r.literal_bool.arg, True)
            self.assertEqual(len(r.literal_bool.foo), 1)
            self.assertEqual(r.inst_b1.arg, True)
            self.assertEqual(len(r.inst_b1.foo), 1)
            self.assertEqual(r.inst_bool.arg, False)
            self.assertEqual(len(r.inst_bool.foo), 2)
