# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest

from testformats.process_struct_pad_term import ProcessStructPadTerm

class TestProcessStructPadTerm(unittest.TestCase):
    def test_process_struct_pad_term(self):
        with ProcessStructPadTerm.from_file('src/str_pad_term.bin') as r:

            self.assertEqual(r.str_pad.value, b"\x66\x61\x67\x24")
            self.assertEqual(r.str_term.value, b"\x66\x61\x67\x27\x73\x7A\x7A")
            self.assertEqual(r.str_term_and_pad.value, b"\x66\x61\x67\x3E\x3E\x3E\x26\x77\x74\x67\x3E\x3E\x3E")
            self.assertEqual(r.str_term_include.value, b"\x66\x61\x67\x21\x77\x74\x6F\x55")
