# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.str_encodings_default import StrEncodingsDefault

class TestStrEncodingsDefault(unittest.TestCase):
    def test_str_encodings_default(self):
        with StrEncodingsDefault.from_file('src/str_encodings.bin') as r:
            self.assertEqual(r.str1, u"Some ASCII")
            self.assertEqual(r.rest.str2, u"\u3053\u3093\u306b\u3061\u306f")
            self.assertEqual(r.rest.str3, u"\u3053\u3093\u306b\u3061\u306f")
            self.assertEqual(r.rest.str4, u"\u2591\u2592\u2593")
