# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.enum_to_i_invalid import EnumToIInvalid
from testformats import enum_to_i_invalid

class TestEnumToIInvalid(unittest.TestCase):
    def test_enum_to_i_invalid(self):
        with EnumToIInvalid.from_file('src/term_strz.bin') as r:
            self.assertEqual(r.pet_1, enum_to_i_invalid.EnumToIInvalid.Animal.dog)
            self.assertEqual(r.pet_2, 111)
            self.assertEqual(r.pet_2_i, 111)
            self.assertEqual(r.pet_2_i_to_s, u"111")
            self.assertEqual(r.pet_2_mod, 32879)
            self.assertEqual(r.one_lt_two, True)
            self.assertEqual(r.pet_2_eq_int_t, True)
            self.assertEqual(r.pet_2_eq_int_f, False)
