# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.instance_std import InstanceStd

class TestInstanceStd(unittest.TestCase):
    def test_instance_std(self):
        with InstanceStd.from_file('src/str_encodings.bin') as r:
            self.assertEqual(r.header, u"Some ")
