#!/bin/sh

. ./config

rm -rf "$FORMATS_COMPILED_DIR"
mkdir -p "$FORMATS_COMPILED_DIR"
"$COMPILER_DIR/jvm/target/universal/stage/bin/kaitai-struct-compiler" -- \
	--verbose all -t all -d "$FORMATS_COMPILED_DIR" \
	-I "$FORMATS_REPO_DIR" \
	--java-package io.kaitai.struct.testformats \
	--php-namespace 'Kaitai\Struct\Tests' \
	"$FORMATS_KSY_DIR"/*.ksy
