#!/bin/sh

. ./config

rm -rf "$FORMATS_COMPILED_DIR"
mkdir -p "$FORMATS_COMPILED_DIR"
"$COMPILER_DIR/jvm/target/universal/stage/bin/kaitai-struct-compiler" -- \
	--verbose all -t all -d "$FORMATS_COMPILED_DIR" \
	--import-path "$FORMATS_REPO_DIR" \
	--import-path "$FORMATS_KSY_DIR/ks_path" \
	--java-package io.kaitai.struct.testformats \
	--php-namespace 'Kaitai\Struct\Tests' \
	--go-package test_formats \
	"$FORMATS_KSY_DIR"/*.ksy || :
