#!/bin/sh

. ./config

# Run Construct + Python 2 tests
echo '#################### construct2'
./travis-fold construct2 ./ci-construct2

# Run Construct + Python 3 tests
echo '#################### construct3'
./travis-fold construct3 ./ci-construct3

# Run C# tests
echo '#################### csharp'
./travis-fold csharp ./ci-csharp

# Run C++/STL tests, generates JUnit XML report
echo '#################### cpp_stl'
./travis-fold cpp_stl ./ci-cpp_stl

# Run Go tests, generates JUnit XML report
echo '#################### go'
./travis-fold go ./ci-go

# Run Java tests, generates JUnit XML report by default
echo '#################### java'
./travis-fold java ./ci-java

# Run JavaScript tests, generate JUnit-like report
echo '#################### javascript'
./travis-fold javascript ./ci-javascript

# Run Lua tests, generate JUnit-like report
echo '#################### lua'
./travis-fold lua ./ci-lua

# Run Perl tests, generate JUnit-like report
echo '#################### perl'
./travis-fold perl ./ci-perl

# Run PHP tests, generate JUnit-like report
echo '#################### php'
./travis-fold php ./ci-php

# Run Python 2 tests, generate bunch of JUnit-like reports
echo '#################### python2'
./travis-fold python2 ./ci-python2

# Run Python 3 tests, generate bunch of JUnit-like reports
echo '#################### python3'
./travis-fold python3 ./ci-python3

# Run Ruby tests, generate JSON report
echo '#################### ruby'
./travis-fold ruby ./ci-ruby

# Aggregate
./aggregate-reports
