#!/bin/sh

. ./config

# Run C# tests
echo '#################### csharp'
./ci-csharp

# Run C++/STL tests, generates JUnit XML report
echo '#################### cpp_stl'
./ci-cpp_stl

# Run Go tests, generates JUnit XML report
echo '#################### go'
./ci-go

# Run Java tests, generates JUnit XML report by default
echo '#################### java'
./ci-java

# Run JavaScript tests, generate JUnit-like report
echo '#################### javascript'
./ci-javascript

# Run Lua tests, generate JUnit-like report
echo '#################### lua'
./ci-lua

# Run Perl tests, generate JUnit-like report
echo '#################### perl'
./ci-perl

# Run PHP tests, generate JUnit-like report
echo '#################### php'
./ci-php

# Run Python 2 tests, generate bunch of JUnit-like reports
echo '#################### python2'
./ci-python2

# Run Python 3 tests, generate bunch of JUnit-like reports
echo '#################### python3'
./ci-python3

# Run Ruby tests, generate JSON report
echo '#################### ruby'
./ci-ruby

# Aggregate
echo '#################### ... aggregation'
aggregate/aggregate "$COMPILER_DIR/target/test_out/TEST-io.kaitai.struct.translators.TranslatorSpec.xml" "$TEST_OUT_DIR" "$TEST_OUT_DIR/full.html"
