#!/bin/sh

. ./config

# Run C# tests
echo '#################### csharp'
./run-csharp

# Run C++/STL tests, generates JUnit XML report
echo '#################### cpp_stl'
./run-cpp_stl

# Run Java tests, generates JUnit XML report by default
echo '#################### java'
./run-java

# Run JavaScript tests, generate JUnit-like report
echo '#################### javascript'
mkdir -p "$TEST_OUT_DIR/javascript"
NODE_PATH=compiled/javascript:helpers/javascript:$JAVASCRIPT_MODULES_DIR:$JAVASCRIPT_RUNTIME_DIR \
	$JAVASCRIPT_MODULES_DIR/mocha/bin/mocha \
	-R xunit spec/javascript >"$TEST_OUT_DIR/javascript/test-output-javascript.xml"

# Run Perl tests, generate JUnit-like report
echo '#################### perl'
./run-perl

# Run PHP tests, generate JUnit-like report
echo '#################### php'
./run-php

# Run Python 2 tests, generate bunch of JUnit-like reports
echo '#################### python2'
rm -rf "$TEST_OUT_DIR/python2"
PYTHONPATH="$PYTHON_RUNTIME_DIR:compiled/python" python2 ./run-python-xml.py spec/python "$TEST_OUT_DIR/python2"

# Run Python 3 tests, generate bunch of JUnit-like reports
echo '#################### python3'
rm -rf "$TEST_OUT_DIR/python3"
PYTHONPATH="$PYTHON_RUNTIME_DIR:compiled/python" python3 ./run-python-xml.py spec/python "$TEST_OUT_DIR/python3"

# Run Ruby tests, generate JSON report
echo '#################### ruby'
mkdir -p "$TEST_OUT_DIR/ruby"
rspec -I compiled/ruby -I "$RUBY_RUNTIME_DIR" -f json >"$TEST_OUT_DIR/ruby/test-output-ruby.json"

# Aggregate
echo '#################### ... aggregation'
aggregate/aggregate "$COMPILER_DIR/target/test_out/TEST-io.kaitai.struct.translators.TranslatorSpec.xml" "$TEST_OUT_DIR" "$TEST_OUT_DIR/full.html"
