#!/bin/sh

./run-cpp_stl

# Run C++/STL valgrind check, generates Valgrind XML report
echo 'Running Valgrind checks...'
if valgrind --version; then
	./valgrind-cpp_stl
else
	echo 'Valgrind not found :-('
fi
