#!/bin/sh

. ./config

rm -rf "$TEST_OUT_DIR/construct"
PYTHONPATH="compiled/construct" PYTHONDONTWRITEBYTECODE=1 PYTHONDEVMODE=1 python run-python-xml.py spec/construct "$TEST_OUT_DIR/construct"

./kst-adoption-report construct
aggregate/convert_to_json construct "$TEST_OUT_DIR/construct" "$TEST_OUT_DIR/construct/ci.json"
