#!/bin/sh

. ./config

export GOPATH=$HOME/go
export GOPATH=$GOPATH:$(pwd)/compiled/go

# Symlink Go runtime libraries from full umbrella project checkout
mkdir -p compiled/go/src/github.com/kaitai-io
rm -f compiled/go/src/github.com/kaitai-io/kaitai_struct_go_runtime
ln -s ../../../../../../runtime/go compiled/go/src/github.com/kaitai-io/kaitai_struct_go_runtime

ABS_TEST_OUT_DIR="$(pwd)/$TEST_OUT_DIR"
ABS_REPORT_LOG="$ABS_TEST_OUT_DIR/go/report.log"
mkdir -p "$TEST_OUT_DIR/go"
rm -f "$TEST_OUT_DIR/go/build.fails"

cd spec/go

keep_compiling=1
while [ "$keep_compiling" = 1 ]; do
	if go test -v . >"$ABS_REPORT_LOG" 2>&1; then
		keep_compiling=0
	else
		echo "Got error:"
		cat "$ABS_REPORT_LOG"
		if egrep "^\.\./\.\./compiled/go/.*:[0-9][0-9]*:" "$ABS_REPORT_LOG" >"$ABS_TEST_OUT_DIR/go/err.now"; then
			cat "$ABS_TEST_OUT_DIR/go/err.now" >>"$ABS_TEST_OUT_DIR/go/build.fails"
			sed 's/:.*//' <"$ABS_TEST_OUT_DIR/go/err.now" | sort -u >"$ABS_TEST_OUT_DIR/go/to_delete.now"
			xargs rm <"$ABS_TEST_OUT_DIR/go/to_delete.now"
			echo "Trying to recover..."
			keep_compiling=1
		else
			echo "Unable to recover, bailing out :("
			keep_compiling=0
			exit 1
		fi
	fi
done

cd ../..
cat "$ABS_TEST_OUT_DIR/go/report.log"
$HOME/go/bin/go-junit-report <"$ABS_TEST_OUT_DIR/go/report.log" >"$ABS_TEST_OUT_DIR/go/report.xml"
