#!/bin/sh

. ./config

# Symlinks fresh KS JavaScript runtime into node_modules dir
mkdir -p "$JAVASCRIPT_MODULES_DIR"
if [ ! -e "$JAVASCRIPT_MODULES_DIR/kaitai-struct" ]; then
    ln -s "$JAVASCRIPT_RUNTIME_DIR" "$JAVASCRIPT_MODULES_DIR/kaitai-struct"
fi

mkdir -p "$TEST_OUT_DIR/javascript"
NODE_PATH=compiled/javascript:helpers/javascript:$JAVASCRIPT_MODULES_DIR:$JAVASCRIPT_RUNTIME_DIR \
	$JAVASCRIPT_MODULES_DIR/mocha/bin/mocha \
	-R xunit spec/javascript >"$TEST_OUT_DIR/javascript/test-output-javascript.xml"
