#!/bin/sh

. ./config

rm -rf "$TEST_OUT_DIR/lua"
mkdir -p "$TEST_OUT_DIR/lua"
export LUA_PATH="$LUA_PATH;$LUA_RUNTIME_DIR/?.lua;spec/lua/?.lua;spec/lua/extra/?.lua;compiled/lua/?.lua;;"

# Detect lua executable
if lua5.3 -v; then
	LUA_BIN=lua5.3
elif lua -v; then
	LUA_BIN=lua
else
	echo "Unable to detect lua executable, bailing out :("
	exit 1
fi

"$LUA_BIN" spec/lua/run_test_suite.lua -v -o junit -n "$TEST_OUT_DIR/lua/report"
