#!/bin/sh

. ./config

rm -rf "$TEST_OUT_DIR/lua"
mkdir -p "$TEST_OUT_DIR/lua"
export LUA_PATH="$LUA_PATH;$LUA_RUNTIME_DIR/?.lua;spec/lua/?.lua;spec/lua/extra/?.lua;compiled/lua/?.lua;;"
lua5.3 spec/lua/run_test_suite.lua -v -o junit -n "$TEST_OUT_DIR/lua/report"
