#!/bin/sh

. ./config

nimble refresh
nimble test

rm -rf "$TEST_OUT_DIR/nim"
mkdir -p "$TEST_OUT_DIR/nim"
nim c -r --outdir:"$TEST_OUT_DIR/nim/bin" "spec/nim/generate_test_suite" "ci"
nim c -r --outdir:"$TEST_OUT_DIR/nim/bin" "spec/nim/test"
rm -r "$TEST_OUT_DIR/nim/bin"

./kst-adoption-report nim
aggregate/convert_to_json nim "$TEST_OUT_DIR/nim" "$TEST_OUT_DIR/nim/ci.json"
