#!/bin/sh

. ./config

rm -rf "$TEST_OUT_DIR/python"
mkdir -p "$TEST_OUT_DIR/python"
PYTHONPATH="$PYTHON_RUNTIME_DIR:compiled/python:spec/python/extra" PYTHONDONTWRITEBYTECODE=1 PYTHONDEVMODE=1 python ./run-python-xml.py "$TEST_OUT_DIR/python/report.xml" discover -s spec/python

./kst-adoption-report python
aggregate/convert_to_json python "$TEST_OUT_DIR/python" "$TEST_OUT_DIR/python/ci.json"
