#!/bin/sh

. "$(dirname "$0")/config"

rm -rf "$TEST_OUT_DIR/python" "$TEST_OUT_DIR/python-write"
mkdir -p "$TEST_OUT_DIR/python" "$TEST_OUT_DIR/python-write"
PYTHONPATH="$PYTHON_RUNTIME_DIR:compiled/python:spec/python/extra" PYTHONDONTWRITEBYTECODE=1 PYTHONDEVMODE=1 python -m xmlrunner --output-file "$TEST_OUT_DIR/python/report.xml" --outsuffix '' discover -s spec/python/spec
PYTHONPATH="$PYTHON_RUNTIME_DIR:compiled/python:spec/python:spec/python/extra" PYTHONDONTWRITEBYTECODE=1 PYTHONDEVMODE=1 python -m xmlrunner --output-file "$TEST_OUT_DIR/python-write/report.xml" --outsuffix '' discover -s spec/python/specwrite

./kst-adoption-report python
./kst-adoption-report python-write
aggregate/convert_to_json python "$TEST_OUT_DIR/python" "$TEST_OUT_DIR/python/ci.json"
aggregate/convert_to_json python-write "$TEST_OUT_DIR/python-write" "$TEST_OUT_DIR/python-write/ci.json"
