#!/bin/sh

. ./config

mkdir -p "$TEST_OUT_DIR/ruby"
rspec -I compiled/ruby -I "$RUBY_RUNTIME_DIR" -f json --out "$TEST_OUT_DIR/ruby/test-output-ruby.json" spec/ruby

aggregate/convert_to_json ruby "$TEST_OUT_DIR/ruby/test-output-ruby.json" "$TEST_OUT_DIR/ruby/ci.json"
