#!/bin/sh
set -eu
. ./config

mkdir -p "$TEST_OUT_DIR/rust"

rm -r "spec/rust/src"
mkdir -p "spec/rust/src/"
for rs in $(ls "$FORMATS_COMPILED_DIR/rust/"); do
    cp "$FORMATS_COMPILED_DIR/rust/$rs" "spec/rust/src"
    mod_name="$(echo "$rs" | cut -d'.' -f1)"
    echo "pub mod $mod_name;" >> "spec/rust/src/lib.rs"
done

cargo junit --name "../../$TEST_OUT_DIR/rust/results.xml"
