#!/bin/sh

. ./config

mkdir -p "$TEST_OUT_DIR/ruby"
rspec -I compiled/ruby -I "$RUBY_RUNTIME_DIR" -f json --out "$TEST_OUT_DIR/ruby/test-output-ruby.json" spec/ruby

# In Travis, we'll be running different (probably old and obsolete) version of Ruby at this point,
# so we'll need to make sure we explicitly run system Ruby.
if [ -n "$TRAVIS" ]; then
	echo 'Running in Travis, running system Ruby explicitly.'
	/usr/bin/ruby --version
	/usr/bin/ruby aggregate/convert_to_json ruby "$TEST_OUT_DIR/ruby/test-output-ruby.json" "$TEST_OUT_DIR/ruby/ci.json"
else
	# This one will run Ruby through shebang, which would use /usr/bin/env to find `ruby` in $PATH.
	aggregate/convert_to_json ruby "$TEST_OUT_DIR/ruby/test-output-ruby.json" "$TEST_OUT_DIR/ruby/ci.json"
fi
