#!/bin/sh

COMPILER_DIR=../compiler
TEST_DIR="$(pwd)"
DEST_DIR="$TEST_DIR/compiled"

rebuild_compiler()
{
	cd "$COMPILER_DIR"
	sbt compilerJVM/stage
	cd "$TEST_DIR"
}

rebuild_compiler
rm -rf "$DEST_DIR"
mkdir -p "$DEST_DIR"
$COMPILER_DIR/jvm/target/universal/stage/bin/kaitai-struct-compiler -- \
	--verbose -t all -d "$DEST_DIR" --java-package io.kaitai.struct.testformats formats/*.ksy
