#!/bin/sh

COMPILER_DIR=../compiler
TEST_DIR="$(pwd)"
DEST_DIR="$TEST_DIR/compiled"

rebuild_compiler()
{
	cd "$COMPILER_DIR"
    sbt universal:packageBin
    rm -rf runnable
    mkdir -p runnable
    unzip -q target/universal/kaitai-struct-compiler-*.zip -d runnable
    cd "$TEST_DIR"
}

rebuild_compiler
rm -rf "$DEST_DIR"
mkdir -p "$DEST_DIR"
$COMPILER_DIR/runnable/kaitai-struct*/bin/kaitai-struct-compiler -- \
	--verbose -t all -d "$DEST_DIR" --java-package io.kaitai.struct.testformats formats/*.ksy
