#!/bin/sh

. ./config

mkdir -p "$TEST_OUT_DIR/php"

export PHP_RUNTIME_DIR
"$PHP_RUNTIME_DIR"/vendor/bin/phpunit spec/php \
	--bootstrap spec/php/_bootstrap.php \
	--log-junit "$TEST_OUT_DIR/php/results.xml" \
	--dont-report-useless-tests
