#!/bin/sh -ef

. "$(dirname "$0")/config"

# rspec is available with and without extension in Windows and the file without extension doesn't
# work if Ruby is installed in a path with spaces, but is used by default in environments like Git
# Bash.
if [ "$OS" = "Windows_NT" ]; then
	EXEC_EXT=".bat"
fi

rspec${EXEC_EXT} -I compiled/ruby -I "$RUBY_RUNTIME_DIR" spec/ruby
