#!/bin/sh

# Takes specs for Ruby and tries to translate them all into other
# languages. If file already exists, just skips it, thus creating only
# missing specs

RUBY_SPEC_DIR=spec/ruby
PYTHON_SPEC_DIR=spec/python
JAVA_SPEC_DIR=spec/java/src/io/kaitai/struct/spec
CPP_STL_SPEC_DIR=spec/cpp_stl

generate_spec()
{
	local src_spec="$1"
	local dst_spec="$2"
	local lang="$3"

	if [ ! -r "$dst_spec" ]; then
		echo "$lang: $dst_spec"
#		echo "./spec_ruby_to_$lang" "$src_spec" "$dst_spec"
	fi
}

for FN in "$RUBY_SPEC_DIR"/*_spec.rb; do
	SPEC=$(basename "$FN" | sed 's/_spec\.rb$//')
	UCC_SPEC=$(echo "$SPEC" | ruby -e 'puts gets.chomp.split(/_/).map { |x| x.capitalize }.join')

	generate_spec "$FN" "$PYTHON_SPEC_DIR/test_$SPEC.py" python
	generate_spec "$FN" "$JAVA_SPEC_DIR/Test${UCC_SPEC}.java" java
	generate_spec "$FN" "$CPP_STL_SPEC_DIR/test_$SPEC.cpp" cpp_stl
done
