// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');
var hexString = require('hexString');

testHelper('BitsByteAligned', 'src/fixed_struct.bin', function(r, BitsByteAligned) {
  assert.strictEqual(r.one, 20);
  assert.strictEqual(r.byte1, 65);
  assert.strictEqual(r.two, 2);
  assert.strictEqual(r.three, false);
  assert.strictEqual(r.byte2, 75);
  assert.strictEqual(r.four, 2892);
  assert.strictEqual(hexString(r.byte3), hexString([255]));
  assert.strictEqual(r.fullByte, 255);
  assert.strictEqual(r.byte4, 80);
});
