// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');

testHelper('ProcessToUser', 'src/process_rotate.bin', function(r) {
  assert.strictEqual(r.buf1.str, "Hello");
});
