// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelperThrows = require('testHelperThrows');
var KaitaiStream = require('kaitai-struct/KaitaiStream');

testHelperThrows('EofExceptionBytes', 'src/term_strz.bin', KaitaiStream.EOFError);
