// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');

testHelper('NavParentSwitchCast', 'src/switch_integers.bin', function(r, NavParentSwitchCast) {

  assert.strictEqual(r.foo.bufType, 1);
  assert.strictEqual(r.foo.flag, 7);
  assert.strictEqual(r.foo.buf.bar.flag, 7);
});
