// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');

testHelper('FloatToI', 'src/floating_points.bin', function(r, FloatToI_) {
  assert.strictEqual(r.singleValue, 0.5);
  assert.strictEqual(r.doubleValue, 0.25);
  assert.strictEqual(r.singleI, 0);
  assert.strictEqual(r.doubleI, 0);
  assert.strictEqual(r.float1I, 1);
  assert.strictEqual(r.float2I, 1);
  assert.strictEqual(r.float3I, 1);
  assert.strictEqual(r.float4I, -2);
});
