// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');

testHelper('CastToImported', 'src/fixed_struct.bin', function(r, CastToImported) {
  assert.strictEqual(r.one.one, 80);
  assert.strictEqual(r.oneCasted.one, 80);
});
