// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');

testHelper('BytesPadTerm', 'src/str_pad_term.bin', function(r, BytesPadTerm_) {
  assert.deepStrictEqual(r.strPad, new Uint8Array([115, 116, 114, 49]));
  assert.deepStrictEqual(r.strTerm, new Uint8Array([115, 116, 114, 50, 102, 111, 111]));
  assert.deepStrictEqual(r.strTermAndPad, new Uint8Array([115, 116, 114, 43, 43, 43, 51, 98, 97, 114, 43, 43, 43]));
  assert.deepStrictEqual(r.strTermInclude, new Uint8Array([115, 116, 114, 52, 98, 97, 122, 64]));
});
