// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');

testHelper('NavParent3', 'src/nav_parent2.bin', function(r, NavParent3_) {
  assert.strictEqual(r.ofsTags, 8);
  assert.strictEqual(r.numTags, 2);
  assert.strictEqual(r.tags[0].name, "RAHC");
  assert.strictEqual(r.tags[0].ofs, 32);
  assert.strictEqual(r.tags[0].numItems, 3);
  assert.strictEqual(r.tags[0].tagContent.content, "foo");
  assert.strictEqual(r.tags[1].name, "RAHC");
  assert.strictEqual(r.tags[1].ofs, 35);
  assert.strictEqual(r.tags[1].numItems, 6);
  assert.strictEqual(r.tags[1].tagContent.content, "barbaz");
});
