// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');

testHelper('EnumIntRangeU', 'src/enum_int_range_u.bin', function(r, EnumIntRangeU) {

  assert.strictEqual(r.f1, EnumIntRangeU.Constants.ZERO);
  assert.strictEqual(r.f2, EnumIntRangeU.Constants.INT_MAX);
});
