// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');

testHelper('CombineStr', 'src/term_strz.bin', function(r, CombineStr_) {
  assert.strictEqual(r.strTerm, "foo");
  assert.strictEqual(r.strLimit, "bar|");
  assert.strictEqual(r.strEos, "baz@");
  assert.strictEqual(r.strCalc, "bar");
  assert.strictEqual(r.strCalcBytes, "baz");
  assert.strictEqual(r.termOrLimit, "foo");
  assert.strictEqual(r.termOrEos, "baz@");
  assert.strictEqual(r.termOrCalc, "foo");
  assert.strictEqual(r.termOrCalcBytes, "baz");
  assert.strictEqual(r.limitOrEos, "bar|");
  assert.strictEqual(r.limitOrCalc, "bar");
  assert.strictEqual(r.limitOrCalcBytes, "bar|");
  assert.strictEqual(r.eosOrCalc, "bar");
  assert.strictEqual(r.eosOrCalcBytes, "baz@");
  assert.strictEqual(r.calcOrCalcBytes, "baz");
});
