// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');

testHelper('SwitchRepeatExpr', 'src/switch_tlv.bin', function(r, SwitchRepeatExpr_) {
  assert.strictEqual(r.code, 17);
  assert.strictEqual(r.size, 9);
  assert.deepStrictEqual(r.body[0].first, new Uint8Array([83, 116, 117, 102, 102, 0, 77, 101, 0]));
});
