// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');

testHelper('StrEncodingsDefault', 'src/str_encodings.bin', function(r, StrEncodingsDefault_) {
  assert.strictEqual(r.str1, "Some ASCII");
  assert.strictEqual(r.rest.str2, "\u3053\u3093\u306b\u3061\u306f");
  assert.strictEqual(r.rest.str3, "\u3053\u3093\u306b\u3061\u306f");
  assert.strictEqual(r.rest.str4, "\u2591\u2592\u2593");
});
