// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');

testHelper('BitsSignedB32Le', 'src/bits_signed_b32_le.bin', function(r, BitsSignedB32Le) {

  assert.strictEqual(r.aNum, 0);
  assert.strictEqual(r.aBit, true);
  assert.strictEqual(r.bNum, 2147483647);
  assert.strictEqual(r.bBit, false);
});
