// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');

testHelper('EnumDeepLiterals', 'src/enum_0.bin', function(r, EnumDeepLiterals_) {
  assert.strictEqual(r.isPet1Ok, true);
  assert.strictEqual(r.isPet2Ok, true);
});
