// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');

testHelper('EnumOfValueInst', 'src/enum_0.bin', function(r, EnumOfValueInst) {
  assert.strictEqual(r.pet1, EnumOfValueInst.Animal.CAT);
  assert.strictEqual(r.pet2, EnumOfValueInst.Animal.CHICKEN);
  assert.strictEqual(r.pet3, EnumOfValueInst.Animal.DOG);
  assert.strictEqual(r.pet4, EnumOfValueInst.Animal.DOG);
});
