// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');

testHelper('BitsSimple', 'src/fixed_struct.bin', function(r, BitsSimple_) {
  assert.strictEqual(r.byte1, 80);
  assert.strictEqual(r.byte2, 65);
  assert.strictEqual(r.bitsA, false);
  assert.strictEqual(r.bitsB, 4);
  assert.strictEqual(r.bitsC, 3);
  assert.strictEqual(r.largeBits1, 300);
  assert.strictEqual(r.spacer, 5);
  assert.strictEqual(r.largeBits2, 1329);
  assert.strictEqual(r.normalS2, -1);
  assert.strictEqual(r.byte8910, 5259587);
  assert.strictEqual(r.byte11To14, 1261262125);
  assert.strictEqual(r.byte15To19, 293220057087);
  assert.strictEqual(r.byte20To27, 18446744073709551615);
  assert.strictEqual(r.testIfB1, 123);
});
