// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');

testHelper('InstanceIoUser', 'src/instance_io.bin', function(r, InstanceIoUser_) {
  assert.strictEqual(r.qtyEntries, 3);
  assert.strictEqual(r.entries[0].name, "the");
  assert.strictEqual(r.entries[1].name, "rainy");
  assert.strictEqual(r.entries[2].name, "day it is");
});
