// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');

testHelper('BcdUserTypeBe', 'src/bcd_user_type_be.bin', function(r, BcdUserTypeBe_) {
  assert.strictEqual(r.ltr.asInt, 12345678);
  assert.strictEqual(r.ltr.asStr, "12345678");
  assert.strictEqual(r.rtl.asInt, 87654321);
  assert.strictEqual(r.rtl.asStr, "87654321");
  assert.strictEqual(r.leadingZeroLtr.asInt, 123456);
  assert.strictEqual(r.leadingZeroLtr.asStr, "00123456");
});
