// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');

testHelper('ExprIfIntOps', 'src/process_coerce_switch.bin', function(r, ExprIfIntOps) {

  assert.strictEqual(r.isEqPrim, true);
  assert.strictEqual(r.isEqBoxed, true);
});
