// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');

testHelper('ProcessXorConst', 'src/process_xor_1.bin', function(r, ProcessXorConst_) {
  assert.strictEqual(r.key, 255);
  assert.deepStrictEqual(r.buf, new Uint8Array([102, 111, 111, 32, 98, 97, 114]));
});
