// Autogenerated from KST: please remove this line if doing any edits by hand!

extern crate kaitai_struct;
extern crate rust;

use kaitai_struct::KaitaiStruct;
use rust::BitsSignedB64Le;

#[test]
fn test_bits_signed_b64_le() {
    if let Ok(r) = BitsSignedB64Le::from_file("src/bits_signed_b64_le.bin") {

        assert_eq!(r.a_num, 0);
        assert_eq!(r.a_bit, true);
        assert_eq!(r.b_num, 9223372036854775807);
        assert_eq!(r.b_bit, false);
    }
}
