// Autogenerated from KST: please remove this line if doing any edits by hand!

extern crate kaitai_struct;
extern crate rust;

use kaitai_struct::KaitaiStruct;
use rust::ExprSizeofType1;

#[test]
fn test_expr_sizeof_type_1() {
    if let Ok(r) = ExprSizeofType1::from_file("src/fixed_struct.bin") {
        assert_eq!(r.sizeof_block, (((1 + 4) + 2) + 4));
        assert_eq!(r.sizeof_subblock, 4);
    }
}
