# Autogenerated from KST: please remove this line if doing any edits by hand!

load_err = nil
begin
  require 'bits_shift_by_b64_le'
rescue SyntaxError => e
  load_err = e
  BitsShiftByB64Le = nil
rescue LoadError => e
  load_err = e
  BitsShiftByB64Le = nil
end

RSpec.describe BitsShiftByB64Le do
  it 'parses test properly' do
    raise load_err if BitsShiftByB64Le.nil?
    r = BitsShiftByB64Le.from_file('src/bits_shift_by_b64_le.bin')

    expect(r.a).to eq 18446744073709551615
    expect(r.b).to eq 0
  end
end
