# Autogenerated from KST: please remove this line if doing any edits by hand!

load_err = nil
begin
  require 'bits_unaligned_b32_be'
rescue SyntaxError => e
  load_err = e
  BitsUnalignedB32Be = nil
rescue LoadError => e
  load_err = e
  BitsUnalignedB32Be = nil
end

RSpec.describe BitsUnalignedB32Be do
  it 'parses test properly' do
    raise load_err if BitsUnalignedB32Be.nil?
    r = BitsUnalignedB32Be.from_file('src/process_xor_4.bin')

    expect(r.a).to eq true
    expect(r.b).to eq 3648472617
    expect(r.c).to eq 10
  end
end
