# Autogenerated from KST: please remove this line if doing any edits by hand!

RSpec.describe 'BitsUnalignedB64Le' do
  it 'parses test properly' do
    require 'bits_unaligned_b64_le'
    r = BitsUnalignedB64Le.from_file('src/process_xor_4.bin')

    expect(r.a).to eq false
    expect(r.b).to eq 1902324737369038326
    expect(r.c).to eq 71
  end
end
