# Autogenerated from KST: please remove this line if doing any edits by hand!

RSpec.describe 'EnumToIInvalid' do
  it 'parses test properly' do
    require 'enum_to_i_invalid'
    r = EnumToIInvalid.from_file('src/term_strz.bin')

    expect(r.pet_1).to eq :animal_dog
    expect(r.pet_2).to eq 111
    expect(r.pet_2_i).to eq 111
    expect(r.pet_2_i_to_s).to eq "111"
    expect(r.pet_2_mod).to eq 32879
    expect(r.one_lt_two).to eq true
    expect(r.pet_2_eq_int_t).to eq true
    expect(r.pet_2_eq_int_f).to eq false
  end
end
