# Autogenerated from KST: please remove this line if doing any edits by hand!

RSpec.describe 'EnumImportLiterals' do
  it 'parses test properly' do
    require 'enum_import_literals'
    require 'enum_deep'
    r = EnumImportLiterals.from_file('src/enum_0.bin')

    expect(r.pet_1_to_i).to eq 7
    expect(r.pet_1_eq).to eq true
    expect(r.pet_2).to eq :animal_hare
  end
end
