# Autogenerated from KST: please remove this line if doing any edits by hand!

load_err = nil
begin
  require 'enum_deep'
rescue SyntaxError => e
  load_err = e
  EnumDeep = nil
rescue LoadError => e
  load_err = e
  EnumDeep = nil
end

RSpec.describe EnumDeep do
  it 'parses test properly' do
    raise load_err if EnumDeep.nil?
    r = EnumDeep.from_file('src/enum_0.bin')

    expect(r.pet_1).to eq :animal_cat
    expect(r.pet_2).to eq :animal_hare
  end
end
