# Autogenerated from KST: please remove this line if doing any edits by hand!

RSpec.describe 'Expr0' do
  it 'parses test properly' do
    require 'expr_0'
    r = Expr0.from_file('src/str_encodings.bin')

    expect(r.must_be_f7).to eq 247
    expect(r.must_be_abc123).to eq "abc123"
  end
end
