# Autogenerated from KST: please remove this line if doing any edits by hand!

RSpec.describe 'ExprIntDiv' do
  it 'parses test properly' do
    require 'expr_int_div'
    r = ExprIntDiv.from_file('src/fixed_struct.bin')

    expect(r.int_u).to eq 1262698832
    expect(r.int_s).to eq -52947
    expect(r.div_pos_const).to eq 756
    expect(r.div_neg_const).to eq -757
    expect(r.div_pos_seq).to eq 97130679
    expect(r.div_neg_seq).to eq -4073
  end
end
