# Autogenerated from KST: please remove this line if doing any edits by hand!

RSpec.describe 'ImportsAbs' do
  it 'parses test properly' do
    require 'imports_abs'
    r = ImportsAbs.from_file('src/fixed_struct.bin')

    expect(r.len.value).to eq 80
    expect(r.body.size).to eq 80
  end
end
