# Autogenerated from KST: please remove this line if doing any edits by hand!

RSpec.describe 'ImportsParamsDefEnumImported' do
  it 'parses test properly' do
    require 'imports_params_def_enum_imported'
    require 'enum_0'
    require 'enum_deep'
    r = ImportsParamsDefEnumImported.from_file('src/enum_0.bin')

    expect(r.one.pet_1).to eq :animal_cat
    expect(r.one.pet_2).to eq :animal_hare
    expect(r.two.pet_1_param).to eq :animal_cat
    expect(r.two.pet_2_param).to eq :animal_hare
  end
end
