# Autogenerated from KST: please remove this line if doing any edits by hand!

RSpec.describe 'IntegersDoubleOverflow' do
  it 'parses test properly' do
    require 'integers_double_overflow'
    r = IntegersDoubleOverflow.from_file('src/integers_double_overflow.bin')

    expect(r.signed_safe_min_be).to eq -9007199254740991
    expect(r.signed_safe_min_le).to eq -9007199254740991
    expect(r.signed_safe_max_be).to eq 9007199254740991
    expect(r.signed_safe_max_le).to eq 9007199254740991
    expect(r.signed_unsafe_neg_be.to_s(10)).to eq "-9007199254740993"
    expect(r.signed_unsafe_neg_le.to_s(10)).to eq "-9007199254740993"
    expect(r.signed_unsafe_pos_be.to_s(10)).to eq "9007199254740993"
    expect(r.signed_unsafe_pos_be.to_s(10)).to eq "9007199254740993"
  end
end
