# Autogenerated from KST: please remove this line if doing any edits by hand!

RSpec.describe 'NavParentVsValueInst' do
  it 'parses test properly' do
    require 'nav_parent_vs_value_inst'
    r = NavParentVsValueInst.from_file('src/term_strz.bin')

    expect(r.s1).to eq "foo"
  end
end
