# Autogenerated from KST: please remove this line if doing any edits by hand!

RSpec.describe 'NestedTypes' do
  it 'parses test properly' do
    require 'nested_types'
    r = NestedTypes.from_file('src/fixed_struct.bin')

    expect(r.one.typed_at_root.value_b).to eq 80
    expect(r.one.typed_here.value_c).to eq 65
    expect(r.two.value_b).to eq 67
  end
end
