# Autogenerated from KST: please remove this line if doing any edits by hand!

RSpec.describe 'PositionInSeq' do
  it 'parses test properly' do
    require 'position_in_seq'
    r = PositionInSeq.from_file('src/position_in_seq.bin')

    expect(r.numbers).to eq [(0 + 1), 2, 3]
  end
end
