# Autogenerated from KST: please remove this line if doing any edits by hand!

RSpec.describe 'ProcessCoerceSwitch' do
  it 'parses test properly' do
    require 'process_coerce_switch'
    r = ProcessCoerceSwitch.from_file('src/process_coerce_switch.bin')

    expect(r.buf_type).to eq 0
    expect(r.flag).to eq 0
    expect(r.buf.bar).to eq [65, 65, 65, 65].pack('C*')
  end
end
