# Autogenerated from KST: please remove this line if doing any edits by hand!

load_err = nil
begin
  require 'switch_else_only'
rescue SyntaxError => e
  load_err = e
  SwitchElseOnly = nil
rescue LoadError => e
  load_err = e
  SwitchElseOnly = nil
end

RSpec.describe SwitchElseOnly do
  it 'parses test properly' do
    raise load_err if SwitchElseOnly.nil?
    r = SwitchElseOnly.from_file('src/switch_opcodes.bin')

    expect(r.opcode).to eq 83
    expect(r.prim_byte).to eq 102
    expect(r.ut.value).to eq [114, 0, 73, 66].pack('C*')
  end
end
