# Autogenerated from KST: please remove this line if doing any edits by hand!

load_err = nil
begin
  require 'switch_manual_int_size_eos'
rescue SyntaxError => e
  load_err = e
  SwitchManualIntSizeEos = nil
rescue LoadError => e
  load_err = e
  SwitchManualIntSizeEos = nil
end

RSpec.describe SwitchManualIntSizeEos do
  it 'parses test properly' do
    raise load_err if SwitchManualIntSizeEos.nil?
    r = SwitchManualIntSizeEos.from_file('src/switch_tlv.bin')

    expect(r.chunks.length).to eq 4
    expect(r.chunks[0].code).to eq 17
    expect(r.chunks[0].body.body.title).to eq "Stuff"
    expect(r.chunks[0].body.body.author).to eq "Me"
    expect(r.chunks[1].code).to eq 34
    expect(r.chunks[1].body.body.entries).to eq ["AAAA", "BBBB", "CCCC"]
    expect(r.chunks[2].code).to eq 51
    expect(r.chunks[2].body.body).to eq [16, 32, 48, 64, 80, 96, 112, 128].pack('C*')
    expect(r.chunks[3].code).to eq 255
    expect(r.chunks[3].body.body).to eq [].pack('C*')
  end
end
