# Autogenerated from KST: please remove this line if doing any edits by hand!

RSpec.describe 'ValidLong' do
  it 'parses test properly' do
    require 'valid_long'
    r = ValidLong.from_file('src/fixed_struct.bin')

  end
end
