# Autogenerated from KST: please remove this line if doing any edits by hand!

RSpec.describe 'ValidFailMaxInt' do
  it 'parses test properly' do
    require 'valid_fail_max_int'
    expect {
      r = ValidFailMaxInt.from_file('src/fixed_struct.bin')
    }.to raise_error(Kaitai::Struct::ValidationGreaterThanError)
  end
end
