# Autogenerated from KST: please remove this line if doing any edits by hand!

require 'valid_fail_range_float'

RSpec.describe ValidFailRangeFloat do
  it 'parses test properly' do
    expect {
      r = ValidFailRangeFloat.from_file('src/floating_points.bin')
    }.to raise_error(Kaitai::Struct::ValidationGreaterThanError)
  end
end
