# Autogenerated from KST: please remove this line if doing any edits by hand!

RSpec.describe 'ZlibSurrounded' do
  it 'parses test properly' do
    require 'zlib_surrounded'
    r = ZlibSurrounded.from_file('src/zlib_surrounded.bin')

    expect(r.zlib.num).to eq -1
  end
end
