# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest, os, streams, options, sequtils, ../testhelpers
import ../../../compiled/nim/params_call_extra_parens

var
  stream = newFileStream("test_out/nim/junitreports/params_call_extra_parens.xml", fmWrite)
  outputFormatter = newJUnitOutputFormatter(stream)
addOutputFormatter(outputFormatter)

suite "Kaitai Struct Compiler Test Suite":
  test "Nim: ParamsCallExtraParens":
    let r = ParamsCallExtraParens.fromFile("src/term_strz.bin")

    check(r.buf1.body == string("foo|b"))

close(outputFormatter)
