# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest, os, streams, options, sequtils, ../testhelpers
import ../../../compiled/nim/process_repeat_usertype

var
  stream = newFileStream("test_out/nim/junitreports/process_repeat_usertype.xml", fmWrite)
  outputFormatter = newJUnitOutputFormatter(stream)
addOutputFormatter(outputFormatter)

suite "Kaitai Struct Compiler Test Suite":
  test "Nim: ProcessRepeatUsertype":
    let r = ProcessRepeatUsertype.fromFile("src/process_xor_4.bin")

    check(r.blocks[0].a == int32(-1975704206))
    check(r.blocks[0].b == int8(20))
    check(r.blocks[1].a == int32(279597642))
    check(r.blocks[1].b == int8(68))

close(outputFormatter)
