# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest, os, streams, options, sequtils, ../testhelpers
import ../../../compiled/nim/str_combine

var
  stream = newFileStream("test_out/nim/junitreports/str_combine.xml", fmWrite)
  outputFormatter = newJUnitOutputFormatter(stream)
addOutputFormatter(outputFormatter)

suite "Kaitai Struct Compiler Test Suite":
  test "Nim: StrCombine":
    let r = StrCombine.fromFile("src/term_strz.bin")

    check(r.strTerm == string("foo"))
    check(r.strLimit == string("bar|"))
    check(r.strEos == string("baz@"))
    check(r.strCalc == string("bar"))
    check(r.strCalcBytes == string("baz"))
    check(r.termOrLimit == string("foo"))
    check(r.termOrEos == string("baz@"))
    check(r.termOrCalc == string("foo"))
    check(r.termOrCalcBytes == string("baz"))
    check(r.limitOrEos == string("bar|"))
    check(r.limitOrCalc == string("bar"))
    check(r.limitOrCalcBytes == string("bar|"))
    check(r.eosOrCalc == string("bar"))
    check(r.eosOrCalcBytes == string("baz@"))
    check(r.calcOrCalcBytes == string("baz"))

close(outputFormatter)
