// Autogenerated from KST: please remove this line if doing any edits by hand!

using System.Threading.Tasks;
using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecRecursiveOne : CommonSpec
    {
        [Test]
        public async Task TestRecursiveOne()
        {
            var r = RecursiveOne.FromFile(SourceFile("fixed_struct.bin"));
            await r.ReadAsync();

            Assert.AreEqual(r.One, 80);
            Assert.AreEqual(((RecursiveOne) (r.Next)).One, 65);
            Assert.AreEqual(((RecursiveOne) (((RecursiveOne) (r.Next)).Next)).One, 67);
            Assert.AreEqual(((RecursiveOne.Fini) (((RecursiveOne) (((RecursiveOne) (r.Next)).Next)).Next)).Finisher, 11595);
        }
    }
}
