// Autogenerated from KST: please remove this line if doing any edits by hand!

using System.Threading.Tasks;
using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecTsPacketHeader : CommonSpec
    {
        [Test]
        public async Task TestTsPacketHeader()
        {
            var r = TsPacketHeader.FromFile(SourceFile("ts_packet.bin"));
            await r.ReadAsync();

            Assert.AreEqual(r.SyncByte, 71);
            Assert.AreEqual(r.TransportErrorIndicator, false);
            Assert.AreEqual(r.PayloadUnitStartIndicator, false);
            Assert.AreEqual(r.TransportPriority, true);
            Assert.AreEqual(r.Pid, 33);
            Assert.AreEqual(r.TransportScramblingControl, 0);
            Assert.AreEqual(r.AdaptationFieldControl, TsPacketHeader.AdaptationFieldControlEnum.PayloadOnly);
        }
    }
}
