// Autogenerated from KST: please remove this line if doing any edits by hand!

using System.Threading.Tasks;
using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecValidShort : CommonSpec
    {
        [Test]
        public async Task TestValidShort()
        {
            var r = ValidShort.FromFile(SourceFile("fixed_struct.bin"));
            await r.ReadAsync();


        }
    }
}
