// Autogenerated from KST: please remove this line if doing any edits by hand!

using System.Threading.Tasks;
using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecParamsCallShort : CommonSpec
    {
        [Test]
        public async Task TestParamsCallShort()
        {
            var r = ParamsCallShort.FromFile(SourceFile("term_strz.bin"));
            await r.ReadAsync();

            Assert.AreEqual(r.Buf1.Body, "foo|b");
            Assert.AreEqual(r.Buf2.Body, "ar|ba");
            Assert.AreEqual(r.Buf2.Trailer, 122);
        }
    }
}
