// Autogenerated from KST: please remove this line if doing any edits by hand!

using System.Threading.Tasks;
using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecEnumDeepLiterals : CommonSpec
    {
        [Test]
        public async Task TestEnumDeepLiterals()
        {
            var r = EnumDeepLiterals.FromFile(SourceFile("enum_0.bin"));
            await r.ReadAsync();

            Assert.AreEqual(r.IsPet1Ok, true);
            Assert.AreEqual(r.IsPet2Ok, true);
        }
    }
}
