// Autogenerated from KST: please remove this line if doing any edits by hand!

using System.Threading.Tasks;
using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecExprSizeofType1 : CommonSpec
    {
        [Test]
        public async Task TestExprSizeofType1()
        {
            var r = ExprSizeofType1.FromFile(SourceFile("fixed_struct.bin"));
            await r.ReadAsync();

            Assert.AreEqual(r.SizeofBlock, (((1 + 4) + 2) + 4));
            Assert.AreEqual(r.SizeofSubblock, 4);
        }
    }
}
