// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec;

import io.kaitai.struct.testformats.EnumLongRangeS;
import org.testng.annotations.Test;
import static org.testng.Assert.*;
public class TestEnumLongRangeS extends CommonSpec {

    @Test
    public void testEnumLongRangeS() throws Exception {
        EnumLongRangeS r = EnumLongRangeS.fromFile(SRC_DIR + "enum_long_range_s.bin");

        assertEquals(r.f1(), EnumLongRangeS.Constants.Known.LONG_MIN);
        assertEquals(r.f2(), EnumLongRangeS.Constants.Known.INT_BELOW_MIN);
        assertEquals(r.f3(), EnumLongRangeS.Constants.Known.INT_MIN);
        assertEquals(r.f4(), EnumLongRangeS.Constants.Known.ZERO);
        assertEquals(r.f5(), EnumLongRangeS.Constants.Known.INT_MAX);
        assertEquals(r.f6(), EnumLongRangeS.Constants.Known.INT_OVER_MAX);
        assertEquals(r.f7(), EnumLongRangeS.Constants.Known.LONG_MAX);
    }
}
