// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec;

import io.kaitai.struct.testformats.ExprIfIntOps;
import org.testng.annotations.Test;
import static org.testng.Assert.*;
public class TestExprIfIntOps extends CommonSpec {

    @Test
    public void testExprIfIntOps() throws Exception {
        ExprIfIntOps r = ExprIfIntOps.fromFile(SRC_DIR + "enum_negative.bin");

        assertIntEquals(r.negBoxed(), 1);
        assertIntEquals(r.isEqPrim(), true);
        assertIntEquals(r.isEqBoxed(), false);
        assertIntEquals(r.isEqNegBoxed(), true);
        assertIntEquals(r.isLtPrim(), false);
        assertIntEquals(r.isLtBoxed(), true);
        assertIntEquals(r.plusPrim(), -2);
        assertIntEquals(r.plusBoxed(), 0);
        assertIntEquals(r.divPrim(), 1);
        assertIntEquals(r.divBoxed(), -1);
        assertIntEquals(r.modPrim(), 0);
        assertIntEquals(r.modBoxed(), 0);
    }
}
