// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec;

import io.kaitai.struct.testformats.ValidFailRegex;
import org.testng.annotations.Test;
import static org.testng.Assert.*;
import io.kaitai.struct.KaitaiStream;
public class TestValidFailRegex extends CommonSpec {

    @Test(expectedExceptions = KaitaiStream.ValidationRegexMatchError.class)
    public void testValidFailRegex() throws Exception {
        ValidFailRegex r = ValidFailRegex.fromFile(SRC_DIR + "fixed_struct.bin");
    }
}
