// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec;

import io.kaitai.struct.testformats.ValidOptionalId;
import org.testng.annotations.Test;
import static org.testng.Assert.*;
public class TestValidOptionalId extends CommonSpec {
    @Test
    public void testValidOptionalId() throws Exception {
        ValidOptionalId r = ValidOptionalId.fromFile(SRC_DIR + "fixed_struct.bin");

    }
}
