// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec;

import io.kaitai.struct.testformats.RepeatUntilComplex;
import org.testng.annotations.Test;
import static org.testng.Assert.*;
import java.util.ArrayList;
import java.util.Arrays;
public class TestRepeatUntilComplex extends CommonSpec {
    @Test
    public void testRepeatUntilComplex() throws Exception {
        RepeatUntilComplex r = RepeatUntilComplex.fromFile(SRC_DIR + "repeat_until_complex.bin");

        assertIntEquals(r.first().size(), 3);
        assertIntEquals(r.first().get(((int) 0)).count(), 4);
        assertEquals(r.first().get(((int) 0)).values(), new ArrayList<Integer>(Arrays.asList((0 + 1), 2, 3, 4)));
        assertIntEquals(r.first().get(((int) 1)).count(), 2);
        assertEquals(r.first().get(((int) 1)).values(), new ArrayList<Integer>(Arrays.asList((0 + 1), 2)));
        assertIntEquals(r.first().get(((int) 2)).count(), 0);
        assertIntEquals(r.second().size(), 4);
        assertIntEquals(r.second().get(((int) 0)).count(), 6);
        assertEquals(r.second().get(((int) 0)).values(), new ArrayList<Integer>(Arrays.asList((0 + 1), 2, 3, 4, 5, 6)));
        assertIntEquals(r.second().get(((int) 1)).count(), 3);
        assertEquals(r.second().get(((int) 1)).values(), new ArrayList<Integer>(Arrays.asList((0 + 1), 2, 3)));
        assertIntEquals(r.second().get(((int) 2)).count(), 4);
        assertEquals(r.second().get(((int) 2)).values(), new ArrayList<Integer>(Arrays.asList((0 + 1), 2, 3, 4)));
        assertIntEquals(r.second().get(((int) 3)).count(), 0);
        assertEquals(r.third(), new ArrayList<Integer>(Arrays.asList((0 + 102), 111, 111, 98, 97, 114, 0)));
    }
}
