// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec;

import io.kaitai.struct.testformats.EofExceptionBytes;
import org.testng.annotations.Test;
import static org.testng.Assert.*;
import io.kaitai.struct.KaitaiStream;
public class TestEofExceptionBytes extends CommonSpec {

    @Test(expectedExceptions = java.nio.BufferUnderflowException.class)
    public void testEofExceptionBytes() throws Exception {
        EofExceptionBytes r = EofExceptionBytes.fromFile(SRC_DIR + "term_strz.bin");
    }
}
