// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec;

import io.kaitai.struct.testformats.NonStandard;
import org.testng.annotations.Test;
import static org.testng.Assert.*;
public class TestNonStandard extends CommonSpec {
    @Test
    public void testNonStandard() throws Exception {
        NonStandard r = NonStandard.fromFile(SRC_DIR + "fixed_struct.bin");

        assertIntEquals(r.foo(), 80);
    }
}
