// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec;

import io.kaitai.struct.testformats.ParamsCallExtraParens;
import org.testng.annotations.Test;
import static org.testng.Assert.*;
public class TestParamsCallExtraParens extends CommonSpec {
    @Test
    public void testParamsCallExtraParens() throws Exception {
        ParamsCallExtraParens r = ParamsCallExtraParens.fromFile(SRC_DIR + "term_strz.bin");

        assertEquals(r.buf1().body(), "foo|b");
    }
}
