// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec;

import io.kaitai.struct.testformats.TermBytes;
import org.testng.annotations.Test;
import static org.testng.Assert.*;
public class TestTermBytes extends CommonSpec {
    @Test
    public void testTermBytes() throws Exception {
        TermBytes r = TermBytes.fromFile(SRC_DIR + "term_strz.bin");

        assertEquals(r.s1(), new byte[] { 102, 111, 111 });
        assertEquals(r.s2(), new byte[] { 98, 97, 114 });
        assertEquals(r.s3(), new byte[] { 124, 98, 97, 122, 64 });
    }
}
