// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec;

import io.kaitai.struct.testformats.ExprIoTernary;
import org.testng.annotations.Test;
import static org.testng.Assert.*;
public class TestExprIoTernary extends CommonSpec {

    @Test
    public void testExprIoTernary() throws Exception {
        ExprIoTernary r = ExprIoTernary.fromFile(SRC_DIR + "if_struct.bin");

        assertIntEquals(r.oneOrTwoIoSize1(), 8);
        assertIntEquals(r.oneOrTwoIoSize2(), 8);
        assertIntEquals(r.oneOrTwoIoSizeAdd3(), 11);
    }
}
