// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec;

import io.kaitai.struct.testformats.TermStruct4;
import org.testng.annotations.Test;
import static org.testng.Assert.*;
public class TestTermStruct4 extends CommonSpec {
    @Test
    public void testTermStruct4() throws Exception {
        TermStruct4 r = TermStruct4.fromFile(SRC_DIR + "term_strz.bin");

        assertEquals(r.s1().value().value(), new byte[] { 102, 111, 111 });
        assertEquals(r.s2().value().value(), new byte[] { 98, 97, 114 });
        assertEquals(r.s3().value().value(), new byte[] { 98, 97, 122 });
    }
}
