// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec;

import io.kaitai.struct.testformats.ProcessRepeatBytes;
import org.testng.annotations.Test;
import static org.testng.Assert.*;
public class TestProcessRepeatBytes extends CommonSpec {
    @Test
    public void testProcessRepeatBytes() throws Exception {
        ProcessRepeatBytes r = ProcessRepeatBytes.fromFile(SRC_DIR + "process_xor_4.bin");

        assertEquals(r.bufs().get(((int) 0)), new byte[] { 114, 37, 61, -118, 20 });
        assertEquals(r.bufs().get(((int) 1)), new byte[] { 74, 82, -86, 16, 68 });
    }
}
