// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec;

import io.kaitai.struct.testformats.ValidFailContents;
import org.testng.annotations.Test;
import static org.testng.Assert.*;
import io.kaitai.struct.KaitaiStream;
public class TestValidFailContents extends CommonSpec {
    @Test(expectedExceptions = KaitaiStream.ValidationNotEqualError.class)
    public void testValidFailContents() throws Exception {
        ValidFailContents r = ValidFailContents.fromFile(SRC_DIR + "fixed_struct.bin");
    }
}
