// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec;

import io.kaitai.struct.testformats.CastNested;
import org.testng.annotations.Test;
import static org.testng.Assert.*;
public class TestCastNested extends CommonSpec {
    @Test
    public void testCastNested() throws Exception {
        CastNested r = CastNested.fromFile(SRC_DIR + "switch_opcodes.bin");

        assertEquals(r.opcodes0Str().value(), "foobar");
        assertEquals(r.opcodes0StrValue(), "foobar");
        assertIntEquals(r.opcodes1Int().value(), 66);
        assertIntEquals(r.opcodes1IntValue(), 66);
    }
}
