// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec;

import io.kaitai.struct.testformats.ExprIoPosBits;
import org.testng.annotations.Test;
import static org.testng.Assert.*;
public class TestExprIoPosBits extends CommonSpec {
    @Test
    public void testExprIoPosBits() throws Exception {
        ExprIoPosBits r = ExprIoPosBits.fromFile(SRC_DIR + "process_xor_4.bin");

        assertIntEquals(r.foo(), 7);
        assertIntEquals(r.bar(), 12);
        assertIntEquals(r.baz(), true);
        assertIntEquals(r.qux(), 59);
    }
}
