// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec;

import io.kaitai.struct.testformats.InstanceInSized;
import org.testng.annotations.Test;
import static org.testng.Assert.*;
public class TestInstanceInSized extends CommonSpec {
    @Test
    public void testInstanceInSized() throws Exception {
        InstanceInSized r = InstanceInSized.fromFile(SRC_DIR + "process_rotate.bin");

        assertIntEquals(r.cont().seqSized().seqF(), 9);
        assertIntEquals(r.cont().seqSized().instInvoked(), 172);
        assertEquals(r.cont().seqSized().instUnusedBySeq(), new byte[] { -115, -115 });
        assertIntEquals(r.cont().seqInStream().seqF(), 237);
        assertEquals(r.cont().seqInStream().inst(), new byte[] { -70, 123, -109 });
        assertIntEquals(r.cont().instInStream().seqF(), 99);
        assertEquals(r.cont().instInStream().inst(), new byte[] { 35, 1, 42 });
        assertIntEquals(r.cont().instSized().seqF(), 52);
        assertIntEquals(r.cont().instSized().instInvoked(), 178);
        assertEquals(r.cont().instSized().instUnusedBySeq(), new byte[] { 57, -78 });
    }
}
