// Autogenerated from KST: please remove this line if doing any edits by hand!

#include <boost/test/unit_test.hpp>
#include "eof_exception_switch_user.h"
#include <iostream>
#include <fstream>
#include <vector>
#include "kaitai/exceptions.h"

BOOST_AUTO_TEST_CASE(test_eof_exception_switch_user) {
    std::ifstream ifs("src/enum_negative.bin", std::ifstream::binary);
    kaitai::kstream ks(&ifs);
    eof_exception_switch_user_t* r = nullptr;
    BOOST_CHECK_THROW(
        r = new eof_exception_switch_user_t(&ks),
        std::ifstream::failure
    );

    delete r;
}
