// Autogenerated from KST: please remove this line if doing any edits by hand!

#include <boost/test/unit_test.hpp>
#include "repeat_eos_u4.h"
#include <iostream>
#include <fstream>
#include <vector>

BOOST_AUTO_TEST_CASE(test_repeat_eos_u4) {
    std::ifstream ifs("src/repeat_eos_struct.bin", std::ifstream::binary);
    kaitai::kstream ks(&ifs);
    repeat_eos_u4_t* r = new repeat_eos_u4_t(&ks);
    BOOST_CHECK_EQUAL(r->numbers()->size(), 4);
    BOOST_CHECK_EQUAL(r->numbers()->at(0), 0);
    BOOST_CHECK_EQUAL(r->numbers()->at(1), 66);
    BOOST_CHECK_EQUAL(r->numbers()->at(2), 66);
    BOOST_CHECK_EQUAL(r->numbers()->at(3), 2069);

    delete r;
}
