// Autogenerated from KST: please remove this line if doing any edits by hand!

#include <boost/test/unit_test.hpp>
#include "default_endian_expr_exception.h"
#include <iostream>
#include <fstream>
#include <vector>
#include "kaitai/exceptions.h"

BOOST_AUTO_TEST_CASE(test_default_endian_expr_exception) {
    std::ifstream ifs("src/endian_expr.bin", std::ifstream::binary);
    kaitai::kstream ks(&ifs);
    default_endian_expr_exception_t* r = nullptr;
    BOOST_CHECK_THROW(
        r = new default_endian_expr_exception_t(&ks),
        kaitai::undecided_endianness_error
    );

    delete r;
}
