// Autogenerated from KST: please remove this line if doing any edits by hand!

#include <boost/test/unit_test.hpp>
#include "expr_if_int_ops.h"
#include <iostream>
#include <fstream>
#include <vector>

BOOST_AUTO_TEST_CASE(test_expr_if_int_ops) {
    std::ifstream ifs("src/process_coerce_switch.bin", std::ifstream::binary);
    kaitai::kstream ks(&ifs);
    expr_if_int_ops_t* r = new expr_if_int_ops_t(&ks);

    BOOST_CHECK_EQUAL(r->is_eq_prim(), true);
    BOOST_CHECK_EQUAL(r->is_eq_boxed(), true);

    delete r;
}
