// Autogenerated from KST: please remove this line if doing any edits by hand!

#include <boost/test/unit_test.hpp>
#include "imports_params_def_array_usertype_imported.h"
#include <iostream>
#include <fstream>
#include <vector>

BOOST_AUTO_TEST_CASE(test_imports_params_def_array_usertype_imported) {
    std::ifstream ifs("src/process_xor_4.bin", std::ifstream::binary);
    kaitai::kstream ks(&ifs);
    imports_params_def_array_usertype_imported_t* r = new imports_params_def_array_usertype_imported_t(&ks);

    BOOST_CHECK_EQUAL(r->hws()->size(), 2);
    BOOST_CHECK_EQUAL(r->hws()->at(0)->one(), 236);
    BOOST_CHECK_EQUAL(r->hws()->at(1)->one(), 187);
    BOOST_CHECK_EQUAL(r->two()->hw0_one(), 236);
    BOOST_CHECK_EQUAL(r->two()->hw1_one(), 187);

    delete r;
}
