// Autogenerated from KST: please remove this line if doing any edits by hand!

#include <boost/test/unit_test.hpp>
#include "process_xor4_const.h"
#include <iostream>
#include <fstream>
#include <vector>

BOOST_AUTO_TEST_CASE(test_process_xor4_const) {
    std::ifstream ifs("src/process_xor_4.bin", std::ifstream::binary);
    kaitai::kstream ks(&ifs);
    process_xor4_const_t* r = new process_xor4_const_t(&ks);

    BOOST_CHECK_EQUAL(r->key(), std::string("\xEC\xBB\xA3\x14", 4));
    BOOST_CHECK_EQUAL(r->buf(), std::string("\x66\x6F\x6F\x20\x62\x61\x72", 7));

    delete r;
}
