// Autogenerated from KST: please remove this line if doing any edits by hand!

#include <boost/test/unit_test.hpp>
#include "expr_bytes_ops.h"
#include <iostream>
#include <fstream>
#include <vector>

BOOST_AUTO_TEST_CASE(test_expr_bytes_ops) {
    std::ifstream ifs("src/fixed_struct.bin", std::ifstream::binary);
    kaitai::kstream ks(&ifs);
    expr_bytes_ops_t* r = new expr_bytes_ops_t(&ks);

    BOOST_CHECK_EQUAL(r->one_size(), 3);
    BOOST_CHECK_EQUAL(r->one_first(), 80);
    BOOST_CHECK_EQUAL(r->one_mid(), 65);
    BOOST_CHECK_EQUAL(r->one_last(), 67);
    BOOST_CHECK_EQUAL(r->one_min(), 65);
    BOOST_CHECK_EQUAL(r->one_max(), 80);
    BOOST_CHECK_EQUAL(r->two_size(), 3);
    BOOST_CHECK_EQUAL(r->two_first(), 65);
    BOOST_CHECK_EQUAL(r->two_mid(), 67);
    BOOST_CHECK_EQUAL(r->two_last(), 75);
    BOOST_CHECK_EQUAL(r->two_min(), 65);
    BOOST_CHECK_EQUAL(r->two_max(), 75);

    delete r;
}
