# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.bcd_user_type_le import BcdUserTypeLe

class TestBcdUserTypeLe(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestBcdUserTypeLe, self).__init__(*args, **kwargs)
        self.struct_class = BcdUserTypeLe
        self.src_filename = 'src/bcd_user_type_le.bin'
