# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.expr_if_int_ops import ExprIfIntOps

class TestExprIfIntOps(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestExprIfIntOps, self).__init__(*args, **kwargs)
        self.struct_class = ExprIfIntOps
        self.src_filename = 'src/instance_io.bin'
