# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.float_to_i import FloatToI

class TestFloatToI(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestFloatToI, self).__init__(*args, **kwargs)
        self.struct_class = FloatToI
        self.src_filename = 'src/floating_points.bin'
