# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.valid_optional_id import ValidOptionalId

class TestValidOptionalId(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestValidOptionalId, self).__init__(*args, **kwargs)
        self.struct_class = ValidOptionalId
        self.src_filename = 'src/fixed_struct.bin'
