# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.valid_fail_contents import ValidFailContents

class TestValidFailContents(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestValidFailContents, self).__init__(*args, **kwargs)
        self.struct_class = ValidFailContents
        self.src_filename = 'src/fixed_struct.bin'

    def test_read_write_roundtrip(self):
        self.skipTest("cannot use roundtrip because parsing is expected to fail")
