# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.expr_io_pos_bits import ExprIoPosBits

class TestExprIoPosBits(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestExprIoPosBits, self).__init__(*args, **kwargs)
        self.struct_class = ExprIoPosBits
        self.src_filename = 'src/process_xor_4.bin'
