# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.position_in_seq import PositionInSeq

class TestPositionInSeq(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestPositionInSeq, self).__init__(*args, **kwargs)
        self.struct_class = PositionInSeq
        self.src_filename = 'src/position_in_seq.bin'
