# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.process_repeat_usertype_dynarg_xor import ProcessRepeatUsertypeDynargXor

class TestProcessRepeatUsertypeDynargXor(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestProcessRepeatUsertypeDynargXor, self).__init__(*args, **kwargs)
        self.struct_class = ProcessRepeatUsertypeDynargXor
        self.src_filename = 'src/process_xor_4.bin'
