# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.integers_double_overflow import IntegersDoubleOverflow

class TestIntegersDoubleOverflow(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestIntegersDoubleOverflow, self).__init__(*args, **kwargs)
        self.struct_class = IntegersDoubleOverflow
        self.src_filename = 'src/integers_double_overflow.bin'
