# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.process_xor4_value import ProcessXor4Value

class TestProcessXor4Value(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestProcessXor4Value, self).__init__(*args, **kwargs)
        self.struct_class = ProcessXor4Value
        self.src_filename = 'src/process_xor_4.bin'
