# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.enum_deep import EnumDeep

class TestEnumDeep(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestEnumDeep, self).__init__(*args, **kwargs)
        self.struct_class = EnumDeep
        self.src_filename = 'src/enum_0.bin'
