# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest

from bits_enum import BitsEnum

class TestBitsEnum(unittest.TestCase):
    def test_bits_enum(self):
        with BitsEnum.from_file('src/fixed_struct.bin') as r:
            self.assertEqual(r.one, BitsEnum.Animal.platypus)
            self.assertEqual(r.two, BitsEnum.Animal.horse)
            self.assertEqual(r.three, BitsEnum.Animal.cat)
