# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest

from expr_bytes_ops import ExprBytesOps

class TestExprBytesOps(unittest.TestCase):
    def test_expr_bytes_ops(self):
        with ExprBytesOps.from_file('src/fixed_struct.bin') as r:

            self.assertEqual(r.one_size, 3)
            self.assertEqual(r.one_first, 80)
            self.assertEqual(r.one_mid, 65)
            self.assertEqual(r.one_last, 67)
            self.assertEqual(r.one_min, 65)
            self.assertEqual(r.one_max, 80)
            self.assertEqual(r.two_size, 3)
            self.assertEqual(r.two_first, 65)
            self.assertEqual(r.two_mid, 67)
            self.assertEqual(r.two_last, 75)
            self.assertEqual(r.two_min, 65)
            self.assertEqual(r.two_max, 75)
