# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest

from debug_switch_user import DebugSwitchUser

class TestDebugSwitchUser(unittest.TestCase):
    def test_debug_switch_user(self):
        with DebugSwitchUser.from_file('src/nav_parent_switch.bin') as r:

            self.assertEqual(r.code, 1)
            self.assertEqual(r.data.val, -190)
