// Autogenerated from KST: please remove this line if doing any edits by hand!

const _imp_std = @import("std");
const _imp_kaitai_struct = @import("kaitai_struct");
const _imp_bits_byte_aligned_eof_le = @import("../formats/bits_byte_aligned_eof_le.zig");

test "BitsByteAlignedEofLe" {
    const file = try _imp_std.fs.cwd().openFile("../../src/bcd_user_type_be.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = _imp_std.testing.allocator;
    var arena = _imp_std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = _imp_kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try _imp_bits_byte_aligned_eof_le.BitsByteAlignedEofLe.create(&arena, &_io, null, null);
    try _imp_std.testing.expectEqualSlices(u8, &[_]u8{ 18, 52, 86, 120, 18, 52, 86, 120 }, r.prebuf);
    try _imp_std.testing.expectEqual(1446253056, r.bits);
}
