// Autogenerated from KST: please remove this line if doing any edits by hand!

const std = @import("std");
const kaitai_struct = @import("kaitai_struct");
const bits_seq_endian_combo = @import("../formats/bits_seq_endian_combo.zig");

test "BitsSeqEndianCombo" {
    const file = try std.fs.cwd().openFile("../../src/process_xor_4.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try bits_seq_endian_combo.BitsSeqEndianCombo.create(&arena, &_io, null, null);
    try std.testing.expectEqual(59, r.be1);
    try std.testing.expectEqual(187, r.be2);
    try std.testing.expectEqual(163, r.le3);
    try std.testing.expectEqual(20, r.be4);
    try std.testing.expectEqual(10, r.le5);
    try std.testing.expectEqual(36, r.le6);
    try std.testing.expectEqual(26, r.le7);
    try std.testing.expectEqual(true, r.be8);
}
