// Autogenerated from KST: please remove this line if doing any edits by hand!

const std = @import("std");
const kaitai_struct = @import("kaitai_struct");
const buffered_struct = @import("../formats/buffered_struct.zig");

test "BufferedStruct" {
    const file = try std.fs.cwd().openFile("../../src/buffered_struct.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try buffered_struct.BufferedStruct.create(&arena, &_io, null, null);
    try std.testing.expectEqual(16, r.len1);
    try std.testing.expectEqual(66, r.block1.number1);
    try std.testing.expectEqual(67, r.block1.number2);
    try std.testing.expectEqual(8, r.len2);
    try std.testing.expectEqual(68, r.block2.number1);
    try std.testing.expectEqual(69, r.block2.number2);
    try std.testing.expectEqual(238, r.finisher);
}
