// Autogenerated from KST: please remove this line if doing any edits by hand!

const _imp_std = @import("std");
const _imp_kaitai_struct = @import("kaitai_struct");
const _imp_bytes_pad_term_empty = @import("../formats/bytes_pad_term_empty.zig");

test "BytesPadTermEmpty" {
    const file = try _imp_std.fs.cwd().openFile("../../src/str_pad_term_empty.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = _imp_std.testing.allocator;
    var arena = _imp_std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = _imp_kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try _imp_bytes_pad_term_empty.BytesPadTermEmpty.create(&arena, &_io, null, null);
    try _imp_std.testing.expectEqualSlices(u8, &[_]u8{  }, r.str_pad);
    try _imp_std.testing.expectEqualSlices(u8, &[_]u8{  }, r.str_term);
    try _imp_std.testing.expectEqualSlices(u8, &[_]u8{  }, r.str_term_and_pad);
    try _imp_std.testing.expectEqualSlices(u8, &[_]u8{ 64 }, r.str_term_include);
}
