// Autogenerated from KST: please remove this line if doing any edits by hand!

const std = @import("std");
const kaitai_struct = @import("kaitai_struct");
const debug_array_user = @import("../formats/debug_array_user.zig");

test "DebugArrayUser" {
    const file = try std.fs.cwd().openFile("../../src/fixed_struct.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try debug_array_user.DebugArrayUser.create(&arena, &_io, null, null);
    try std.testing.expectEqual(80, r.one_cat.meow);
    try std.testing.expectEqual(3, r.array_of_cats.items.len);
    try std.testing.expectEqual(65, r.array_of_cats.items[0].meow);
    try std.testing.expectEqual(67, r.array_of_cats.items[1].meow);
    try std.testing.expectEqual(75, r.array_of_cats.items[2].meow);
}
