// Autogenerated from KST: please remove this line if doing any edits by hand!

const _imp_std = @import("std");
const _imp_kaitai_struct = @import("kaitai_struct");
const _imp_enum_import_seq = @import("../formats/enum_import_seq.zig");
const _imp_enum_0 = @import("../formats/enum_0.zig");
const _imp_enum_deep = @import("../formats/enum_deep.zig");

test "EnumImportSeq" {
    const file = try _imp_std.fs.cwd().openFile("../../src/enum_0.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = _imp_std.testing.allocator;
    var arena = _imp_std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = _imp_kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try _imp_enum_import_seq.EnumImportSeq.create(&arena, &_io, null, null);
    try _imp_std.testing.expectEqual(_imp_enum_0.Enum0.Animal.cat, r.pet_1);
    try _imp_std.testing.expectEqual(_imp_enum_deep.EnumDeep.Container1.Container2.Animal.hare, r.pet_2);
}
