// Autogenerated from KST: please remove this line if doing any edits by hand!

const std = @import("std");
const kaitai_struct = @import("kaitai_struct");
const eof_exception_bytes = @import("../formats/eof_exception_bytes.zig");

test "EofExceptionBytes" {
    const file = try std.fs.cwd().openFile("../../src/term_strz.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = kaitai_struct.KaitaiStream.fromFileReader(&reader);
    try std.testing.expectError(error.EndOfStream, eof_exception_bytes.EofExceptionBytes.create(&arena, &_io, null, null));
}
