// Autogenerated from KST: please remove this line if doing any edits by hand!

const std = @import("std");
const kaitai_struct = @import("kaitai_struct");
const expr_enum_to_s = @import("../formats/expr_enum_to_s.zig");

test "ExprEnumToS" {
    const file = try std.fs.cwd().openFile("../../src/enum_0.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try expr_enum_to_s.ExprEnumToS.create(&arena, &_io, null, null);
    try std.testing.expectEqualStrings("one=cat", (try r.oneAsString()));
}
