// Autogenerated from KST: please remove this line if doing any edits by hand!

const _imp_std = @import("std");
const _imp_kaitai_struct = @import("kaitai_struct");
const _imp_expr_io_ternary = @import("../formats/expr_io_ternary.zig");

test "ExprIoTernary" {
    const file = try _imp_std.fs.cwd().openFile("../../src/if_struct.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = _imp_std.testing.allocator;
    var arena = _imp_std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = _imp_kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try _imp_expr_io_ternary.ExprIoTernary.create(&arena, &_io, null, null);
    try _imp_std.testing.expectEqual(8, (try r.oneOrTwoIoSize1()));
    try _imp_std.testing.expectEqual(8, (try r.oneOrTwoIoSize2()));
    try _imp_std.testing.expectEqual(11, (try r.oneOrTwoIoSizeAdd3()));
}
