// Autogenerated from KST: please remove this line if doing any edits by hand!

const std = @import("std");
const kaitai_struct = @import("kaitai_struct");
const expr_0 = @import("../formats/expr_0.zig");

test "Expr0" {
    const file = try std.fs.cwd().openFile("../../src/str_encodings.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try expr_0.Expr0.create(&arena, &_io, null, null);
    try std.testing.expectEqual(247, (try r.mustBeF7()));
    try std.testing.expectEqualStrings("abc123", (try r.mustBeAbc123()));
}
