// Autogenerated from KST: please remove this line if doing any edits by hand!

const _imp_std = @import("std");
const _imp_kaitai_struct = @import("kaitai_struct");
const _imp_expr_if_int_eq = @import("../formats/expr_if_int_eq.zig");

test "ExprIfIntEq" {
    const file = try _imp_std.fs.cwd().openFile("../../src/process_coerce_switch.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = _imp_std.testing.allocator;
    var arena = _imp_std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = _imp_kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try _imp_expr_if_int_eq.ExprIfIntEq.create(&arena, &_io, null, null);
    try _imp_std.testing.expectEqual(true, (try r.seqEqLit()));
    try _imp_std.testing.expectEqual(true, (try r.seqEqCalc()));
    try _imp_std.testing.expectEqual(true, (try r.seqEqCalcIf()));
    try _imp_std.testing.expectEqual(true, (try r.seqEqSeqIf()));
    try _imp_std.testing.expectEqual(true, (try r.calcEqLit()));
    try _imp_std.testing.expectEqual(true, (try r.calcEqCalcIf()));
    try _imp_std.testing.expectEqual(true, (try r.calcEqSeqIf()));
    try _imp_std.testing.expectEqual(true, (try r.calcIfEqLit()));
    try _imp_std.testing.expectEqual(true, (try r.calcIfEqSeqIf()));
    try _imp_std.testing.expectEqual(true, (try r.seqIfEqLit()));
}
