// Autogenerated from KST: please remove this line if doing any edits by hand!

const std = @import("std");
const kaitai_struct = @import("kaitai_struct");
const imports_cast_to_imported2 = @import("../formats/imports_cast_to_imported2.zig");

test "ImportsCastToImported2" {
    const file = try std.fs.cwd().openFile("../../src/process_xor_4.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try imports_cast_to_imported2.ImportsCastToImported2.create(&arena, &_io, null, null);
    try std.testing.expectEqual(236, r.hw.one);
    try std.testing.expectEqual(236, (try r.two.hw()).one);
}
