// Autogenerated from KST: please remove this line if doing any edits by hand!

const _imp_std = @import("std");
const _imp_kaitai_struct = @import("kaitai_struct");
const _imp_integers_min_max = @import("../formats/integers_min_max.zig");

test "IntegersMinMax" {
    const file = try _imp_std.fs.cwd().openFile("../../src/integers_min_max.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = _imp_std.testing.allocator;
    var arena = _imp_std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = _imp_kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try _imp_integers_min_max.IntegersMinMax.create(&arena, &_io, null, null);
    try _imp_std.testing.expectEqual(0, r.unsigned_min.u1);
    try _imp_std.testing.expectEqual(0, r.unsigned_min.u2le);
    try _imp_std.testing.expectEqual(0, r.unsigned_min.u4le);
    try _imp_std.testing.expectEqual(0, r.unsigned_min.u8le);
    try _imp_std.testing.expectEqual(0, r.unsigned_min.u2be);
    try _imp_std.testing.expectEqual(0, r.unsigned_min.u4be);
    try _imp_std.testing.expectEqual(0, r.unsigned_min.u8be);
    try _imp_std.testing.expectEqual(255, r.unsigned_max.u1);
    try _imp_std.testing.expectEqual(65535, r.unsigned_max.u2le);
    try _imp_std.testing.expectEqual(4294967295, r.unsigned_max.u4le);
    try _imp_std.testing.expectEqual(18446744073709551615, r.unsigned_max.u8le);
    try _imp_std.testing.expectEqual(65535, r.unsigned_max.u2be);
    try _imp_std.testing.expectEqual(4294967295, r.unsigned_max.u4be);
    try _imp_std.testing.expectEqual(18446744073709551615, r.unsigned_max.u8be);
    try _imp_std.testing.expectEqual(-128, r.signed_min.s1);
    try _imp_std.testing.expectEqual(-32768, r.signed_min.s2le);
    try _imp_std.testing.expectEqual(-2147483648, r.signed_min.s4le);
    try _imp_std.testing.expectEqual(-9223372036854775808, r.signed_min.s8le);
    try _imp_std.testing.expectEqual(-32768, r.signed_min.s2be);
    try _imp_std.testing.expectEqual(-2147483648, r.signed_min.s4be);
    try _imp_std.testing.expectEqual(-9223372036854775808, r.signed_min.s8be);
    try _imp_std.testing.expectEqual(127, r.signed_max.s1);
    try _imp_std.testing.expectEqual(32767, r.signed_max.s2le);
    try _imp_std.testing.expectEqual(2147483647, r.signed_max.s4le);
    try _imp_std.testing.expectEqual(9223372036854775807, r.signed_max.s8le);
    try _imp_std.testing.expectEqual(32767, r.signed_max.s2be);
    try _imp_std.testing.expectEqual(2147483647, r.signed_max.s4be);
    try _imp_std.testing.expectEqual(9223372036854775807, r.signed_max.s8be);
}
