// Autogenerated from KST: please remove this line if doing any edits by hand!

const std = @import("std");
const kaitai_struct = @import("kaitai_struct");
const js_signed_right_shift = @import("../formats/js_signed_right_shift.zig");

test "JsSignedRightShift" {
    const file = try std.fs.cwd().openFile("../../src/fixed_struct.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try js_signed_right_shift.JsSignedRightShift.create(&arena, &_io, null, null);
    try std.testing.expectEqual(1073741824, (try r.shouldBe40000000()));
    try std.testing.expectEqual(10485760, (try r.shouldBeA00000()));
}
