// Autogenerated from KST: please remove this line if doing any edits by hand!

const _imp_std = @import("std");
const _imp_kaitai_struct = @import("kaitai_struct");
const _imp_js_signed_right_shift = @import("../formats/js_signed_right_shift.zig");

test "JsSignedRightShift" {
    const file = try _imp_std.fs.cwd().openFile("../../src/fixed_struct.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = _imp_std.testing.allocator;
    var arena = _imp_std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = _imp_kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try _imp_js_signed_right_shift.JsSignedRightShift.create(&arena, &_io, null, null);
    try _imp_std.testing.expectEqual(1073741824, (try r.shouldBe40000000()));
    try _imp_std.testing.expectEqual(10485760, (try r.shouldBeA00000()));
}
