// Autogenerated from KST: please remove this line if doing any edits by hand!

const _imp_std = @import("std");
const _imp_kaitai_struct = @import("kaitai_struct");
const _imp_nav_parent_recursive = @import("../formats/nav_parent_recursive.zig");

test "NavParentRecursive" {
    const file = try _imp_std.fs.cwd().openFile("../../src/enum_negative.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = _imp_std.testing.allocator;
    var arena = _imp_std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = _imp_kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try _imp_nav_parent_recursive.NavParentRecursive.create(&arena, &_io, null, null);
    try _imp_std.testing.expectEqual(255, r.value);
    try _imp_std.testing.expectEqual(1, r.next.value);
    try _imp_std.testing.expectEqual(255, (try r.next.parentValue()));
    try _imp_std.testing.expectEqual(null, r.next.next);
}
