// Autogenerated from KST: please remove this line if doing any edits by hand!

const _imp_std = @import("std");
const _imp_kaitai_struct = @import("kaitai_struct");
const _imp_nav_parent_switch = @import("../formats/nav_parent_switch.zig");

test "NavParentSwitch" {
    const file = try _imp_std.fs.cwd().openFile("../../src/nav_parent_switch.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = _imp_std.testing.allocator;
    var arena = _imp_std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = _imp_kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try _imp_nav_parent_switch.NavParentSwitch.create(&arena, &_io, null, null);
    try _imp_std.testing.expectEqual(1, r.category);
    try _imp_std.testing.expectEqual(66, @as(*_imp_nav_parent_switch.NavParentSwitch.Element1, r.content).foo);
    try _imp_std.testing.expectEqual(255, @as(*_imp_nav_parent_switch.NavParentSwitch.Element1, r.content).subelement.bar);
}
