// Autogenerated from KST: please remove this line if doing any edits by hand!

const _imp_std = @import("std");
const _imp_kaitai_struct = @import("kaitai_struct");
const _imp_nested_same_name2 = @import("../formats/nested_same_name2.zig");

test "NestedSameName2" {
    const file = try _imp_std.fs.cwd().openFile("../../src/nested_same_name2.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = _imp_std.testing.allocator;
    var arena = _imp_std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = _imp_kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try _imp_nested_same_name2.NestedSameName2.create(&arena, &_io, null, null);
    try _imp_std.testing.expectEqual(66, r.version);
    try _imp_std.testing.expectEqual(2, r.main_data.main_size);
    try _imp_std.testing.expectEqualSlices(u8, &[_]u8{ 17, 17, 17, 17 }, r.main_data.foo.data1);
    try _imp_std.testing.expectEqual(3, r.dummy.dummy_size);
    try _imp_std.testing.expectEqualSlices(u8, &[_]u8{ 34, 34, 34, 34, 34, 34 }, r.dummy.foo.data2);
}
