// Autogenerated from KST: please remove this line if doing any edits by hand!

const _imp_std = @import("std");
const _imp_kaitai_struct = @import("kaitai_struct");
const _imp_nested_same_name = @import("../formats/nested_same_name.zig");

test "NestedSameName" {
    const file = try _imp_std.fs.cwd().openFile("../../src/repeat_n_struct.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = _imp_std.testing.allocator;
    var arena = _imp_std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = _imp_kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try _imp_nested_same_name.NestedSameName.create(&arena, &_io, null, null);
    try _imp_std.testing.expectEqual(2, r.main_data.main_size);
    try _imp_std.testing.expectEqualSlices(u8, &[_]u8{ 16, 0, 0, 0 }, r.main_data.foo.data);
}
