// Autogenerated from KST: please remove this line if doing any edits by hand!

const std = @import("std");
const kaitai_struct = @import("kaitai_struct");
const params_enum = @import("../formats/params_enum.zig");

test "ParamsEnum" {
    const file = try std.fs.cwd().openFile("../../src/enum_0.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try params_enum.ParamsEnum.create(&arena, &_io, null, null);
    try std.testing.expectEqual(params_enum.ParamsEnum.Animal.cat, r.one);
    try std.testing.expectEqual(true, (try r.invoke_with_param.isCat()));
}
