// Autogenerated from KST: please remove this line if doing any edits by hand!

const _imp_std = @import("std");
const _imp_kaitai_struct = @import("kaitai_struct");
const _imp_params_pass_bool = @import("../formats/params_pass_bool.zig");

test "ParamsPassBool" {
    const file = try _imp_std.fs.cwd().openFile("../../src/term_strz.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = _imp_std.testing.allocator;
    var arena = _imp_std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = _imp_kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try _imp_params_pass_bool.ParamsPassBool.create(&arena, &_io, null, null);
    try _imp_std.testing.expectEqual(false, r.s_false);
    try _imp_std.testing.expectEqual(true, r.s_true);
    try _imp_std.testing.expectEqual(true, r.seq_b1.arg);
    try _imp_std.testing.expectEqual(1, r.seq_b1.foo.len);
    try _imp_std.testing.expectEqual(false, r.seq_bool.arg);
    try _imp_std.testing.expectEqual(2, r.seq_bool.foo.len);
    try _imp_std.testing.expectEqual(false, r.literal_b1.arg);
    try _imp_std.testing.expectEqual(2, r.literal_b1.foo.len);
    try _imp_std.testing.expectEqual(true, r.literal_bool.arg);
    try _imp_std.testing.expectEqual(1, r.literal_bool.foo.len);
    try _imp_std.testing.expectEqual(true, r.inst_b1.arg);
    try _imp_std.testing.expectEqual(1, r.inst_b1.foo.len);
    try _imp_std.testing.expectEqual(false, r.inst_bool.arg);
    try _imp_std.testing.expectEqual(2, r.inst_bool.foo.len);
}
