// Autogenerated from KST: please remove this line if doing any edits by hand!

const _imp_std = @import("std");
const _imp_kaitai_struct = @import("kaitai_struct");
const _imp_params_call = @import("../formats/params_call.zig");

test "ParamsCall" {
    const file = try _imp_std.fs.cwd().openFile("../../src/term_strz.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = _imp_std.testing.allocator;
    var arena = _imp_std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = _imp_kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try _imp_params_call.ParamsCall.create(&arena, &_io, null, null);
    try _imp_std.testing.expectEqualStrings("foo|b", r.buf1.body);
    try _imp_std.testing.expectEqualStrings("ar|ba", r.buf2.body);
    try _imp_std.testing.expectEqual(122, r.buf2.trailer);
}
