// Autogenerated from KST: please remove this line if doing any edits by hand!

const std = @import("std");
const kaitai_struct = @import("kaitai_struct");
const process_repeat_bytes = @import("../formats/process_repeat_bytes.zig");

test "ProcessRepeatBytes" {
    const file = try std.fs.cwd().openFile("../../src/process_xor_4.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try process_repeat_bytes.ProcessRepeatBytes.create(&arena, &_io, null, null);
    try std.testing.expectEqualSlices(u8, &[_]u8{ 114, 37, 61, 138, 20 }, r.bufs.items[0]);
    try std.testing.expectEqualSlices(u8, &[_]u8{ 74, 82, 170, 16, 68 }, r.bufs.items[1]);
}
