// Autogenerated from KST: please remove this line if doing any edits by hand!

const _imp_std = @import("std");
const _imp_kaitai_struct = @import("kaitai_struct");
const _imp_process_custom_no_args = @import("../formats/process_custom_no_args.zig");

test "ProcessCustomNoArgs" {
    const file = try _imp_std.fs.cwd().openFile("../../src/process_rotate.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = _imp_std.testing.allocator;
    var arena = _imp_std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = _imp_kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try _imp_process_custom_no_args.ProcessCustomNoArgs.create(&arena, &_io, null, null);
    try _imp_std.testing.expectEqualSlices(u8, &[_]u8{ 95, 9, 172, 141, 141, 237, 95 }, r.buf);
}
