// Autogenerated from KST: please remove this line if doing any edits by hand!

const _imp_std = @import("std");
const _imp_kaitai_struct = @import("kaitai_struct");
const _imp_process_repeat_usertype = @import("../formats/process_repeat_usertype.zig");

test "ProcessRepeatUsertype" {
    const file = try _imp_std.fs.cwd().openFile("../../src/process_xor_4.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = _imp_std.testing.allocator;
    var arena = _imp_std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = _imp_kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try _imp_process_repeat_usertype.ProcessRepeatUsertype.create(&arena, &_io, null, null);
    try _imp_std.testing.expectEqual(-1975704206, r.blocks.items[0].a);
    try _imp_std.testing.expectEqual(20, r.blocks.items[0].b);
    try _imp_std.testing.expectEqual(279597642, r.blocks.items[1].a);
    try _imp_std.testing.expectEqual(68, r.blocks.items[1].b);
}
