// Autogenerated from KST: please remove this line if doing any edits by hand!

const _imp_std = @import("std");
const _imp_kaitai_struct = @import("kaitai_struct");
const _imp_repeat_n_struct = @import("../formats/repeat_n_struct.zig");

test "RepeatNStruct" {
    const file = try _imp_std.fs.cwd().openFile("../../src/repeat_n_struct.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = _imp_std.testing.allocator;
    var arena = _imp_std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = _imp_kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try _imp_repeat_n_struct.RepeatNStruct.create(&arena, &_io, null, null);
    try _imp_std.testing.expectEqual(2, r.chunks.items.len);
    try _imp_std.testing.expectEqual(16, r.chunks.items[0].offset);
    try _imp_std.testing.expectEqual(8312, r.chunks.items[0].len);
    try _imp_std.testing.expectEqual(8328, r.chunks.items[1].offset);
    try _imp_std.testing.expectEqual(15, r.chunks.items[1].len);
}
