// Autogenerated from KST: please remove this line if doing any edits by hand!

const std = @import("std");
const kaitai_struct = @import("kaitai_struct");
const str_eos_pad_term_equal = @import("../formats/str_eos_pad_term_equal.zig");

test "StrEosPadTermEqual" {
    const file = try std.fs.cwd().openFile("../../src/str_pad_term.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try str_eos_pad_term_equal.StrEosPadTermEqual.create(&arena, &_io, null, null);
    try std.testing.expectEqualStrings("str1", r.s1.value);
    try std.testing.expectEqualStrings("str2foo@", r.s2.value);
    try std.testing.expectEqualStrings("str", r.s3.value);
    try std.testing.expectEqualStrings("str4baz@.", r.s4.value);
}
