// Autogenerated from KST: please remove this line if doing any edits by hand!

const std = @import("std");
const kaitai_struct = @import("kaitai_struct");
const str_pad_term_zero_size = @import("../formats/str_pad_term_zero_size.zig");

test "StrPadTermZeroSize" {
    const file = try std.fs.cwd().openFile("../../src/enum_negative.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try str_pad_term_zero_size.StrPadTermZeroSize.create(&arena, &_io, null, null);
    try std.testing.expectEqualStrings("", r.str_pad);
    try std.testing.expectEqualStrings("", r.str_term);
    try std.testing.expectEqualStrings("", r.str_term_and_pad);
    try std.testing.expectEqualStrings("", r.str_term_include);
}
