// Autogenerated from KST: please remove this line if doing any edits by hand!

const std = @import("std");
const kaitai_struct = @import("kaitai_struct");
const term_strz_utf16_v2 = @import("../formats/term_strz_utf16_v2.zig");

test "TermStrzUtf16V2" {
    const file = try std.fs.cwd().openFile("../../src/term_strz_utf16.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try term_strz_utf16_v2.TermStrzUtf16V2.create(&arena, &_io, null, null);
    try std.testing.expectEqualStrings("a\u{0200}b", r.s1);
    try std.testing.expectEqualStrings("c\u{0200}d\u{0000}", r.s2);
    try std.testing.expectEqualStrings("e\u{0200}f", r.s3);
}
