// Autogenerated from KST: please remove this line if doing any edits by hand!

const std = @import("std");
const kaitai_struct = @import("kaitai_struct");
const valid_fail_eq_str = @import("../formats/valid_fail_eq_str.zig");

test "ValidFailEqStr" {
    const file = try std.fs.cwd().openFile("../../src/fixed_struct.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = kaitai_struct.KaitaiStream.fromFileReader(&reader);
    try std.testing.expectError(error.ValidationNotEqualError, valid_fail_eq_str.ValidFailEqStr.create(&arena, &_io, null, null));
}
