// Autogenerated from KST: please remove this line if doing any edits by hand!

const std = @import("std");
const kaitai_struct = @import("kaitai_struct");
const valid_eq_str_encodings = @import("../formats/valid_eq_str_encodings.zig");

test "ValidEqStrEncodings" {
    const file = try std.fs.cwd().openFile("../../src/str_encodings.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try valid_eq_str_encodings.ValidEqStrEncodings.create(&arena, &_io, null, null);
    _ = r;
}
