// Autogenerated from KST: please remove this line if doing any edits by hand!

const _imp_std = @import("std");
const _imp_kaitai_struct = @import("kaitai_struct");
const _imp_valid_eq_str_encodings = @import("../formats/valid_eq_str_encodings.zig");

test "ValidEqStrEncodings" {
    const file = try _imp_std.fs.cwd().openFile("../../src/str_encodings.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = _imp_std.testing.allocator;
    var arena = _imp_std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = _imp_kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try _imp_valid_eq_str_encodings.ValidEqStrEncodings.create(&arena, &_io, null, null);
    _ = r;
}
