// Autogenerated from KST: please remove this line if doing any edits by hand!

const _imp_std = @import("std");
const _imp_kaitai_struct = @import("kaitai_struct");
const _imp_zlib_with_header_78 = @import("../formats/zlib_with_header_78.zig");

test "ZlibWithHeader78" {
    const file = try _imp_std.fs.cwd().openFile("../../src/zlib_with_header_78.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = _imp_std.testing.allocator;
    var arena = _imp_std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = _imp_kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try _imp_zlib_with_header_78.ZlibWithHeader78.create(&arena, &_io, null, null);
    try _imp_std.testing.expectEqualSlices(u8, &[_]u8{ 97, 32, 113, 117, 105, 99, 107, 32, 98, 114, 111, 119, 110, 32, 102, 111, 120, 32, 106, 117, 109, 112, 115, 32, 111, 118, 101, 114 }, r.data);
}
