// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"runtime/debug"
	"os"
	"testing"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	. "test_formats"
	"github.com/stretchr/testify/assert"
)

func TestInstanceIoUser(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			debug.PrintStack()
			t.Fatal("unexpected panic:", r)
		}
	}()
	f, err := os.Open("../../src/instance_io.bin")
	if err != nil {
		t.Fatal(err)
	}
	s := kaitai.NewStream(f)
	var r InstanceIoUser
	err = r.Read(s, &r, &r)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 3, r.QtyEntries)
	tmp1, err := r.Entries[0].Name()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, "the", tmp1)
	tmp2, err := r.Entries[1].Name()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, "rainy", tmp2)
	tmp3, err := r.Entries[2].Name()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, "day it is", tmp3)
}
