# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils, unittest
import ../../../compiled/nim/bits_seq_endian_combo
import ../test_utils

let r = BitsSeqEndianCombo.fromFile("src/process_xor_4.bin")

test "BitsSeqEndianCombo":

  check(r.be1 == uint64(59))
  check(r.be2 == uint64(187))
  check(r.le3 == uint64(163))
  check(r.be4 == uint64(20))
  check(r.le5 == uint64(10))
  check(r.le6 == uint64(36))
  check(r.le7 == uint64(26))
  check(r.be8 == bool(true))
  discard
