# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils, unittest
import ../../../compiled/nim/default_endian_expr_is_le
import ../test_utils

let r = DefaultEndianExprIsLe.fromFile("src/endian_expr.bin")

test "DefaultEndianExprIsLe":

  check(r.docs[0].indicator == @[73'u8, 73'u8])
  check(r.docs[0].main.someInt == uint32(66))
  check(r.docs[0].main.someIntBe == uint16(66))
  check(r.docs[0].main.someIntLe == uint16(66))
  check(r.docs[1].indicator == @[77'u8, 77'u8])
  check(r.docs[1].main.someInt == uint32(66))
  check(r.docs[1].main.someIntBe == uint16(66))
  check(r.docs[1].main.someIntLe == uint16(66))
  check(r.docs[2].indicator == @[88'u8, 88'u8])
  check(r.docs[2].main.someInt == uint32(66))
  check(r.docs[2].main.someIntBe == uint16(66))
  check(r.docs[2].main.someIntLe == uint16(66))
  discard
