# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils, unittest
import ../../../compiled/nim/enum_of_value_inst
import ../test_utils

let r = EnumOfValueInst.fromFile("src/enum_0.bin")

test "EnumOfValueInst":

  check(r.pet1 == enum_of_value_inst.cat)
  check(r.pet2 == enum_of_value_inst.chicken)
  check(r.pet3 == enum_of_value_inst.dog)
  check(r.pet4 == enum_of_value_inst.dog)
  discard
