# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../../compiled/nim/enum_of_value_inst

let r = EnumOfValueInst.fromFile("src/enum_0.bin")

doAssert(r.pet1 == Animal())
doAssert(r.pet2 == Animal())
doAssert(r.pet3 == Animal())
doAssert(r.pet4 == Animal())
