# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils, unittest
import ../../../compiled/nim/enum_int_range_s
import ../test_utils

let r = EnumIntRangeS.fromFile("src/enum_int_range_s.bin")

test "EnumIntRangeS":

  check(r.f1 == EnumIntRangeS_Constants.int_min)
  check(r.f2 == EnumIntRangeS_Constants.zero)
  check(r.f3 == EnumIntRangeS_Constants.int_max)
  discard
