# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils, unittest
import ../../../compiled/nim/enum_negative
import ../test_utils

let r = EnumNegative.fromFile("src/enum_negative.bin")

test "EnumNegative":

  check(r.f1 == enum_negative.negative_one)
  check(r.f2 == enum_negative.positive_one)
  discard
