# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../../compiled/nim/expr_bytes_ops

let r = ExprBytesOps.fromFile("src/fixed_struct.bin")

doAssert(r.oneSize == int(3))
doAssert(r.oneFirst == uint8(80))
doAssert(r.oneMid == uint8(65))
doAssert(r.oneLast == uint8(67))
doAssert(r.oneMin == uint8(65))
doAssert(r.oneMax == uint8(80))
doAssert(r.twoSize == int(3))
doAssert(r.twoFirst == uint8(65))
doAssert(r.twoMid == uint8(67))
doAssert(r.twoLast == uint8(75))
doAssert(r.twoMin == uint8(65))
doAssert(r.twoMax == uint8(75))
