# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../../compiled/nim/expr_calc_array_ops
import ../test_utils

let r = ExprCalcArrayOps.fromFile("src/fixed_struct.bin")

doAssert(r.intArraySize == int(7))
doAssert(r.intArrayFirst == int(10))
doAssert(r.intArrayMid == int(25))
doAssert(r.intArrayLast == int(1000))
doAssert(r.intArrayMin == int(10))
doAssert(r.intArrayMax == int(1000))
doAssert(r.doubleArraySize == int(5))
doAssert(r.doubleArrayFirst == float64(10.0))
doAssert(r.doubleArrayMid == float64(25.0))
doAssert(r.doubleArrayLast == float64(3.14159))
doAssert(r.doubleArrayMin == float64(3.14159))
doAssert(r.doubleArrayMax == float64(100.0))
doAssert(r.strArraySize == int(4))
doAssert(r.strArrayFirst == string("un"))
doAssert(r.strArrayMid == string("deux"))
doAssert(r.strArrayLast == string("quatre"))
doAssert(r.strArrayMin == string("deux"))
doAssert(r.strArrayMax == string("un"))
