# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest, os, streams, options, ../testhelpers
import ../../../compiled/nim/expr_2

var
  stream = newFileStream("test_out/nim/junitreports/expr_2.xml", fmWrite)
  outputFormatter = newJUnitOutputFormatter(stream)
addOutputFormatter(outputFormatter)

suite "Kaitai Struct Compiler Test Suite":
  test "Nim: Expr2":
    let r = Expr2.fromFile("src/str_encodings.bin")

    check(r.str1.lenOrig == uint16(10))
    check(r.str1.lenMod == int(7))
    check(r.str1.str == string("Some AS"))
    check(r.str1Len == int(7))
    check(r.str1LenMod == int(7))
    check(r.str1Byte1 == uint8(73))
    check(r.str1Avg == int(73))
    check(r.str1Char5 == string("e"))
    check(r.str1Tuple5.byte0 == uint8(101))
    check(r.str1Tuple5.byte0 == uint8(101))
    check(r.str1Tuple5.byte1 == uint8(32))
    check(r.str1Tuple5.byte2 == uint8(65))
    check(r.str1Tuple5.avg == int(48))
    check(r.str2Tuple5.byte0 == uint8(101))
    check(r.str2Tuple5.byte1 == uint8(32))
    check(r.str2Tuple5.byte2 == uint8(65))
    check(r.str2Tuple5.avg == int(48))

close(outputFormatter)
