# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest, os, streams, options, sequtils, ../testhelpers
import ../../../compiled/nim/expr_mod

var
  stream = newFileStream("test_out/nim/junitreports/expr_mod.xml", fmWrite)
  outputFormatter = newJUnitOutputFormatter(stream)
addOutputFormatter(outputFormatter)

suite "Kaitai Struct Compiler Test Suite":
  test "Nim: ExprMod":
    let r = ExprMod.fromFile("src/fixed_struct.bin")

    check(r.intU == uint32(1262698832))
    check(r.intS == int32(-52947))
    check(r.modPosConst == int(9))
    check(r.modNegConst == int(4))
    check(r.modPosSeq == int(5))
    check(r.modNegSeq == int(2))

close(outputFormatter)
