# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils, unittest
import ../../../compiled/nim/expr_3
import ../test_utils

let r = Expr3.fromFile("src/fixed_struct.bin")

test "Expr3":

  check(r.one == uint8(80))
  check(r.two == string("ACK"))
  check(r.three == string("@ACK"))
  check(r.four == string("_ACK_"))
  check(r.isStrEq == bool(true))
  check(r.isStrNe == bool(false))
  check(r.isStrLt == bool(true))
  check(r.isStrGt == bool(false))
  check(r.isStrLe == bool(true))
  check(r.isStrGe == bool(false))
  check(r.isStrLt2 == bool(true))
  check(r.testNot == bool(true))
  discard
