# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest, os, streams, options, ../testhelpers
import ../../../compiled/nim/expr_3

var
  stream = newFileStream("test_out/nim/junitreports/expr_3.xml", fmWrite)
  outputFormatter = newJUnitOutputFormatter(stream)
addOutputFormatter(outputFormatter)

suite "Kaitai Struct Compiler Test Suite":
  test "Nim: Expr3":
    let r = Expr3.fromFile("src/fixed_struct.bin")

    check(r.one == 80)
    check(r.two == "ACK")
    check(r.three == "@ACK")
    check(r.four == "_ACK_")
    check(r.isStrEq == true)
    check(r.isStrNe == false)
    check(r.isStrLt == true)
    check(r.isStrGt == false)
    check(r.isStrLe == true)
    check(r.isStrGe == false)
    check(r.isStrLt2 == true)
    check(r.testNot == true)

close(outputFormatter)
