# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest, os, streams, options, ../testhelpers
import ../../../compiled/nim/fixed_contents

var
  stream = newFileStream("test_out/nim/junitreports/fixed_contents.xml", fmWrite)
  outputFormatter = newJUnitOutputFormatter(stream)
addOutputFormatter(outputFormatter)

suite "Kaitai Struct Compiler Test Suite":
  test "Nim: FixedContents":
    let r = FixedContents.fromFile("src/fixed_struct.bin")


close(outputFormatter)
