# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest, os, streams, options, ../testhelpers
import ../../../compiled/nim/floating_points

var
  stream = newFileStream("test_out/nim/junitreports/floating_points.xml", fmWrite)
  outputFormatter = newJUnitOutputFormatter(stream)
addOutputFormatter(outputFormatter)

suite "Kaitai Struct Compiler Test Suite":
  test "Nim: FloatingPoints":
    let r = FloatingPoints.fromFile("src/floating_points.bin")

    check(r.singleValue == float32(0.5))
    check(r.singleValueBe == float32(0.5))
    check(r.doubleValue == float64(0.25))
    check(r.doubleValueBe == float64(0.25))
    check(r.approximateValue == float32(1.2345))
    check(r.singleValuePlusInt == float64(1.5))
    check(r.singleValuePlusFloat == float64(1.0))
    check(r.doubleValuePlusFloat == float64(0.3))

close(outputFormatter)
