# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../../compiled/nim/if_instances
import ../test_utils

let r = IfInstances.fromFile("src/fixed_struct.bin")

doAssert(r.neverHappens == none(typeof(r.neverHappens)))
