# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils, unittest
import ../../../compiled/nim/instance_std_array
import ../test_utils

let r = InstanceStdArray.fromFile("src/instance_std_array.bin")

test "InstanceStdArray":

  check(r.ofs == uint32(16))
  check(r.qtyEntries == uint32(3))
  check(r.entrySize == uint32(4))
  check(len(r.entries) == int(3))
  check(r.entries[0] == @[17'u8, 17'u8, 17'u8, 17'u8])
  check(r.entries[1] == @[34'u8, 34'u8, 34'u8, 34'u8])
  check(r.entries[2] == @[51'u8, 51'u8, 51'u8, 51'u8])
  discard
