# Autogenerated from KST: please remove this line if doing any edits by hand!

let r = InstanceStdArray.fromFile("src" / "instance_std_array.bin")

check(r.ofs == 16)
check(r.qtyEntries == 3)
check(r.entrySize == 4)
check(len(r.entries) == 3)
check(r.entries[0] == @[17, 17, 17, 17])
check(r.entries[1] == @[34, 34, 34, 34])
check(r.entries[2] == @[51, 51, 51, 51])
