# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest, os, streams, options, ../testhelpers
import ../../../compiled/nim/instance_user_array

var
  stream = newFileStream("test_out/nim/junitreports/instance_user_array.xml", fmWrite)
  outputFormatter = newJUnitOutputFormatter(stream)
addOutputFormatter(outputFormatter)

suite "Kaitai Struct Compiler Test Suite":
  test "Nim: InstanceUserArray":
    let r = InstanceUserArray.fromFile("src/instance_std_array.bin")

    check(r.ofs == uint32(16))
    check(r.qtyEntries == uint32(3))
    check(r.entrySize == uint32(4))
    check(len(r.userEntries) == int(3))
    check(r.userEntries[0].word1 == uint16(4369))
    check(r.userEntries[0].word2 == uint16(4369))
    check(r.userEntries[1].word1 == uint16(8738))
    check(r.userEntries[1].word2 == uint16(8738))
    check(r.userEntries[2].word1 == uint16(13107))
    check(r.userEntries[2].word2 == uint16(13107))

close(outputFormatter)
