# Autogenerated from KST: please remove this line if doing any edits by hand!

let r = NavParentSwitch.fromFile("src" / "nav_parent_switch.bin")

check(r.category == 1)
check(Element1(r.content).foo == 66)
check(Element1(r.content).subelement.bar == 255)
