# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils, unittest
import ../../../compiled/nim/nav_parent_switch_cast
import ../test_utils

let r = NavParentSwitchCast.fromFile("src/switch_integers.bin")

test "NavParentSwitchCast":

  check(r.main.bufType == uint8(1))
  check(r.main.flag == uint8(7))
  check((NavParentSwitchCast_Foo_One(r.main.buf)).branch.flag == uint8(7))
  discard
