# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest, os, streams, options, ../testhelpers
import ../../../compiled/nim/params_call_short

var
  stream = newFileStream("test_out/nim/junitreports/params_call_short.xml", fmWrite)
  outputFormatter = newJUnitOutputFormatter(stream)
addOutputFormatter(outputFormatter)

suite "Kaitai Struct Compiler Test Suite":
  test "Nim: ParamsCallShort":
    let r = ParamsCallShort.fromFile("src/term_strz.bin")

    check(r.buf1.body == "foo|b")
    check(r.buf2.body == "ar|ba")
    check(r.buf2.trailer == 122)

close(outputFormatter)
