# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils, unittest
import ../../../compiled/nim/params_pass_bool
import ../test_utils

let r = ParamsPassBool.fromFile("src/term_strz.bin")

test "ParamsPassBool":

  check(r.sFalse == bool(false))
  check(r.sTrue == bool(true))
  check(r.seqB1.arg == bool(true))
  check(len(r.seqB1.foo) == int(1))
  check(r.seqBool.arg == bool(false))
  check(len(r.seqBool.foo) == int(2))
  check(r.literalB1.arg == bool(false))
  check(len(r.literalB1.foo) == int(2))
  check(r.literalBool.arg == bool(true))
  check(len(r.literalBool.foo) == int(1))
  check(r.instB1.arg == bool(true))
  check(len(r.instB1.foo) == int(1))
  check(r.instBool.arg == bool(false))
  check(len(r.instBool.foo) == int(2))
  discard
