# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils, unittest
import ../../../compiled/nim/params_pass_array_usertype
import ../test_utils

let r = ParamsPassArrayUsertype.fromFile("src/position_to_end.bin")

test "ParamsPassArrayUsertype":

  check(len(r.passBlocks.bar) == int(2))
  check(r.passBlocks.bar[0].foo == uint8(1))
  check(r.passBlocks.bar[1].foo == uint8(2))
  check(r.passBlocks.one == @[3'u8])
  check(r.passBlocks.two == @[4'u8, 5'u8])
  discard
