# Autogenerated from KST: please remove this line if doing any edits by hand!

let r = ProcessXorValue.fromFile("src" / "process_xor_1.bin")

check(r.key == 255)
check(r.buf == @[102, 111, 111, 32, 98, 97, 114])
