# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../../compiled/nim/process_repeat_usertype
import ../test_utils

let r = ProcessRepeatUsertype.fromFile("src/process_xor_4.bin")

doAssert(r.blocks[0].a == int32(-1975704206))
doAssert(r.blocks[0].b == int8(20))
doAssert(r.blocks[1].a == int32(279597642))
doAssert(r.blocks[1].b == int8(68))
