# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest, os, streams, options, ../testhelpers
import ../../../compiled/nim/process_coerce_switch

var
  stream = newFileStream("test_out/nim/junitreports/process_coerce_switch.xml", fmWrite)
  outputFormatter = newJUnitOutputFormatter(stream)
addOutputFormatter(outputFormatter)

suite "Kaitai Struct Compiler Test Suite":
  test "Nim: ProcessCoerceSwitch":
    let r = ProcessCoerceSwitch.fromFile("src/process_coerce_switch.bin")

    check(r.bufType == uint8(0))
    check(r.flag == uint8(0))
    check(r.buf.bar == seq[byte](@[65, 65, 65, 65]))

close(outputFormatter)
