# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils, unittest
import ../../../compiled/nim/recursive_one
import ../test_utils

let r = RecursiveOne.fromFile("src/fixed_struct.bin")

test "RecursiveOne":

  check(r.one == uint8(80))
  check((RecursiveOne(r.next)).one == uint8(65))
  check((RecursiveOne((RecursiveOne(r.next)).next)).one == uint8(67))
  check((RecursiveOne_Fini((RecursiveOne((RecursiveOne(r.next)).next)).next)).finisher == uint16(11595))
  discard
