# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest, os, streams, options, ../testhelpers
import ../../../compiled/nim/repeat_n_struct

var
  stream = newFileStream("test_out/nim/junitreports/repeat_n_struct.xml", fmWrite)
  outputFormatter = newJUnitOutputFormatter(stream)
addOutputFormatter(outputFormatter)

suite "Kaitai Struct Compiler Test Suite":
  test "Nim: RepeatNStruct":
    let r = RepeatNStruct.fromFile("src/repeat_n_struct.bin")

    check(len(r.chunks) == 2)
    check(r.chunks[0].offset == 16)
    check(r.chunks[0].len == 8312)
    check(r.chunks[1].offset == 8328)
    check(r.chunks[1].len == 15)

close(outputFormatter)
