# Autogenerated from KST: please remove this line if doing any edits by hand!

let r = RepeatNStrzDouble.fromFile("src" / "repeat_n_strz.bin")

check(r.qty == 2)
check(r.lines1 == @["foo"])
check(r.lines2 == @["bar"])
