# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils, unittest
import ../../../compiled/nim/str_pad_term_empty
import ../test_utils

let r = StrPadTermEmpty.fromFile("src/str_pad_term_empty.bin")

test "StrPadTermEmpty":

  check(r.strPad == string(""))
  check(r.strTerm == string(""))
  check(r.strTermAndPad == string(""))
  check(r.strTermInclude == string("@"))
  discard
