# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest, os, streams, options, ../testhelpers
import ../../../compiled/nim/str_pad_term

var
  stream = newFileStream("test_out/nim/junitreports/str_pad_term.xml", fmWrite)
  outputFormatter = newJUnitOutputFormatter(stream)
addOutputFormatter(outputFormatter)

suite "Kaitai Struct Compiler Test Suite":
  test "Nim: StrPadTerm":
    let r = StrPadTerm.fromFile("src/str_pad_term.bin")

    check(r.strPad == "str1")
    check(r.strTerm == "str2foo")
    check(r.strTermAndPad == "str+++3bar+++")
    check(r.strTermInclude == "str4baz@")

close(outputFormatter)
