# Autogenerated from KST: please remove this line if doing any edits by hand!

let r = StrPadTermEmpty.fromFile("src" / "str_pad_term_empty.bin")

check(r.strPad == "")
check(r.strTerm == "")
check(r.strTermAndPad == "")
check(r.strTermInclude == "@")
