# Autogenerated from KST: please remove this line if doing any edits by hand!

let r = StrLiterals2.fromFile("src" / "fixed_struct.bin")

check(r.dollar1 == "$foo")
check(r.dollar2 == "${foo}")
check(r.hash == "#{foo}")
check(r.atSign == "@foo")
