# Autogenerated from KST: please remove this line if doing any edits by hand!

let r = SwitchManualStr.fromFile("src" / "switch_opcodes.bin")

check(len(r.opcodes) == 4)
check(r.opcodes[0].code == "S")
check(Strval(r.opcodes[0].body).value == "foobar")
check(r.opcodes[1].code == "I")
check(Intval(r.opcodes[1].body).value == 66)
check(r.opcodes[2].code == "I")
check(Intval(r.opcodes[2].body).value == 55)
check(r.opcodes[3].code == "S")
check(Strval(r.opcodes[3].body).value == "")
