# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest, os, streams, options, ../testhelpers
import ../../../compiled/nim/switch_manual_str_else

var
  stream = newFileStream("test_out/nim/junitreports/switch_manual_str_else.xml", fmWrite)
  outputFormatter = newJUnitOutputFormatter(stream)
addOutputFormatter(outputFormatter)

suite "Kaitai Struct Compiler Test Suite":
  test "Nim: SwitchManualStrElse":
    let r = SwitchManualStrElse.fromFile("src/switch_opcodes2.bin")

    check(len(r.opcodes) == 4)
    check(r.opcodes[0].code == "S")
    check(r.opcodes[0].body.value == "foo")
    check(r.opcodes[1].code == "X")
    check(r.opcodes[1].body.filler == 66)
    check(r.opcodes[2].code == "Y")
    check(r.opcodes[2].body.filler == 51966)
    check(r.opcodes[3].code == "I")
    check(r.opcodes[3].body.value == 7)

close(outputFormatter)
