# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest, os, streams, options, sequtils, ../testhelpers
import ../../../compiled/nim/term_bytes

var
  stream = newFileStream("test_out/nim/junitreports/term_bytes.xml", fmWrite)
  outputFormatter = newJUnitOutputFormatter(stream)
addOutputFormatter(outputFormatter)

suite "Kaitai Struct Compiler Test Suite":
  test "Nim: TermBytes":
    let r = TermBytes.fromFile("src/term_strz.bin")

    check(r.s1 == seq[byte](@[102, 111, 111].mapIt(toByte(it))))
    check(r.s2 == seq[byte](@[98, 97, 114].mapIt(toByte(it))))
    check(r.s3 == seq[byte](@[124, 98, 97, 122, 64].mapIt(toByte(it))))

close(outputFormatter)
