# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest, os, streams, options, ../testhelpers
import ../../../compiled/nim/type_ternary

var
  stream = newFileStream("test_out/nim/junitreports/type_ternary.xml", fmWrite)
  outputFormatter = newJUnitOutputFormatter(stream)
addOutputFormatter(outputFormatter)

suite "Kaitai Struct Compiler Test Suite":
  test "Nim: TypeTernary":
    let r = TypeTernary.fromFile("src/term_strz.bin")

    check(r.dif.value == uint8(101))

close(outputFormatter)
