# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils, unittest
import ../../../compiled/nim/type_ternary
import ../test_utils

let r = TypeTernary.fromFile("src/term_strz.bin")

test "TypeTernary":

  check(r.dif.value == uint8(101))
  discard
