# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils, unittest
import ../../../compiled/nim/valid_switch
import ../test_utils

let r = ValidSwitch.fromFile("src/fixed_struct.bin")

test "ValidSwitch":

  discard
