<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class CastToTopTest extends TestCase {
    public function testCastToTop() {
        $r = CastToTop::fromFile(self::SRC_DIR_PATH . '/fixed_struct.bin');

        $this->assertEquals(80, $r->code());
        $this->assertEquals(65, $r->header()->code());
        $this->assertEquals(65, $r->headerCasted()->code());
    }
}
