<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class CombineBytesTest extends TestCase {
    public function testCombineBytes() {
        $r = CombineBytes::fromFile(self::SRC_DIR_PATH . '/term_strz.bin');

        $this->assertSame("\x66\x6F\x6F", $r->bytesTerm());
        $this->assertSame("\x62\x61\x72\x7C", $r->bytesLimit());
        $this->assertSame("\x62\x61\x7A\x40", $r->bytesEos());
        $this->assertSame("\x52\x6E\x44", $r->bytesCalc());
        $this->assertSame("\x66\x6F\x6F", $r->termOrLimit());
        $this->assertSame("\x62\x61\x7A\x40", $r->termOrEos());
        $this->assertSame("\x66\x6F\x6F", $r->termOrCalc());
        $this->assertSame("\x62\x61\x72\x7C", $r->limitOrEos());
        $this->assertSame("\x52\x6E\x44", $r->limitOrCalc());
        $this->assertSame("\x62\x61\x7A\x40", $r->eosOrCalc());
    }
}
