<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class DefaultEndianExprIsBeTest extends TestCase {
    public function testDefaultEndianExprIsBe() {
        $r = DefaultEndianExprIsBe::fromFile(self::SRC_DIR_PATH . '/endian_expr.bin');

        $this->assertEquals("\x49\x49", $r->docs()[0]->indicator());
        $this->assertEquals(66, $r->docs()[0]->main()->someInt());
        $this->assertEquals(66, $r->docs()[0]->main()->someIntBe());
        $this->assertEquals(66, $r->docs()[0]->main()->someIntLe());
        $this->assertEquals(66, $r->docs()[0]->main()->instInt());
        $this->assertEquals(66, $r->docs()[0]->main()->instSub()->foo());
        $this->assertEquals("\x4D\x4D", $r->docs()[1]->indicator());
        $this->assertEquals(66, $r->docs()[1]->main()->someInt());
        $this->assertEquals(66, $r->docs()[1]->main()->someIntBe());
        $this->assertEquals(66, $r->docs()[1]->main()->someIntLe());
        $this->assertEquals(1107296256, $r->docs()[1]->main()->instInt());
        $this->assertEquals(1107296256, $r->docs()[1]->main()->instSub()->foo());
        $this->assertEquals("\x58\x58", $r->docs()[2]->indicator());
        $this->assertEquals(1107296256, $r->docs()[2]->main()->someInt());
        $this->assertEquals(66, $r->docs()[2]->main()->someIntBe());
        $this->assertEquals(66, $r->docs()[2]->main()->someIntLe());
        $this->assertEquals(66, $r->docs()[2]->main()->instInt());
        $this->assertEquals(66, $r->docs()[2]->main()->instSub()->foo());
    }
}
