<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class DefaultEndianExprExceptionTest extends TestCase {
    public function testDefaultEndianExprException() {
        $this->expectException(\Kaitai\Struct\Error\UndecidedEndiannessError::class);
        $r = DefaultEndianExprException::fromFile(self::SRC_DIR_PATH . '/endian_expr.bin');
    }
}
