<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class DefaultEndianModTest extends TestCase {
    public function testDefaultEndianMod() {
        $r = DefaultEndianMod::fromFile(self::SRC_DIR_PATH . '/fixed_struct.bin');

        $this->assertSame(1262698832, $r->main()->one());
        $this->assertSame(-52947, $r->main()->nest()->two());
        $this->assertSame(1346454347, $r->main()->nestBe()->two());
    }
}
