<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class EnumLongRangeSTest extends TestCase {
    public function testEnumLongRangeS() {
        $r = EnumLongRangeS::fromFile(self::SRC_DIR_PATH . '/enum_long_range_s.bin');

        $this->assertSame(\Kaitai\Struct\Tests\EnumLongRangeS\Constants::LONG_MIN, $r->f1());
        $this->assertSame(\Kaitai\Struct\Tests\EnumLongRangeS\Constants::INT_BELOW_MIN, $r->f2());
        $this->assertSame(\Kaitai\Struct\Tests\EnumLongRangeS\Constants::INT_MIN, $r->f3());
        $this->assertSame(\Kaitai\Struct\Tests\EnumLongRangeS\Constants::ZERO, $r->f4());
        $this->assertSame(\Kaitai\Struct\Tests\EnumLongRangeS\Constants::INT_MAX, $r->f5());
        $this->assertSame(\Kaitai\Struct\Tests\EnumLongRangeS\Constants::INT_OVER_MAX, $r->f6());
        $this->assertSame(\Kaitai\Struct\Tests\EnumLongRangeS\Constants::LONG_MAX, $r->f7());
    }
}
