<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class EnumDeepLiteralsTest extends TestCase {
    public function testEnumDeepLiterals() {
        $r = EnumDeepLiterals::fromFile(self::SRC_DIR_PATH . '/enum_0.bin');

        $this->assertSame(true, $r->isPet1Ok());
        $this->assertSame(true, $r->isPet2Ok());
    }
}
