<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class ExprCalcArrayOpsTest extends TestCase {
    public function testExprCalcArrayOps() {
        $r = ExprCalcArrayOps::fromFile(self::SRC_DIR_PATH . '/fixed_struct.bin');

        $this->assertSame(7, $r->intArraySize());
        $this->assertSame(10, $r->intArrayFirst());
        $this->assertSame(25, $r->intArrayMid());
        $this->assertSame(1000, $r->intArrayLast());
        $this->assertSame(10, $r->intArrayMin());
        $this->assertSame(1000, $r->intArrayMax());
        $this->assertSame(5, $r->doubleArraySize());
        $this->assertEquals($r->doubleArrayFirst(), 10.0, '', 1e-6);
        $this->assertEquals($r->doubleArrayMid(), 25.0, '', 1e-6);
        $this->assertEquals($r->doubleArrayLast(), 3.14159, '', 1e-6);
        $this->assertEquals($r->doubleArrayMin(), 3.14159, '', 1e-6);
        $this->assertEquals($r->doubleArrayMax(), 100.0, '', 1e-6);
        $this->assertSame(4, $r->strArraySize());
        $this->assertSame("un", $r->strArrayFirst());
        $this->assertSame("deux", $r->strArrayMid());
        $this->assertSame("quatre", $r->strArrayLast());
        $this->assertSame("deux", $r->strArrayMin());
        $this->assertSame("un", $r->strArrayMax());
    }
}
