<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class ExprStrOpsTest extends TestCase {
    public function testExprStrOps() {
        $r = ExprStrOps::fromFile(self::SRC_DIR_PATH . '/term_strz.bin');


        $this->assertEquals("foo|b", $r->one());
        $this->assertEquals(5, $r->oneLen());
        $this->assertEquals("b|oof", $r->oneRev());
        $this->assertEquals("foo", $r->oneSubstr0To3());
        $this->assertEquals("o|b", $r->oneSubstr2To5());
        $this->assertEquals("", $r->oneSubstr3To3());
        $this->assertEquals("0123456789", $r->two());
        $this->assertEquals(10, $r->twoLen());
        $this->assertEquals("9876543210", $r->twoRev());
        $this->assertEquals("0123456", $r->twoSubstr0To7());
        $this->assertEquals("456789", $r->twoSubstr4To10());
        $this->assertEquals("0123456789", $r->twoSubstr0To10());
    }
}
