<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class ExprIfIntOpsTest extends TestCase {
    public function testExprIfIntOps() {
        $r = ExprIfIntOps::fromFile(self::SRC_DIR_PATH . '/instance_io.bin');
        $this->assertSame(3, $r->key());
        $this->assertSame("\xFC\xFC\xFC\xFD\x09\x03\x03\x03", $r->bytes());
        $this->assertSame(253, $r->bytesSubKey());
        $this->assertSame(-3, $r->itemsSubKey());
    }
}
