<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class ExprIfIntOpsTest extends TestCase {
    public function testExprIfIntOps() {
        $r = ExprIfIntOps::fromFile(self::SRC_DIR_PATH . '/process_coerce_switch.bin');

        $this->assertSame(true, $r->isEqPrim());
        $this->assertSame(true, $r->isEqBoxed());
    }
}
