<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class ExprCalcArrayOpsTest extends TestCase {
    public function testExprCalcArrayOps() {
        $r = ExprCalcArrayOps::fromFile(self::SRC_DIR_PATH . '/fixed_struct.bin');


        $this->assertEquals(7, $r->intArraySize());
        $this->assertEquals(10, $r->intArrayFirst());
        $this->assertEquals(25, $r->intArrayMid());
        $this->assertEquals(1000, $r->intArrayLast());
        $this->assertEquals(10, $r->intArrayMin());
        $this->assertEquals(1000, $r->intArrayMax());
        $this->assertEquals(5, $r->doubleArraySize());
        $this->assertEquals($r->doubleArrayFirst(), 10.0, '', 1e-6);
        $this->assertEquals($r->doubleArrayMin(), 25.0, '', 1e-6);
        $this->assertEquals($r->doubleArrayLast(), 3.14159, '', 1e-6);
        $this->assertEquals($r->doubleArrayMin(), 3.14159, '', 1e-6);
        $this->assertEquals($r->doubleArrayMax(), 100.0, '', 1e-6);
        $this->assertEquals(4, $r->strArraySize());
        $this->assertEquals("un", $r->strArrayFirst());
        $this->assertEquals("deux", $r->strArrayMid());
        $this->assertEquals("quatre", $r->strArrayLast());
        $this->assertEquals("deux", $r->strArrayMin());
        $this->assertEquals("quatre", $r->strArrayMax());
    }
}
