<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class ExprBytesOpsTest extends TestCase {
    public function testExprBytesOps() {
        $r = ExprBytesOps::fromFile(self::SRC_DIR_PATH . '/fixed_struct.bin');

        $this->assertSame(3, $r->oneSize());
        $this->assertSame(80, $r->oneFirst());
        $this->assertSame(65, $r->oneMid());
        $this->assertSame(67, $r->oneLast());
        $this->assertSame(65, $r->oneMin());
        $this->assertSame(80, $r->oneMax());
        $this->assertSame(3, $r->twoSize());
        $this->assertSame(65, $r->twoFirst());
        $this->assertSame(67, $r->twoMid());
        $this->assertSame(75, $r->twoLast());
        $this->assertSame(65, $r->twoMin());
        $this->assertSame(75, $r->twoMax());
    }
}
