<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class ImportsParamsDefEnumImportedTest extends TestCase {
    public function testImportsParamsDefEnumImported() {
        $r = ImportsParamsDefEnumImported::fromFile(self::SRC_DIR_PATH . '/enum_0.bin');

        $this->assertSame(\Kaitai\Struct\Tests\Enum0\Animal::CAT, $r->one()->pet1());
        $this->assertSame(\Kaitai\Struct\Tests\EnumDeep\Container1\Container2\Animal::HARE, $r->one()->pet2());
        $this->assertSame(\Kaitai\Struct\Tests\Enum0\Animal::CAT, $r->two()->pet1Param());
        $this->assertSame(\Kaitai\Struct\Tests\EnumDeep\Container1\Container2\Animal::HARE, $r->two()->pet2Param());
    }
}
