<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class InstanceUserArrayTest extends TestCase {
    public function testInstanceUserArray() {
        $r = InstanceUserArray::fromFile(self::SRC_DIR_PATH . '/instance_std_array.bin');

        $this->assertSame(16, $r->ofs());
        $this->assertSame(3, $r->qtyEntries());
        $this->assertSame(4, $r->entrySize());
        $this->assertSame(3, count($r->userEntries()));
        $this->assertSame(4369, $r->userEntries()[0]->word1());
        $this->assertSame(4369, $r->userEntries()[0]->word2());
        $this->assertSame(8738, $r->userEntries()[1]->word1());
        $this->assertSame(8738, $r->userEntries()[1]->word2());
        $this->assertSame(13107, $r->userEntries()[2]->word1());
        $this->assertSame(13107, $r->userEntries()[2]->word2());
    }
}
