<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class MetaXrefTest extends TestCase {
    public function testMetaXref() {
        $r = MetaXref::fromFile(self::SRC_DIR_PATH . '/fixed_struct.bin');

    }
}
