<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class ProcessToUserTest extends TestCase {
    public function testProcessToUser() {
        $r = ProcessToUser::fromFile(self::SRC_DIR_PATH . '/process_rotate.bin');

        $this->assertSame("Hello", $r->buf1()->str());
    }
}
