<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class TsPacketHeaderTest extends TestCase {
    public function testTsPacketHeader() {
        $r = TsPacketHeader::fromFile(self::SRC_DIR_PATH . '/ts_packet.bin');

        $this->assertEquals(71, $r->syncByte());
        $this->assertEquals(false, $r->transportErrorIndicator());
        $this->assertEquals(false, $r->payloadUnitStartIndicator());
        $this->assertEquals(true, $r->transportPriority());
        $this->assertEquals(33, $r->pid());
        $this->assertEquals(0, $r->transportScramblingControl());
        $this->assertEquals(\Kaitai\Struct\Tests\TsPacketHeader\AdaptationFieldControlEnum::PAYLOAD_ONLY, $r->adaptationFieldControl());
    }
}
