<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class ValidFailMinIntTest extends TestCase {
    public function testValidFailMinInt() {
        $this->expectException(\Kaitai\Struct\Error\ValidationLessThanError::class);
        $r = ValidFailMinInt::fromFile(self::SRC_DIR_PATH . '/fixed_struct.bin');
    }
}
