<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class ValidFailRangeIntTest extends TestCase {
    public function testValidFailRangeInt() {
        $this->expectException(\Kaitai\Struct\Error\ValidationGreaterThanError::class);
        $r = ValidFailRangeInt::fromFile(self::SRC_DIR_PATH . '/fixed_struct.bin');
    }
}
