<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class ValidFailAnyofIntTest extends TestCase {
    public function testValidFailAnyofInt() {
        $this->expectException(\Kaitai\Struct\Error\ValidationNotAnyOfError::class);
        $r = ValidFailAnyofInt::fromFile(self::SRC_DIR_PATH . '/fixed_struct.bin');
    }
}
