<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class ValidNotParsedIfTest extends TestCase {
    public function testValidNotParsedIf() {
        $r = ValidNotParsedIf::fromFile(self::SRC_DIR_PATH . '/fixed_struct.bin');

    }
}
