<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class ValidFailRepeatInstTest extends TestCase {
    public function testValidFailRepeatInst() {
        $this->expectException(\Kaitai\Struct\Error\ValidationNotEqualError::class);
        $r = ValidFailRepeatInst::fromFile(self::SRC_DIR_PATH . '/bcd_user_type_be.bin');
    }
}
