<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class ValidFailRepeatMaxIntTest extends TestCase {
    public function testValidFailRepeatMaxInt() {
        $this->expectException(\Kaitai\Struct\Error\ValidationGreaterThanError::class);
        $r = ValidFailRepeatMaxInt::fromFile(self::SRC_DIR_PATH . '/nav_parent_switch.bin');
    }
}
