// Autogenerated from KST: please remove this line if doing any edits by hand!

#include <boost/test/unit_test.hpp>
#include "nested_type_param.h"
#include <iostream>
#include <fstream>
#include <vector>

BOOST_AUTO_TEST_CASE(test_nested_type_param) {
    std::ifstream ifs("src/term_strz.bin", std::ifstream::binary);
    kaitai::kstream ks(&ifs);
    nested_type_param_t* r = new nested_type_param_t(&ks);

    BOOST_CHECK_EQUAL(r->main_seq()->my_len(), 5);
    BOOST_CHECK_EQUAL(r->main_seq()->body(), std::string("foo|b"));

    delete r;
}
