// Autogenerated from KST: please remove this line if doing any edits by hand!

#include <boost/test/unit_test.hpp>
#include "params_call.h"
#include <iostream>
#include <fstream>
#include <vector>

BOOST_AUTO_TEST_CASE(test_params_call) {
    std::ifstream ifs("src/term_strz.bin", std::ifstream::binary);
    kaitai::kstream ks(&ifs);
    params_call_t* r = new params_call_t(&ks);

    BOOST_CHECK_EQUAL(r->buf1()->body(), std::string("foo|b"));
    BOOST_CHECK_EQUAL(r->buf2()->body(), std::string("ar|ba"));
    BOOST_CHECK_EQUAL(r->buf2()->trailer(), 122);

    delete r;
}
