// Autogenerated from KST: please remove this line if doing any edits by hand!

#include <boost/test/unit_test.hpp>
#include "bits_unaligned_b64_le.h"
#include <iostream>
#include <fstream>
#include <vector>

BOOST_AUTO_TEST_CASE(test_bits_unaligned_b64_le) {
    std::ifstream ifs("src/process_xor_4.bin", std::ifstream::binary);
    kaitai::kstream ks(&ifs);
    bits_unaligned_b64_le_t* r = new bits_unaligned_b64_le_t(&ks);

    BOOST_CHECK_EQUAL(r->a(), false);
    BOOST_CHECK_EQUAL(r->b(), 1902324737369038326LL);
    BOOST_CHECK_EQUAL(r->c(), 71);

    delete r;
}
