// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecExpr0 : CommonSpec
    {
        [Test]
        public void TestExpr0()
        {
            var r = Expr0.FromFile(SourceFile("str_encodings.bin"));

            Assert.AreEqual(r.MustBeF7, 247);
            Assert.AreEqual(r.MustBeAbc123, "abc123");
        }
    }
}
