# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest

from expr_str_encodings import _schema

class TestExprStrEncodings(unittest.TestCase):
    def test_expr_str_encodings(self):
        r = _schema.parse_file('src/str_encodings.bin')

        self.assertEqual(r.str1_eq, True)
        self.assertEqual(r.str2_eq, True)
        self.assertEqual(r.str3_eq, True)
        self.assertEqual(r.str3_eq_str2, True)
        self.assertEqual(r.str4_eq, True)
        self.assertEqual(r.str4_gt_str_calc, True)
        self.assertEqual(r.str4_gt_str_from_bytes, True)
