# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest

from repeat_eos_bit import _schema

class TestRepeatEosBit(unittest.TestCase):
    def test_repeat_eos_bit(self):
        r = _schema.parse_file('src/enum_0.bin')
        self.assertEqual(len(r.nibbles), 16)
