# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from bits_seq_endian_combo import _schema

class TestBitsSeqEndianCombo(unittest.TestCase):
    def test_bits_seq_endian_combo(self):
        r = _schema.parse_file('src/process_xor_4.bin')

        self.assertEqual(r.be1, 59)
        self.assertEqual(r.be2, 187)
        self.assertEqual(r.le3, 163)
        self.assertEqual(r.be4, 20)
        self.assertEqual(r.le5, 10)
        self.assertEqual(r.le6, 36)
        self.assertEqual(r.le7, 26)
        self.assertEqual(r.be8, True)
