# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest

from expr_bytes_ops import _schema

class TestExprBytesOps(unittest.TestCase):
    def test_expr_bytes_ops(self):
        r = _schema.parse_file('src/nav_parent_switch.bin')

        self.assertEqual(r.one_size, 3)
        self.assertEqual(r.one_first, 1)
        self.assertEqual(r.one_mid, 66)
        self.assertEqual(r.one_last, 255)
        self.assertEqual(str(r.one_last), u"255")
        self.assertEqual(r.one_min, 1)
        self.assertEqual(r.one_max, 255)
        self.assertEqual(str(r.one_max), u"255")
        self.assertEqual(r.two_size, 3)
        self.assertEqual(r.two_first, 65)
        self.assertEqual(r.two_mid, 255)
        self.assertEqual(str(r.two_mid), u"255")
        self.assertEqual(r.two_last, 75)
        self.assertEqual(r.two_min, 65)
        self.assertEqual(r.two_max, 255)
        self.assertEqual(str(r.two_max), u"255")
