# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest

from position_in_seq import _schema

class TestPositionInSeq(unittest.TestCase):
    def test_position_in_seq(self):
        r = _schema.parse_file('src/position_in_seq.bin')
        self.assertEqual(r.numbers, [(0 + 1), 2, 3])
