# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest

from enum_for_unknown_id import _schema

class TestEnumForUnknownId(unittest.TestCase):
    def test_enum_for_unknown_id(self):
        r = _schema.parse_file('src/fixed_struct.bin')

        self.assertEqual(r.one, 80)
