# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest

from meta_tags import _schema

class TestMetaTags(unittest.TestCase):
    def test_meta_tags(self):
        r = _schema.parse_file('src/fixed_struct.bin')
