# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest

from bits_signed_res_b32_be import _schema

class TestBitsSignedResB32Be(unittest.TestCase):
    def test_bits_signed_res_b32_be(self):
        r = _schema.parse_file('src/bits_shift_by_b32_le.bin')

        self.assertEqual(r.a, 4294967295)
