# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest

from expr_fstring_0 import _schema

class TestExprFstring0(unittest.TestCase):
    def test_expr_fstring_0(self):
        r = _schema.parse_file('src/term_strz.bin')

        self.assertEqual(r.seq_str, u"foo|b")
        self.assertEqual(r.seq_int, 97)
        self.assertEqual(r.empty, u"")
        self.assertEqual(r.literal, u"abc")
        self.assertEqual(r.literal_with_escapes, u"abc\n\tt")
        self.assertEqual(r.head_and_int_literal, u"abc=123")
        self.assertEqual(r.head_and_str_literal, u"abc=foo")
        self.assertEqual(r.head_and_int, u"abc=97")
        self.assertEqual(r.head_and_str, u"abc=foo|b")
