# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest

from cast_to_imported import _schema

class TestCastToImported(unittest.TestCase):
    def test_cast_to_imported(self):
        r = _schema.parse_file('src/fixed_struct.bin')
        self.assertEqual(r.one.one, 80)
        self.assertEqual(r.one_casted.one, 80)
