# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest

from if_struct import _schema

class TestIfStruct(unittest.TestCase):
    def test_if_struct(self):
        r = _schema.parse_file('src/if_struct.bin')
        self.assertEqual(r.op1.opcode, 83)
        self.assertIsNone(r.op1.arg_tuple)
        self.assertEqual(r.op1.arg_str.str, u"foo")
        self.assertEqual(r.op2.opcode, 84)
        self.assertEqual(r.op2.arg_tuple.num1, 66)
        self.assertEqual(r.op2.arg_tuple.num2, 67)
        self.assertIsNone(r.op2.arg_str)
        self.assertEqual(r.op3.opcode, 83)
        self.assertIsNone(r.op3.arg_tuple)
        self.assertEqual(r.op3.arg_str.str, u"bar")
