// Autogenerated from KST: please remove this line if doing any edits by hand!

extern crate kaitai_struct;
extern crate kaitai_rust;

use kaitai_struct::KaitaiStruct;
use rust::Enum1;

#[test]
fn test_enum_1() {
    if let Ok(r) = Enum1::from_file("src/enum_0.bin") {

        assert_eq!(r.main.submain.pet_1, Enum1_MainObj_Animal::Cat);
        assert_eq!(r.main.submain.pet_2, Enum1_MainObj_Animal::Chicken);
    }
}
