// Autogenerated from KST: please remove this line if doing any edits by hand!

extern crate kaitai_struct;
extern crate rust;

use kaitai_struct::KaitaiStruct;
use rust::ValidNotParsedIf;

#[test]
fn test_valid_not_parsed_if() {
    if let Ok(r) = ValidNotParsedIf::from_file("src/fixed_struct.bin") {

    }
}
