// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.specwrite;

import io.kaitai.struct.KaitaiStruct.ReadWrite;
import io.kaitai.struct.testwrite.BitsUnalignedB64Le;
import org.testng.annotations.Test;

public class TestBitsUnalignedB64Le extends CommonSpec {
    @Override
    protected Class<? extends ReadWrite> getStructClass() {
        return BitsUnalignedB64Le.class;
    }

    @Override
    protected String getSrcFilename() {
        return "process_xor_4.bin";
    }
}
