// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.specwrite;

import io.kaitai.struct.KaitaiStruct.ReadWrite;
import io.kaitai.struct.testwrite.TermU1Val;
import org.testng.annotations.Test;

public class TestTermU1Val extends CommonSpec {
    @Override
    protected Class<? extends ReadWrite> getStructClass() {
        return TermU1Val.class;
    }

    @Override
    protected String getSrcFilename() {
        return "str_encodings.bin";
    }
}
