// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.specwrite;

import io.kaitai.struct.KaitaiStruct.ReadWrite;
import io.kaitai.struct.testwrite.StrPadTermEmpty;
import org.testng.annotations.Test;

public class TestStrPadTermEmpty extends CommonSpec {
    @Override
    protected Class<? extends ReadWrite> getStructClass() {
        return StrPadTermEmpty.class;
    }

    @Override
    protected String getSrcFilename() {
        return "str_pad_term_empty.bin";
    }
}
