// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.specwrite;

import io.kaitai.struct.KaitaiStruct.ReadWrite;
import io.kaitai.struct.testwrite.RepeatUntilCalcArrayType;
import org.testng.annotations.Test;

public class TestRepeatUntilCalcArrayType extends CommonSpec {
    @Override
    protected Class<? extends ReadWrite> getStructClass() {
        return RepeatUntilCalcArrayType.class;
    }

    @Override
    protected String getSrcFilename() {
        return "repeat_until_process.bin";
    }
}
