// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.specwrite;

import io.kaitai.struct.KaitaiStruct.ReadWrite;
import io.kaitai.struct.testwrite.SwitchElseOnly;
import org.testng.annotations.Test;

public class TestSwitchElseOnly extends CommonSpec {
    @Override
    protected Class<? extends ReadWrite> getStructClass() {
        return SwitchElseOnly.class;
    }

    @Override
    protected String getSrcFilename() {
        return "switch_opcodes.bin";
    }
}
