// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.specwrite;

import io.kaitai.struct.KaitaiStruct.ReadWrite;
import io.kaitai.struct.testwrite.EnumNegative;
import org.testng.annotations.Test;

public class TestEnumNegative extends CommonSpec {
    @Override
    protected Class<? extends ReadWrite> getStructClass() {
        return EnumNegative.class;
    }

    @Override
    protected String getSrcFilename() {
        return "enum_negative.bin";
    }
}
