// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.specwrite;

import io.kaitai.struct.KaitaiStruct.ReadWrite;
import io.kaitai.struct.testwrite.TermStruct;
import org.testng.annotations.Test;

public class TestTermStruct extends CommonSpec {
    @Override
    protected Class<? extends ReadWrite> getStructClass() {
        return TermStruct.class;
    }

    @Override
    protected String getSrcFilename() {
        return "term_strz.bin";
    }
}
