// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.specwrite;

import io.kaitai.struct.KaitaiStruct.ReadWrite;
import io.kaitai.struct.testwrite.NavParentSwitch;
import org.testng.annotations.Test;

public class TestNavParentSwitch extends CommonSpec {
    @Override
    protected Class<? extends ReadWrite> getStructClass() {
        return NavParentSwitch.class;
    }

    @Override
    protected String getSrcFilename() {
        return "nav_parent_switch.bin";
    }
}
