// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.specwrite;

import io.kaitai.struct.KaitaiStruct.ReadWrite;
import io.kaitai.struct.testwrite.BitsSignedShiftB64Le;
import org.testng.annotations.Test;

public class TestBitsSignedShiftB64Le extends CommonSpec {
    @Override
    protected Class<? extends ReadWrite> getStructClass() {
        return BitsSignedShiftB64Le.class;
    }

    @Override
    protected String getSrcFilename() {
        return "bits_signed_shift_b64_le.bin";
    }
}
