// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.specwrite;

import io.kaitai.struct.KaitaiStruct.ReadWrite;
import io.kaitai.struct.testwrite.BitsByteAlignedEofBe;
import org.testng.annotations.Test;

public class TestBitsByteAlignedEofBe extends CommonSpec {
    @Override
    protected Class<? extends ReadWrite> getStructClass() {
        return BitsByteAlignedEofBe.class;
    }

    @Override
    protected String getSrcFilename() {
        return "bcd_user_type_be.bin";
    }
}
