// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecStrEncodings : CommonSpec
    {
        [Test]
        public void TestStrEncodings()
        {
            var r = StrEncodings.FromFile(SourceFile("str_encodings.bin"));

            Assert.AreEqual("Some ASCII", r.Str1);
            Assert.AreEqual("\u3053\u3093\u306b\u3061\u306f", r.Str2);
            Assert.AreEqual("\u3053\u3093\u306b\u3061\u306f", r.Str3);
            Assert.AreEqual("\u2591\u2592\u2593", r.Str4);
        }
    }
}
