// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecBitsUnalignedB32Be : CommonSpec
    {
        [Test]
        public void TestBitsUnalignedB32Be()
        {
            var r = BitsUnalignedB32Be.FromFile(SourceFile("process_xor_4.bin"));

            Assert.AreEqual(r.A, true);
            Assert.AreEqual(r.B, 3648472617);
            Assert.AreEqual(r.C, 10);
        }
    }
}
