// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecBufferedStruct : CommonSpec
    {
        [Test]
        public void TestBufferedStruct()
        {
            var r = BufferedStruct.FromFile(SourceFile("buffered_struct.bin"));

            Assert.AreEqual(r.Len1, 16);
            Assert.AreEqual(r.Block1.Number1, 66);
            Assert.AreEqual(r.Block1.Number2, 67);
            Assert.AreEqual(r.Len2, 8);
            Assert.AreEqual(r.Block2.Number1, 68);
            Assert.AreEqual(r.Block2.Number2, 69);
            Assert.AreEqual(r.Finisher, 238);
        }
    }
}
