// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecBitsSeqEndianCombo : CommonSpec
    {
        [Test]
        public void TestBitsSeqEndianCombo()
        {
            var r = BitsSeqEndianCombo.FromFile(SourceFile("process_xor_4.bin"));

            Assert.AreEqual(59, r.Be1);
            Assert.AreEqual(187, r.Be2);
            Assert.AreEqual(163, r.Le3);
            Assert.AreEqual(20, r.Be4);
            Assert.AreEqual(10, r.Le5);
            Assert.AreEqual(36, r.Le6);
            Assert.AreEqual(26, r.Le7);
            Assert.AreEqual(true, r.Be8);
        }
    }
}
