// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecRepeatEosBitsB1 : CommonSpec
    {
        [Test]
        public void TestRepeatEosBitsB1()
        {
            var r = RepeatEosBitsB1.FromFile(SourceFile("enum_negative.bin"));
            Assert.AreEqual(16, r.Bits.Count);
            Assert.AreEqual(true, r.Bits[0]);
            Assert.AreEqual(true, r.Bits[1]);
            Assert.AreEqual(true, r.Bits[2]);
            Assert.AreEqual(true, r.Bits[3]);
            Assert.AreEqual(true, r.Bits[4]);
            Assert.AreEqual(true, r.Bits[5]);
            Assert.AreEqual(true, r.Bits[6]);
            Assert.AreEqual(true, r.Bits[7]);
            Assert.AreEqual(false, r.Bits[8]);
            Assert.AreEqual(false, r.Bits[9]);
            Assert.AreEqual(false, r.Bits[10]);
            Assert.AreEqual(false, r.Bits[11]);
            Assert.AreEqual(false, r.Bits[12]);
            Assert.AreEqual(false, r.Bits[13]);
            Assert.AreEqual(false, r.Bits[14]);
            Assert.AreEqual(true, r.Bits[15]);
        }
    }
}
