// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecDebugArrayUser : CommonSpec
    {
        [Test]
        public void TestDebugArrayUser()
        {
            var r = DebugArrayUser.FromFile(SourceFile("fixed_struct.bin"));
            r._read();

            Assert.AreEqual(r.OneCat.Meow, 80);
            Assert.AreEqual(r.ArrayOfCats[0].Meow, 65);
            Assert.AreEqual(r.ArrayOfCats[1].Meow, 67);
            Assert.AreEqual(r.ArrayOfCats[2].Meow, 75);
        }
    }
}
