// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecBitsEnum : CommonSpec
    {
        [Test]
        public void TestBitsEnum()
        {
            var r = BitsEnum.FromFile(SourceFile("fixed_struct.bin"));

            AreEqual(r.One, BitsEnum.Animal.Platypus);
            AreEqual(r.Two, BitsEnum.Animal.Horse);
            AreEqual(r.Three, BitsEnum.Animal.Cat);
        }
    }
}
