// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecEnumImportLiterals : CommonSpec
    {
        [Test]
        public void TestEnumImportLiterals()
        {
            var r = EnumImportLiterals.FromFile(SourceFile("enum_0.bin"));

            AreEqual(r.Pet1ToI, 7);
            AreEqual(r.Pet1Eq, true);
            AreEqual(r.Pet2, EnumDeep.Container1.Container2.Animal.Hare);
        }
    }
}
