// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecEnumDeepLiterals : CommonSpec
    {
        [Test]
        public void TestEnumDeepLiterals()
        {
            var r = EnumDeepLiterals.FromFile(SourceFile("enum_0.bin"));

            Assert.AreEqual(true, r.IsPet1Ok);
            Assert.AreEqual(true, r.IsPet2Ok);
        }
    }
}
