// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecInstanceUserArray : CommonSpec
    {
        [Test]
        public void TestInstanceUserArray()
        {
            var r = InstanceUserArray.FromFile(SourceFile("instance_std_array.bin"));

            AreEqual(r.Ofs, 16);
            AreEqual(r.QtyEntries, 3);
            AreEqual(r.EntrySize, 4);
            AreEqual(r.UserEntries.Count, 3);
            AreEqual(r.UserEntries[0].Word1, 4369);
            AreEqual(r.UserEntries[0].Word2, 4369);
            AreEqual(r.UserEntries[1].Word1, 8738);
            AreEqual(r.UserEntries[1].Word2, 8738);
            AreEqual(r.UserEntries[2].Word1, 13107);
            AreEqual(r.UserEntries[2].Word2, 13107);
        }
    }
}
