// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecTermStrzUtf16V3 : CommonSpec
    {
        [Test]
        public void TestTermStrzUtf16V3()
        {
            var r = TermStrzUtf16V3.FromFile(SourceFile("term_strz_utf16.bin"));

            Assert.AreEqual("a\u0200b", r.S1);
            Assert.AreEqual(0, r.Term);
            Assert.AreEqual("c\u0200d", r.S2);
            Assert.AreEqual("", r.S3);
        }
    }
}
