// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;
using System;

namespace Kaitai
{
    [TestFixture]
    public class SpecIntegersDoubleOverflow : CommonSpec
    {
        [Test]
        public void TestIntegersDoubleOverflow()
        {
            var r = IntegersDoubleOverflow.FromFile(SourceFile("integers_double_overflow.bin"));

            Assert.AreEqual(-9007199254740991, r.SignedSafeMinBe);
            Assert.AreEqual(-9007199254740991, r.SignedSafeMinLe);
            Assert.AreEqual(9007199254740991, r.SignedSafeMaxBe);
            Assert.AreEqual(9007199254740991, r.SignedSafeMaxLe);
            Assert.AreEqual("-9007199254740993", Convert.ToString((long) (r.SignedUnsafeNegBe), 10));
            Assert.AreEqual("-9007199254740993", Convert.ToString((long) (r.SignedUnsafeNegLe), 10));
            Assert.AreEqual("9007199254740993", Convert.ToString((long) (r.SignedUnsafePosBe), 10));
            Assert.AreEqual("9007199254740993", Convert.ToString((long) (r.SignedUnsafePosBe), 10));
        }
    }
}
