// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecExprToITrailing : CommonSpec
    {
        [Test]
        public void TestExprToITrailing()
        {
            var r = ExprToITrailing.FromFile(SourceFile("term_strz.bin"));

            Assert.Throws<System.FormatException>(
                delegate
                {
                    r.ToIR10;
                }
            );
            Assert.AreEqual(r.ToIR13, 44020937);
            Assert.Throws<System.FormatException>(
                delegate
                {
                    r.ToIGarbage;
                }
            );
        }
    }
}
