// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecTermBytes : CommonSpec
    {
        [Test]
        public void TestTermBytes()
        {
            var r = TermBytes.FromFile(SourceFile("term_strz.bin"));

            Assert.AreEqual(new byte[] { 102, 111, 111 }, r.S1);
            Assert.AreEqual(new byte[] { 98, 97, 114 }, r.S2);
            Assert.AreEqual(new byte[] { 124, 98, 97, 122, 64 }, r.S3);
        }
    }
}
