// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecStrEos : CommonSpec
    {
        [Test]
        public void TestStrEos()
        {
            var r = StrEos.FromFile(SourceFile("term_strz.bin"));

            Assert.AreEqual("foo|bar|baz@", r.Str);
        }
    }
}
