// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecSwitchManualInt : CommonSpec
    {
        [Test]
        public void TestSwitchManualInt()
        {
            var r = SwitchManualInt.FromFile(SourceFile("switch_opcodes.bin"));

            Assert.AreEqual(4, r.Opcodes.Count);
            Assert.AreEqual(83, r.Opcodes[0].Code);
            Assert.AreEqual("foobar", ((SwitchManualInt.Opcode.Strval) (r.Opcodes[0].Body)).Value);
            Assert.AreEqual(73, r.Opcodes[1].Code);
            Assert.AreEqual(66, ((SwitchManualInt.Opcode.Intval) (r.Opcodes[1].Body)).Value);
            Assert.AreEqual(73, r.Opcodes[2].Code);
            Assert.AreEqual(55, ((SwitchManualInt.Opcode.Intval) (r.Opcodes[2].Body)).Value);
            Assert.AreEqual(83, r.Opcodes[3].Code);
            Assert.AreEqual("", ((SwitchManualInt.Opcode.Strval) (r.Opcodes[3].Body)).Value);
        }
    }
}
