// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecFloatToI : CommonSpec
    {
        [Test]
        public void TestFloatToI()
        {
            var r = FloatToI.FromFile(SourceFile("floating_points.bin"));
            Assert.AreEqual(0.5, r.SingleValue, 1e-6);
            Assert.AreEqual(0.25, r.DoubleValue, 1e-6);
            Assert.AreEqual(0.5, r.SingleValueIf, 1e-6);
            Assert.AreEqual(0.25, r.DoubleValueIf, 1e-6);
            Assert.AreEqual(0, r.SingleI);
            Assert.AreEqual(0, r.DoubleI);
            Assert.AreEqual(0, r.SingleIfI);
            Assert.AreEqual(0, r.DoubleIfI);
            Assert.AreEqual(1, r.Float1I);
            Assert.AreEqual(1, r.Float2I);
            Assert.AreEqual(1, r.Float3I);
            Assert.AreEqual(-2, r.Float4I);
            Assert.AreEqual(13, r.CalcIfI);
        }
    }
}
