// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecEnumLongRangeS : CommonSpec
    {
        [Test]
        public void TestEnumLongRangeS()
        {
            var r = EnumLongRangeS.FromFile(SourceFile("enum_long_range_s.bin"));

            AreEqual(r.F1, EnumLongRangeS.Constants.LongMin);
            AreEqual(r.F2, EnumLongRangeS.Constants.IntBelowMin);
            AreEqual(r.F3, EnumLongRangeS.Constants.IntMin);
            AreEqual(r.F4, EnumLongRangeS.Constants.Zero);
            AreEqual(r.F5, EnumLongRangeS.Constants.IntMax);
            AreEqual(r.F6, EnumLongRangeS.Constants.IntOverMax);
            AreEqual(r.F7, EnumLongRangeS.Constants.LongMax);
        }
    }
}
