// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecSwitchRepeatExpr : CommonSpec
    {
        [Test]
        public void TestSwitchRepeatExpr()
        {
            var r = SwitchRepeatExpr.FromFile(SourceFile("switch_tlv.bin"));

            Assert.AreEqual(17, r.Code);
            Assert.AreEqual(9, r.Size);
            Assert.AreEqual(new byte[] { 83, 116, 117, 102, 102, 0, 77, 101, 0 }, ((SwitchRepeatExpr.One) (r.Body[0])).First);
        }
    }
}
