// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecValidFailRangeFloat : CommonSpec
    {
        [Test]
        public void TestValidFailRangeFloat()
        {
            Assert.Throws<ValidationGreaterThanError>(
                delegate
                {
                    ValidFailRangeFloat.FromFile(SourceFile("floating_points.bin"));
                }
            );
        }
    }
}
