// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecIndexSizes : CommonSpec
    {
        [Test]
        public void TestIndexSizes()
        {
            var r = IndexSizes.FromFile(SourceFile("index_sizes.bin"));

            AreEqual(r.Qty, 3);
            AreEqual(r.Sizes[0], 1);
            AreEqual(r.Sizes[1], 8);
            AreEqual(r.Sizes[2], 4);
            AreEqual(r.Bufs[0], "A");
            AreEqual(r.Bufs[1], "BBBBBBBB");
            AreEqual(r.Bufs[2], "CCCC");
        }
    }
}
