// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecParamsPassArrayStruct : CommonSpec
    {
        [Test]
        public void TestParamsPassArrayStruct()
        {
            var r = ParamsPassArrayStruct.FromFile(SourceFile("position_to_end.bin"));

            Assert.AreEqual(r.PassStructs.Structs.Count, 2);
            Assert.AreEqual(((ParamsPassArrayStruct.Foo) (r.PassStructs.Structs[0])).F, 1);
            Assert.AreEqual(((ParamsPassArrayStruct.Bar) (r.PassStructs.Structs[1])).B, 2);
        }
    }
}
