// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecNestedTypes3 : CommonSpec
    {
        [Test]
        public void TestNestedTypes3()
        {
            var r = NestedTypes3.FromFile(SourceFile("fixed_struct.bin"));

            Assert.AreEqual(r.ACc.ValueCc, 80);
            Assert.AreEqual(r.ACD.ValueD, 65);
            Assert.AreEqual(r.B.ValueB, 67);
            Assert.AreEqual(r.B.ACc.ValueCc, 75);
            Assert.AreEqual(r.B.ACD.ValueD, 45);
        }
    }
}
