// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecFloatingPoints : CommonSpec
    {
        [Test]
        public void TestFloatingPoints()
        {
            var r = FloatingPoints.FromFile(SourceFile("floating_points.bin"));

            Assert.AreEqual(((float) (0.5)), r.SingleValue, 1e-6);
            Assert.AreEqual(((float) (0.5)), r.SingleValueBe, 1e-6);
            Assert.AreEqual(0.25, r.DoubleValue, 1e-6);
            Assert.AreEqual(0.25, r.DoubleValueBe, 1e-6);
            Assert.AreEqual(1.2345, r.ApproximateValue, 1e-6);
            Assert.AreEqual(1.5, r.SingleValuePlusInt, 1e-6);
            Assert.AreEqual(1.0, r.SingleValuePlusFloat, 1e-6);
            Assert.AreEqual(0.3, r.DoubleValuePlusFloat, 1e-6);
        }
    }
}
