// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecParamsPassArrayStr : CommonSpec
    {
        [Test]
        public void TestParamsPassArrayStr()
        {
            var r = ParamsPassArrayStr.FromFile(SourceFile("term_strz.bin"));

            Assert.AreEqual(3, r.PassStrArray.Strs.Count);
            Assert.AreEqual("fo", r.PassStrArray.Strs[0]);
            Assert.AreEqual("o|", r.PassStrArray.Strs[1]);
            Assert.AreEqual("ba", r.PassStrArray.Strs[2]);
            Assert.AreEqual(2, r.PassStrArrayCalc.Strs.Count);
            Assert.AreEqual("aB", r.PassStrArrayCalc.Strs[0]);
            Assert.AreEqual("Cd", r.PassStrArrayCalc.Strs[1]);
        }
    }
}
