// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;
using System.Collections.Generic;

namespace Kaitai
{
    [TestFixture]
    public class SpecSwitchManualIntSizeElse : CommonSpec
    {
        [Test]
        public void TestSwitchManualIntSizeElse()
        {
            var r = SwitchManualIntSizeElse.FromFile(SourceFile("switch_tlv.bin"));

            AreEqual(r.Chunks.Count, 4);
            AreEqual(r.Chunks[0].Code, 17);
            AreEqual(((SwitchManualIntSizeElse.Chunk.ChunkMeta) (r.Chunks[0].Body)).Title, "Stuff");
            AreEqual(((SwitchManualIntSizeElse.Chunk.ChunkMeta) (r.Chunks[0].Body)).Author, "Me");
            AreEqual(r.Chunks[1].Code, 34);
            AreEqual(((SwitchManualIntSizeElse.Chunk.ChunkDir) (r.Chunks[1].Body)).Entries, new List<string> { "AAAA", "BBBB", "CCCC" });
            AreEqual(r.Chunks[2].Code, 51);
            AreEqual(((SwitchManualIntSizeElse.Chunk.Dummy) (r.Chunks[2].Body)).Rest, new byte[] { 16, 32, 48, 64, 80, 96, 112, 128 });
            AreEqual(r.Chunks[3].Code, 255);
            AreEqual(((SwitchManualIntSizeElse.Chunk.Dummy) (r.Chunks[3].Body)).Rest, new byte[] {  });
        }
    }
}
