// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecExprIoTernary : CommonSpec
    {
        [Test]
        public void TestExprIoTernary()
        {
            var r = ExprIoTernary.FromFile(SourceFile("if_struct.bin"));

            Assert.AreEqual(r.OneOrTwoIoSize1, 8);
            Assert.AreEqual(r.OneOrTwoIoSize2, 8);
            Assert.AreEqual(r.OneOrTwoIoSizeAdd3, 11);
        }
    }
}
