// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecImportsParamsDefEnumImported : CommonSpec
    {
        [Test]
        public void TestImportsParamsDefEnumImported()
        {
            var r = ImportsParamsDefEnumImported.FromFile(SourceFile("enum_0.bin"));

            Assert.AreEqual(Enum0.Animal.Cat, r.One.Pet1);
            Assert.AreEqual(EnumDeep.Container1.Container2.Animal.Hare, r.One.Pet2);
            Assert.AreEqual(Enum0.Animal.Cat, r.Two.Pet1Param);
            Assert.AreEqual(EnumDeep.Container1.Container2.Animal.Hare, r.Two.Pet2Param);
        }
    }
}
