// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecStrLiterals2 : CommonSpec
    {
        [Test]
        public void TestStrLiterals2()
        {
            var r = StrLiterals2.FromFile(SourceFile("fixed_struct.bin"));

            Assert.AreEqual("$foo", r.Dollar1);
            Assert.AreEqual("${foo}", r.Dollar2);
            Assert.AreEqual("#{foo}", r.Hash);
            Assert.AreEqual("@foo", r.AtSign);
        }
    }
}
