// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecExprFstring0 : CommonSpec
    {
        [Test]
        public void TestExprFstring0()
        {
            var r = ExprFstring0.FromFile(SourceFile("term_strz.bin"));

            AreEqual(r.SeqStr, "foo|b");
            AreEqual(r.SeqInt, 97);
            AreEqual(r.Empty, "");
            AreEqual(r.Literal, "abc");
            AreEqual(r.LiteralWithEscapes, "abc\n\tt");
            AreEqual(r.HeadAndIntLiteral, "abc=123");
            AreEqual(r.HeadAndStrLiteral, "abc=foo");
            AreEqual(r.HeadAndInt, "abc=97");
            AreEqual(r.HeadAndStr, "abc=foo|b");
        }
    }
}
