// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;
using System.IO;

namespace Kaitai
{
    [TestFixture]
    public class SpecEosExceptionBytes : CommonSpec
    {
        [Test]
        public void TestEosExceptionBytes()
        {
            Assert.Throws<EndOfStreamException>(
                delegate
                {
                    EosExceptionBytes.FromFile(SourceFile("term_strz.bin"));
                }
            );
        }
    }
}
