// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecSwitchManualEnumInvalid : CommonSpec
    {
        [Test]
        public void TestSwitchManualEnumInvalid()
        {
            var r = SwitchManualEnumInvalid.FromFile(SourceFile("enum_negative.bin"));

            AreEqual(r.Opcodes.Count, 2);
            AreEqual(r.Opcodes[0].Code, (SwitchManualEnumInvalid.Opcode.CodeEnum) 255);
            Assert.IsNull(r.Opcodes[0].Body);
            AreEqual(r.Opcodes[1].Code, (SwitchManualEnumInvalid.Opcode.CodeEnum) 1);
            Assert.IsNull(r.Opcodes[1].Body);
        }
    }
}
