// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecIndexToParamUntil : CommonSpec
    {
        [Test]
        public void TestIndexToParamUntil()
        {
            var r = IndexToParamUntil.FromFile(SourceFile("index_sizes.bin"));

            Assert.AreEqual(3, r.Qty);
            Assert.AreEqual(1, r.Sizes[0]);
            Assert.AreEqual(8, r.Sizes[1]);
            Assert.AreEqual(4, r.Sizes[2]);
            Assert.AreEqual("A", r.Blocks[0].Buf);
            Assert.AreEqual("BBBBBBBB", r.Blocks[1].Buf);
            Assert.AreEqual("CCCC", r.Blocks[2].Buf);
        }
    }
}
