// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;
using System.Collections.Generic;

namespace Kaitai
{
    [TestFixture]
    public class SpecRepeatUntilS4 : CommonSpec
    {
        [Test]
        public void TestRepeatUntilS4()
        {
            var r = RepeatUntilS4.FromFile(SourceFile("repeat_until_s4.bin"));

            Assert.AreEqual(r.Entries, new List<int> { 66, 4919, -251658241, -1 });
            Assert.AreEqual(r.Afterall, "foobar");
        }
    }
}
