// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecParamsCall : CommonSpec
    {
        [Test]
        public void TestParamsCall()
        {
            var r = ParamsCall.FromFile(SourceFile("term_strz.bin"));

            AreEqual(r.Buf1.Body, "foo|b");
            AreEqual(r.Buf2.Body, "ar|ba");
            AreEqual(r.Buf2.Trailer, 122);
        }
    }
}
