// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecNavParentRecursive : CommonSpec
    {
        [Test]
        public void TestNavParentRecursive()
        {
            var r = NavParentRecursive.FromFile(SourceFile("enum_negative.bin"));

            Assert.AreEqual(255, r.Value);
            Assert.AreEqual(1, r.Next.Value);
            Assert.AreEqual(255, r.Next.ParentValue);
            Assert.IsNull(r.Next.Next);
        }
    }
}
