// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecIntegers : CommonSpec
    {
        [Test]
        public void TestIntegers()
        {
            var r = Integers.FromFile(SourceFile("fixed_struct.bin"));

            AreEqual(r.Uint8, 255);
            AreEqual(r.Uint16, 65535);
            AreEqual(r.Uint32, 4294967295);
            AreEqual(r.Uint64, 18446744073709551615);
            AreEqual(r.Sint8, -1);
            AreEqual(r.Sint16, -1);
            AreEqual(r.Sint32, -1);
            AreEqual(r.Sint64, -1);
            AreEqual(r.Uint16le, 66);
            AreEqual(r.Uint32le, 66);
            AreEqual(r.Uint64le, 66);
            AreEqual(r.Sint16le, -66);
            AreEqual(r.Sint32le, -66);
            AreEqual(r.Sint64le, -66);
            AreEqual(r.Uint16be, 66);
            AreEqual(r.Uint32be, 66);
            AreEqual(r.Uint64be, 66);
            AreEqual(r.Sint16be, -66);
            AreEqual(r.Sint32be, -66);
            AreEqual(r.Sint64be, -66);
        }
    }
}
