// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecNestedSameName : CommonSpec
    {
        [Test]
        public void TestNestedSameName()
        {
            var r = NestedSameName.FromFile(SourceFile("repeat_n_struct.bin"));

            AreEqual(r.MainData.MainSize, 2);
            AreEqual(r.MainData.Foo.Data, new byte[] { 16, 0, 0, 0 });
        }
    }
}
