// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecRepeatNStruct : CommonSpec
    {
        [Test]
        public void TestRepeatNStruct()
        {
            var r = RepeatNStruct.FromFile(SourceFile("repeat_n_struct.bin"));

            Assert.AreEqual(2, r.Chunks.Count);
            Assert.AreEqual(16, r.Chunks[0].Offset);
            Assert.AreEqual(8312, r.Chunks[0].Len);
            Assert.AreEqual(8328, r.Chunks[1].Offset);
            Assert.AreEqual(15, r.Chunks[1].Len);
        }
    }
}
