// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecParamsPassArrayUsertype : CommonSpec
    {
        [Test]
        public void TestParamsPassArrayUsertype()
        {
            var r = ParamsPassArrayUsertype.FromFile(SourceFile("position_to_end.bin"));

            AreEqual(r.PassBlocks.Bar.Count, 2);
            AreEqual(r.PassBlocks.Bar[0].Foo, 1);
            AreEqual(r.PassBlocks.Bar[1].Foo, 2);
            AreEqual(r.PassBlocks.One, new byte[] { 3 });
            AreEqual(r.PassBlocks.Two, new byte[] { 4, 5 });
        }
    }
}
