// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecNestedTypes3 : CommonSpec
    {
        [Test]
        public void TestNestedTypes3()
        {
            var r = NestedTypes3.FromFile(SourceFile("fixed_struct.bin"));

            Assert.AreEqual(80, r.ACc.ValueCc);
            Assert.AreEqual(65, r.ACD.ValueD);
            Assert.AreEqual(67, r.B.ValueB);
            Assert.AreEqual(75, r.B.ACc.ValueCc);
            Assert.AreEqual(45, r.B.ACD.ValueD);
        }
    }
}
