// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecBytesPadTerm : CommonSpec
    {
        [Test]
        public void TestBytesPadTerm()
        {
            var r = BytesPadTerm.FromFile(SourceFile("str_pad_term.bin"));

            Assert.AreEqual(new byte[] { 115, 116, 114, 49 }, r.StrPad);
            Assert.AreEqual(new byte[] { 115, 116, 114, 50, 102, 111, 111 }, r.StrTerm);
            Assert.AreEqual(new byte[] { 115, 116, 114, 43, 43, 43, 51, 98, 97, 114, 43, 43, 43 }, r.StrTermAndPad);
            Assert.AreEqual(new byte[] { 115, 116, 114, 52, 98, 97, 122, 64 }, r.StrTermInclude);
        }
    }
}
