// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecImportsAbs : CommonSpec
    {
        [Test]
        public void TestImportsAbs()
        {
            var r = ImportsAbs.FromFile(SourceFile("fixed_struct.bin"));

            Assert.AreEqual(80, r.Len.Value);
            Assert.AreEqual(80, r.Body.Length);
        }
    }
}
