// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecValidFailAnyofInt : CommonSpec
    {
        [Test]
        public void TestValidFailAnyofInt()
        {
            Assert.Throws<ValidationNotAnyOfError>(
                delegate
                {
                    ValidFailAnyofInt.FromFile(SourceFile("fixed_struct.bin"));
                }
            );
        }
    }
}
