// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecExprStrEncodings : CommonSpec
    {
        [Test]
        public void TestExprStrEncodings()
        {
            var r = ExprStrEncodings.FromFile(SourceFile("str_encodings.bin"));

            AreEqual(r.Str1Eq, true);
            AreEqual(r.Str2Eq, true);
            AreEqual(r.Str3Eq, true);
            AreEqual(r.Str3EqStr2, true);
            AreEqual(r.Str4Eq, true);
            AreEqual(r.Str4GtStrCalc, true);
            AreEqual(r.Str4GtStrFromBytes, true);
        }
    }
}
