-- Autogenerated from KST: please remove this line if doing any edits by hand!

local luaunit = require("luaunit")

require("switch_repeat_expr_invalid")

TestSwitchRepeatExprInvalid = {}

function TestSwitchRepeatExprInvalid:test_switch_repeat_expr_invalid()
    local r = SwitchRepeatExprInvalid:from_file("src/switch_integers.bin")
    luaunit.assertEquals(#r.codes, 3)
    luaunit.assertEquals(r.codes[0 + 1], 1)
    luaunit.assertEquals(r.codes[1 + 1], 7)
    luaunit.assertEquals(r.codes[2 + 1], 2)
    luaunit.assertEquals(r.body[0 + 1].first, "\064\064\004\055")
    luaunit.assertEquals(r.body[1 + 1], "\019\000\000\008")
    luaunit.assertEquals(r.body[2 + 1].second, "\055\019\000\000")
end
