-- Autogenerated from KST: please remove this line if doing any edits by hand!

local luaunit = require("luaunit")

require("str_encodings_default")

TestStrEncodingsDefault = {}

function TestStrEncodingsDefault:test_str_encodings_default()
    local r = StrEncodingsDefault:from_file("src/str_encodings.bin")

    luaunit.assertEquals(r.str1, "Some ASCII")
    luaunit.assertEquals(r.rest.str2, "\u{3053}\u{3093}\u{306b}\u{3061}\u{306f}")
    luaunit.assertEquals(r.rest.str3, "\u{3053}\u{3093}\u{306b}\u{3061}\u{306f}")
    luaunit.assertEquals(r.rest.str4, "\u{2591}\u{2592}\u{2593}")
end
