-- Autogenerated from KST: please remove this line if doing any edits by hand!

local luaunit = require("luaunit")

require("switch_repeat_expr_invalid")

TestSwitchRepeatExprInvalid = {}

function TestSwitchRepeatExprInvalid:test_switch_repeat_expr_invalid()
    local r = SwitchRepeatExprInvalid:from_file("src/switch_tlv.bin")

    luaunit.assertEquals(r.code, 17)
    luaunit.assertEquals(r.size, 9)
    luaunit.assertEquals(r.body[0 + 1], "\083\116\117\102\102\000\077\101\000")
end
