-- Autogenerated from KST: please remove this line if doing any edits by hand!

local luaunit = require("luaunit")

require("eos_exception_sized")

TestEosExceptionSized = {}

function TestEosExceptionSized:test_eos_exception_sized()
    luaunit.assertErrorMsgMatches(".+: requested %d+ bytes, but only %d+ bytes available", EosExceptionSized.from_file, EosExceptionSized, "src/term_strz.bin")
end
