-- Autogenerated from KST: please remove this line if doing any edits by hand!

local luaunit = require("luaunit")

require("term_strz_utf16_v4")

TestTermStrzUtf16V4 = {}

function TestTermStrzUtf16V4:test_term_strz_utf16_v4()
    local r = TermStrzUtf16V4:from_file("src/term_strz_utf16.bin")

    luaunit.assertEquals(r.s1.value, "a\u{0200}b")
    luaunit.assertEquals(r.s2.value, "c\u{0200}d")
    luaunit.assertEquals(r.s3.value, "e\u{0200}f")
end
