-- Autogenerated from KST: please remove this line if doing any edits by hand!

local luaunit = require("luaunit")

require("nav_parent_recursive")

TestNavParentRecursive = {}

function TestNavParentRecursive:test_nav_parent_recursive()
    local r = NavParentRecursive:from_file("src/enum_negative.bin")

    luaunit.assertEquals(r.value, 255)
    luaunit.assertEquals(r.next.value, 1)
    luaunit.assertEquals(r.next.parent_value, 255)
    luaunit.assertNil(r.next.next)
end
