-- Autogenerated from KST: please remove this line if doing any edits by hand!

local luaunit = require("luaunit")

require("opaque_external_type")

TestOpaqueExternalType = {}

function TestOpaqueExternalType:test_opaque_external_type()
    local r = OpaqueExternalType:from_file("src/term_strz.bin")

    luaunit.assertEquals(r.hw.one, 102)
end
