-- Autogenerated from KST: please remove this line if doing any edits by hand!

local luaunit = require("luaunit")

require("valid_fail_eq_str")

TestValidFailEqStr = {}

function TestValidFailEqStr:test_valid_fail_eq_str()
    luaunit.assertErrorMsgMatches(".+: not equal, expected .*, but got .*", ValidFailEqStr.from_file, ValidFailEqStr, "src/fixed_struct.bin")
end
