-- Autogenerated from KST: please remove this line if doing any edits by hand!

local luaunit = require("luaunit")

require("valid_fail_anyof_int")

TestValidFailAnyofInt = {}

function TestValidFailAnyofInt:test_valid_fail_anyof_int()
    luaunit.assertErrorMsgMatches(".+: ValidationNotAnyOfError", ValidFailAnyofInt.from_file, ValidFailAnyofInt, "src/fixed_struct.bin")
end
