-- Autogenerated from KST: please remove this line if doing any edits by hand!

local luaunit = require("luaunit")

require("str_literals_latin1")

TestStrLiteralsLatin1 = {}

function TestStrLiteralsLatin1:test_str_literals_latin1()
    local r = StrLiteralsLatin1:from_file("src/str_literals_latin1.bin")

    luaunit.assertEquals(r.parsed_eq_literal, true)
end
