-- Autogenerated from KST: please remove this line if doing any edits by hand!

local luaunit = require("luaunit")

require("bits_shift_by_b64_le")

TestBitsShiftByB64Le = {}

function TestBitsShiftByB64Le:test_bits_shift_by_b64_le()
    local r = BitsShiftByB64Le:from_file("src/bits_shift_by_b64_le.bin")

    luaunit.assertEquals(r.a, 0xffffffffffffffff)
    luaunit.assertEquals(r.b, 0)
end
