-- Autogenerated from KST: please remove this line if doing any edits by hand!

local luaunit = require("luaunit")

require("params_call")

TestParamsCall = {}

function TestParamsCall:test_params_call()
    local r = ParamsCall:from_file("src/term_strz.bin")

    luaunit.assertEquals(r.buf1.body, "foo|b")
    luaunit.assertEquals(r.buf2.body, "ar|ba")
    luaunit.assertEquals(r.buf2.trailer, 122)
end
