-- Autogenerated from KST: please remove this line if doing any edits by hand!

local luaunit = require("luaunit")

require("valid_fail_contents_inst")

TestValidFailContentsInst = {}

function TestValidFailContentsInst:test_valid_fail_contents_inst()
    luaunit.assertErrorMsgMatches(".+: not equal, expected .*, but got .*", ValidFailContentsInst.from_file, ValidFailContentsInst, "src/fixed_struct.bin")
end
