-- Autogenerated from KST: please remove this line if doing any edits by hand!

local luaunit = require("luaunit")

require("valid_fail_eq_int")

TestValidFailEqInt = {}

function TestValidFailEqInt:test_valid_fail_eq_int()
    luaunit.assertErrorMsgMatches(".+: not equal, expected .*, but got .*", ValidFailEqInt.from_file, ValidFailEqInt, "src/fixed_struct.bin")
end
