-- Autogenerated from KST: please remove this line if doing any edits by hand!

local luaunit = require("luaunit")

require("expr_bytes_ops")

TestExprBytesOps = {}

function TestExprBytesOps:test_expr_bytes_ops()
    local r = ExprBytesOps:from_file("src/nav_parent_switch.bin")

    luaunit.assertEquals(r.one_size, 3)
    luaunit.assertEquals(r.one_first, 1)
    luaunit.assertEquals(r.one_mid, 66)
    luaunit.assertEquals(r.one_last, 255)
    luaunit.assertEquals(tostring(r.one_last), "255")
    luaunit.assertEquals(r.one_min, 1)
    luaunit.assertEquals(r.one_max, 255)
    luaunit.assertEquals(tostring(r.one_max), "255")
    luaunit.assertEquals(r.two_size, 3)
    luaunit.assertEquals(r.two_first, 65)
    luaunit.assertEquals(r.two_mid, 255)
    luaunit.assertEquals(tostring(r.two_mid), "255")
    luaunit.assertEquals(r.two_last, 75)
    luaunit.assertEquals(r.two_min, 65)
    luaunit.assertEquals(r.two_max, 255)
    luaunit.assertEquals(tostring(r.two_max), "255")
end
