-- Autogenerated from KST: please remove this line if doing any edits by hand!

local luaunit = require("luaunit")

require("valid_fail_inst")

TestValidFailInst = {}

function TestValidFailInst:test_valid_fail_inst()
    luaunit.assertErrorMsgMatches(".+: not equal, expected .*, but got .*", ValidFailInst.from_file, ValidFailInst, "src/fixed_struct.bin")
end
