-- Autogenerated from KST: please remove this line if doing any edits by hand!

local luaunit = require("luaunit")

require("buffered_struct")

TestBufferedStruct = {}

function TestBufferedStruct:test_buffered_struct()
    local r = BufferedStruct:from_file("src/buffered_struct.bin")

    luaunit.assertEquals(r.len1, 16)
    luaunit.assertEquals(r.block1.number1, 66)
    luaunit.assertEquals(r.block1.number2, 67)
    luaunit.assertEquals(r.len2, 8)
    luaunit.assertEquals(r.block2.number1, 68)
    luaunit.assertEquals(r.block2.number2, 69)
    luaunit.assertEquals(r.finisher, 238)
end
