# Autogenerated from KST: please remove this line if doing any edits by hand!

package spec::perl::TestReservedPythonKeywords;

use strict;
use warnings;
use base qw(Test::Class);
use Test::More;
use ReservedPythonKeywords;

sub test_reserved_python_keywords: Test(45) {
    my $r = ReservedPythonKeywords->from_file('src/full256.bin');
    is($r->and(), 0, 'Equals');
    is($r->as(), 1, 'Equals');
    is($r->assert(), 2, 'Equals');
    is($r->async(), 3, 'Equals');
    is($r->await(), 4, 'Equals');
    is($r->break(), 5, 'Equals');
    is($r->class(), 6, 'Equals');
    is($r->continue(), 7, 'Equals');
    is($r->def(), 8, 'Equals');
    is($r->del(), 9, 'Equals');
    is($r->elif(), 10, 'Equals');
    is($r->else(), 11, 'Equals');
    is($r->except(), 12, 'Equals');
    is($r->false(), 13, 'Equals');
    is($r->finally(), 14, 'Equals');
    is($r->for(), 15, 'Equals');
    is($r->from(), 16, 'Equals');
    is($r->global(), 17, 'Equals');
    is($r->if(), 18, 'Equals');
    is($r->import(), 19, 'Equals');
    is($r->in(), 20, 'Equals');
    is($r->is(), 21, 'Equals');
    is($r->lambda(), 22, 'Equals');
    is($r->none(), 23, 'Equals');
    is($r->nonlocal(), 24, 'Equals');
    is($r->not(), 25, 'Equals');
    is($r->or(), 26, 'Equals');
    is($r->pass(), 27, 'Equals');
    is($r->raise(), 28, 'Equals');
    is($r->return(), 29, 'Equals');
    is($r->true(), 30, 'Equals');
    is($r->try(), 31, 'Equals');
    is($r->while(), 32, 'Equals');
    is($r->with(), 33, 'Equals');
    is($r->yield(), 34, 'Equals');
    is($r->keyword_struct_def()->while(), 35, 'Equals');
    is($r->keyword_struct_def()->for(), 36, 'Equals');
    is($r->keyword_struct_def()->with(), 37, 'Equals');
    is($r->keyword_struct_false()->pass(), 38, 'Equals');
    is($r->keyword_enum(), $ReservedPythonKeywords::TRUE_AND, 'Equals');
    is($r->keyword_nested_enum(), $ReservedPythonKeywords::Def::TRY_EXCEPT, 'Equals');
    is($r->inst_keyword_seq(), 1, 'Equals');
    is($r->inst_keyword_enum(), $ReservedPythonKeywords::TRUE_IF, 'Equals');
    is($r->inst_keyword_enum_to_i(), 6, 'Equals');
    is($r->keyword_struct_def()->return(), 71, 'Equals');
}

Test::Class->runtests;
