# Autogenerated from KST: please remove this line if doing any edits by hand!

package spec::perl::TestSwitchRepeatExpr;

use strict;
use warnings;
use base qw(Test::Class);
use Test::More;
use SwitchRepeatExpr;

sub test_switch_repeat_expr: Test(7) {
    my $r = SwitchRepeatExpr->from_file('src/switch_integers.bin');
    is(scalar(@{$r->codes()}), 3, 'Equals');
    is(@{$r->codes()}[0], 1, 'Equals');
    is(@{$r->codes()}[1], 7, 'Equals');
    is(@{$r->codes()}[2], 2, 'Equals');
    is(@{$r->body()}[0]->first(), pack('C*', (64, 64, 4, 55)), 'Equals');
    is(@{$r->body()}[1]->second(), pack('C*', (19, 0, 0, 8)), 'Equals');
    is(@{$r->body()}[2]->first(), pack('C*', (55, 19, 0, 0)), 'Equals');
}

Test::Class->runtests;
