# Autogenerated from KST: please remove this line if doing any edits by hand!

package spec::perl::TestExprFstring0;

use strict;
use warnings;
use base qw(Test::Class);
use Test::More;
use ExprFstring0;

sub test_expr_fstring_0: Test(9) {
    my $r = ExprFstring0->from_file('src/term_strz.bin');

    is($r->seq_str(), "foo|b", 'Equals');
    is($r->seq_int(), 97, 'Equals');
    is($r->empty(), "", 'Equals');
    is($r->literal(), "abc", 'Equals');
    is($r->literal_with_escapes(), "abc\n\tt", 'Equals');
    is($r->head_and_int_literal(), "abc=123", 'Equals');
    is($r->head_and_str_literal(), "abc=foo", 'Equals');
    is($r->head_and_int(), "abc=97", 'Equals');
    is($r->head_and_str(), "abc=foo|b", 'Equals');
}

Test::Class->runtests;
