# Autogenerated from KST: please remove this line if doing any edits by hand!

package spec::perl::TestNavParentRecursive;

use strict;
use warnings;
use base qw(Test::Class);
use Test::More;
use NavParentRecursive;

sub test_nav_parent_recursive: Test(4) {
    my $r = NavParentRecursive->from_file('src/enum_negative.bin');

    is($r->value(), 255, 'Equals');
    is($r->next()->value(), 1, 'Equals');
    is($r->next()->parent_value(), 255, 'Equals');
    ok(!defined($r->next()->next()), 'nil');
}

Test::Class->runtests;
