# Autogenerated from KST: please remove this line if doing any edits by hand!

package spec::perl::TestRepeatUntilS4;

use strict;
use warnings;
use base qw(Test::Class);
use Test::More;
use RepeatUntilS4;

sub test_repeat_until_s4: Test(2) {
    my $r = RepeatUntilS4->from_file('src/repeat_until_s4.bin');

    is_deeply($r->entries(), [66, 4919, -251658241, -1], 'Equals');
    is($r->afterall(), "foobar", 'Equals');
}

Test::Class->runtests;
