# Autogenerated from KST: please remove this line if doing any edits by hand!

package spec::perl::TestSwitchRepeatExprInvalid;

use strict;
use warnings;
use base qw(Test::Class);
use Test::More;
use SwitchRepeatExprInvalid;

sub test_switch_repeat_expr_invalid: Test(3) {
    my $r = SwitchRepeatExprInvalid->from_file('src/switch_tlv.bin');

    is($r->code(), 17, 'Equals');
    is($r->size(), 9, 'Equals');
    is(@{$r->body()}[0], pack('C*', (83, 116, 117, 102, 102, 0, 77, 101, 0)), 'Equals');
}

Test::Class->runtests;
