# Autogenerated from KST: please remove this line if doing any edits by hand!

package spec::perl::TestExprIoTernary;

use strict;
use warnings;
use base qw(Test::Class);
use Test::More;
use ExprIoTernary;

sub test_expr_io_ternary: Test(3) {
    my $r = ExprIoTernary->from_file('src/if_struct.bin');

    is($r->one_or_two_io_size1(), 8, 'Equals');
    is($r->one_or_two_io_size2(), 8, 'Equals');
    is($r->one_or_two_io_size_add_3(), 11, 'Equals');
}

Test::Class->runtests;
