# Autogenerated from KST: please remove this line if doing any edits by hand!

package spec::perl::TestParamsCallShort;

use strict;
use warnings;
use base qw(Test::Class);
use Test::More;
use ParamsCallShort;

sub test_params_call_short: Test(3) {
    my $r = ParamsCallShort->from_file('src/term_strz.bin');

    is($r->buf1()->body(), "foo|b", 'Equals');
    is($r->buf2()->body(), "ar|ba", 'Equals');
    is($r->buf2()->trailer(), 122, 'Equals');
}

Test::Class->runtests;
