# Autogenerated from KST: please remove this line if doing any edits by hand!

package spec::perl::TestExpr0;

use strict;
use warnings;
use base qw(Test::Class);
use Test::More;
use Expr0;

sub test_expr_0: Test(2) {
    my $r = Expr0->from_file('src/str_encodings.bin');

    is($r->must_be_f7(), 247, 'Equals');
    is($r->must_be_abc123(), "abc123", 'Equals');
}

Test::Class->runtests;
