# Autogenerated from KST: please remove this line if doing any edits by hand!

package spec::perl::TestBitsSimpleLe;

use strict;
use warnings;
use base qw(Test::Class);
use Test::More;
use BitsSimpleLe;

sub test_bits_simple_le: Test(14) {
    my $r = BitsSimpleLe->from_file('src/fixed_struct.bin');

    is($r->byte_1(), 80, 'Equals');
    is($r->byte_2(), 65, 'Equals');
    cmp_ok($r->bits_a(), '==', 1, 'Equals');
    is($r->bits_b(), 1, 'Equals');
    is($r->bits_c(), 4, 'Equals');
    is($r->large_bits_1(), 331, 'Equals');
    is($r->spacer(), 3, 'Equals');
    is($r->large_bits_2(), 393, 'Equals');
    is($r->normal_s2(), -1, 'Equals');
    is($r->byte_8_9_10(), 4407632, 'Equals');
    is($r->byte_11_to_14(), 760556875, 'Equals');
    is($r->byte_15_to_19(), 1099499455812, 'Equals');
    is($r->byte_20_to_27(), 18446744073709551615, 'Equals');
    is($r->test_if_b1(), 123, 'Equals');
}

Test::Class->runtests;
