#!/usr/bin/env ruby

require_relative 'test_result'
require_relative 'junit_xml_parser'
require_relative 'rspec_json_parser'

TEST_ROOT = ARGV[0]

parsers = {
  'java' => JUnitXMLParser.new("#{TEST_ROOT}/java/junitreports/TEST-io.kaitai.struct.spec.SpecTests.xml"),
  'python' => JUnitXMLParser.new("#{TEST_ROOT}/python"),
  'ruby' => RSpecJSONParser.new("#{TEST_ROOT}/ruby/test-output-ruby.json"),
}

@aggr = {}

parsers.each_pair { |lang, result|
  result.each_test { |t|
    h = (@aggr[t.name] ||= {})
    h[lang] = t
  }
}

langs = parsers.keys.sort

puts <<__EOF__
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Kaitai Struct: test results</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="container">
    <table class="table">
    <tr>
      <th>Test</th>
__EOF__

langs.each { |lang|
  puts "      <th>#{lang}</th>"
}

puts <<__EOF__
    </tr>

__EOF__

@aggr.keys.sort.each { |test_name|
  puts "<tr>"
  puts "  <td>#{test_name}</td>"

  tests = @aggr[test_name]
  langs.each { |lang|
    test = tests[lang]
    if test
      puts "  <td>#{test.status}</td>"
    else
      puts "  <td>didn't run</td>"
    end
  }

  puts "</tr>"
}

puts <<__EOF__
    </table>
    </div>
</body>
</html>
__EOF__
