#!/usr/bin/env ruby

require 'erb'

require_relative 'test_result'
require_relative 'junit_xml_parser'
require_relative 'rspec_json_parser'

TEST_ROOT = ARGV[0]

parsers = {
  'java' => JUnitXMLParser.new("#{TEST_ROOT}/java/junitreports/TEST-io.kaitai.struct.spec.SpecTests.xml"),
  'javascript' => JUnitXMLParser.new("#{TEST_ROOT}/javascript/test-output-javascript.xml"),
  'python' => JUnitXMLParser.new("#{TEST_ROOT}/python"),
  'ruby' => RSpecJSONParser.new("#{TEST_ROOT}/ruby/test-output-ruby.json"),
}

@aggr = {}
@count_ok = {}

parsers.each_pair { |lang, result|
  ok = 0
  result.each_test { |t|
    h = (@aggr[t.name] ||= {})
    raise "Duplicate test name \"#{t.name}\" for #{lang}" if h[lang]
    h[lang] = t
    ok +=1 if t.status == :passed
  }
  @count_ok[lang] = ok
}

@langs = parsers.keys.sort

puts "got #{@aggr.size} tests..."
puts "processing for #{@langs.inspect}..."

@date = Time.now.utc.to_s

bin_dir = File.expand_path(File.dirname(__FILE__))
tmpl = ERB.new(File.read("#{bin_dir}/report.html.erb"), nil, nil, '_err')
File.open(ARGV[1], 'w') { |out|
  out.print tmpl.result(binding)
}
