#!/usr/bin/env ruby

require 'erb'

require_relative 'test_result'
require_relative 'junit_xml_parser'
require_relative 'rspec_json_parser'
require_relative 'boost_test_parser'
require_relative 'nunit_xml_parser'
require_relative 'build_fail_parser'

TEST_ROOT = ARGV[0]

parsers = {
  'csharp' => NUnitXMLParser.new("#{TEST_ROOT}/csharp/TestResult.xml"),
  'cpp_stl' => BoostTestParser.new("#{TEST_ROOT}/cpp_stl/results.xml"),
  'java' => JUnitXMLParser.new("#{TEST_ROOT}/java/junitreports"),
  'javascript' => JUnitXMLParser.new("#{TEST_ROOT}/javascript/test-output-javascript.xml"),
  'python' => JUnitXMLParser.new("#{TEST_ROOT}/python"),
  'ruby' => RSpecJSONParser.new("#{TEST_ROOT}/ruby/test-output-ruby.json"),
}

@aggr = {}
@count_ok = {}

# Process testing results
parsers.each_pair { |lang, result|
  ok = 0
  result.each_test { |t|
    h = (@aggr[t.name] ||= {})
    raise "Duplicate test name \"#{t.name}\" for #{lang}" if h[lang]
    h[lang] = t
    ok +=1 if t.status == :passed
  }
  @count_ok[lang] = ok
}

# Add build fail results
bfps = {
  'java' => BuildFailParser.new("#{TEST_ROOT}/java"),
}

bfps.each_pair { |lang, bfp|
  bfp.each_test { |t|
    h = (@aggr[t.name] ||= {})
    prev_t = h[lang]
    if prev_t
      if prev_t.status == :format_build_failed and t.status == :spec_build_failed
        # "format failed" is the culprit, trust it
        next
      elsif prev_t.status == :spec_build_failed and t.status == :format_build_failed
        # actually it is "format failed", store it
      else
        raise "Already got test information on failing build test \"#{t.name}\" for #{lang}: #{h[lang].inspect}"
      end
    end
    h[lang] = t
  }
}

@langs = parsers.keys.sort

puts "got #{@aggr.size} tests..."
puts "processing for #{@langs.inspect}..."

@date = Time.now.utc.to_s

bin_dir = File.expand_path(File.dirname(__FILE__))
tmpl = ERB.new(File.read("#{bin_dir}/report.html.erb"), nil, nil, '_err')
File.open(ARGV[1], 'w') { |out|
  out.print tmpl.result(binding)
}
