#!/usr/bin/env ruby

require 'json'

def load_ci_json(fn)
  begin
    doc = File.read(fn)
  rescue => e
    # Note: `Exception#full_message` is only available since Ruby 2.5 (see
    # https://www.bigbinary.com/blog/ruby-2-5-adds-exception-full_message-method),
    # but it seems that the oldest Ruby of all CI hosts we use is Ruby 2.6 in
    # AppVeyor (all GitHub Actions jobs should have Ruby 3), so it should be fine.
    $stderr.puts e.full_message
    return {}
  end
  JSON.load(doc)
end

def dump_test_list(list)
  list.each { |t|
    if t.length == 2
      puts "  #{t[0]} -> #{t[1].inspect}"
    else
      puts "  #{t[0]}: #{t[1].inspect} -> #{t[2].inspect}"
    end
  }
end

prev = load_ci_json(ARGV[0])
now = load_ci_json(ARGV[1])

prev.delete('$meta')
now.delete('$meta')

added = []
changed = []
removed = []

# Detect added and changed tests
now.each_pair { |name, now_res|
  prev_res = prev[name]
  if prev_res
    if prev_res['status'] != now_res['status']
      changed << [name, prev_res, now_res]
    end
  else
    added << [name, now_res]
  end
}

# Detect removed tests
prev.each_pair { |name, res|
  removed << [name, res] unless now[name]
}

unless added.empty?
  puts "+#{added.length} tests added:"
  dump_test_list(added)
end

unless removed.empty?
  puts "-#{removed.length} tests removed:"
  dump_test_list(removed)
end

unless changed.empty?
  puts "!#{changed.length} tests changed:"
  dump_test_list(changed)
end
