# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../compiled/nim/bcd_user_type_le
import auxiliary/test_utils

let r = BcdUserTypeLe.fromFile("src/bcd_user_type_le.bin")

assert r.ltr.asInt == int(12345678)
assert r.ltr.asStr == string("12345678")
assert r.rtl.asInt == int(87654321)
assert r.rtl.asStr == string("87654321")
assert r.leadingZeroLtr.asInt == int(123456)
assert r.leadingZeroLtr.asStr == string("00123456")
