# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../compiled/nim/buffered_struct
import auxiliary/test_utils

let r = BufferedStruct.fromFile("../../src/buffered_struct.bin")

assert r.len1 == 16
assert r.block1.number1 == 66
assert r.block1.number2 == 67
assert r.len2 == 8
assert r.block2.number1 == 68
assert r.block2.number2 == 69
assert r.finisher == 238
