# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../compiled/nim/expr_mod
import auxiliary/test_utils

let r = ExprMod.fromFile("src/fixed_struct.bin")

assert r.intU == uint32(1262698832)
assert r.intS == int32(-52947)
assert r.modPosConst == int(9)
assert r.modNegConst == int(4)
assert r.modPosSeq == int(5)
assert r.modNegSeq == int(2)
