# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../compiled/nim/floating_points
import auxiliary/test_utils

let r = FloatingPoints.fromFile("src/floating_points.bin")

assert r.singleValue == float32((float32(0.5)))
assert r.singleValueBe == float32((float32(0.5)))
assert r.doubleValue == float64(0.25)
assert r.doubleValueBe == float64(0.25)
assert r.approximateValue == float32(1.2345)
assert r.singleValuePlusInt == float64(1.5)
assert r.singleValuePlusFloat == float64(1.0)
assert r.doubleValuePlusFloat == float64(0.3)
