# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../compiled/nim/integers
import auxiliary/test_utils

let r = Integers.fromFile("src/fixed_struct.bin")

assert r.uint8 == uint8(255)
assert r.uint16 == uint16(65535)
assert r.uint32 == uint32(4294967295'i64)
assert r.uint64 == uint64(18446744073709551615'u64)
assert r.sint8 == int8(-1)
assert r.sint16 == int16(-1)
assert r.sint32 == int32(-1)
assert r.sint64 == int64(-1)
assert r.uint16le == uint16(66)
assert r.uint32le == uint32(66)
assert r.uint64le == uint64(66)
assert r.sint16le == int16(-66)
assert r.sint32le == int32(-66)
assert r.sint64le == int64(-66)
assert r.uint16be == uint16(66)
assert r.uint32be == uint32(66)
assert r.uint64be == uint64(66)
assert r.sint16be == int16(-66)
assert r.sint32be == int32(-66)
assert r.sint64be == int64(-66)
