# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../compiled/nim/integers_double_overflow
import auxiliary/test_utils
import strutils

let r = IntegersDoubleOverflow.fromFile("../../src/integers_double_overflow.bin")

assert r.signedSafeMinBe == -9007199254740991'i64
assert r.signedSafeMinLe == -9007199254740991'i64
assert r.signedSafeMaxBe == 9007199254740991'i64
assert r.signedSafeMaxLe == 9007199254740991'i64
assert intToStr(int(r.signedUnsafeNegBe)) == "-9007199254740993"
assert intToStr(int(r.signedUnsafeNegLe)) == "-9007199254740993"
assert intToStr(int(r.signedUnsafePosBe)) == "9007199254740993"
assert intToStr(int(r.signedUnsafePosBe)) == "9007199254740993"
