# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../compiled/nim/js_signed_right_shift
import auxiliary/test_utils

let r = JsSignedRightShift.fromFile("../../src/fixed_struct.bin")

assert r.shouldBe40000000 == 1073741824
assert r.shouldBeA00000 == 10485760
