# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../compiled/nim/params_pass_struct
import auxiliary/test_utils

let r = ParamsPassStruct.fromFile("src/enum_negative.bin")

assert r.first.foo == uint8(255)
assert r.one.bar.qux == uint8(1)
assert (ParamsPassStruct_Block(r.one.foo)).foo == uint8(255)
assert (ParamsPassStruct_Block(r.one.bar.foo)).foo == uint8(255)
