# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../compiled/nim/params_call
import auxiliary/test_utils

let r = ParamsCall.fromFile("../../src/term_strz.bin")

assert r.buf1.body == "foo|b"
assert r.buf2.body == "ar|ba"
assert r.buf2.trailer == 122
