# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../compiled/nim/process_coerce_usertype1
import auxiliary/test_utils

let r = ProcessCoerceUsertype1.fromFile("../../src/process_coerce_bytes.bin")

assert r.records[0].flag == 0
assert r.records[0].buf.value == 1094795585
assert r.records[1].flag == 1
assert r.records[1].buf.value == 1111638594
