# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../compiled/nim/repeat_eos_bits_b1
import auxiliary/test_utils

let r = RepeatEosBitsB1.fromFile("../../src/enum_negative.bin")
assert len(r.bits) == 16
assert r.bits[0] == true
assert r.bits[1] == true
assert r.bits[2] == true
assert r.bits[3] == true
assert r.bits[4] == true
assert r.bits[5] == true
assert r.bits[6] == true
assert r.bits[7] == true
assert r.bits[8] == false
assert r.bits[9] == false
assert r.bits[10] == false
assert r.bits[11] == false
assert r.bits[12] == false
assert r.bits[13] == false
assert r.bits[14] == false
assert r.bits[15] == true
