# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../compiled/nim/switch_repeat_expr_invalid
import auxiliary/test_utils

let r = SwitchRepeatExprInvalid.fromFile("../../src/switch_integers.bin")
assert len(r.codes) == 3
assert r.codes[0] == 1
assert r.codes[1] == 7
assert r.codes[2] == 2
assert (SwitchRepeatExprInvalid_One(r.body[0])).first == @[64'u8, 64'u8, 4'u8, 55'u8]
assert (seq[byte](r.body[1])) == @[19'u8, 0'u8, 0'u8, 8'u8]
assert (SwitchRepeatExprInvalid_Two(r.body[2])).second == @[55'u8, 19'u8, 0'u8, 0'u8]
