# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../compiled/nim/switch_integers2
import auxiliary/test_utils

let r = SwitchIntegers2.fromFile("../../src/switch_integers.bin")

assert r.code == 1
assert r.len == 7
assert r.ham == @[2'u8, 64'u8, 64'u8, 4'u8, 55'u8, 19'u8, 0'u8]
assert r.padding == 0
assert r.lenModStr == "13"
