# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../compiled/nim/term_strz
import auxiliary/test_utils

let r = TermStrz.fromFile("src/term_strz.bin")

assert r.s1 == string("foo")
assert r.s2 == string("bar")
assert r.s3 == string("|baz@")
