# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../compiled/nim/ts_packet_header
import auxiliary/test_utils

let r = TsPacketHeader.fromFile("src/ts_packet.bin")

assert r.syncByte == uint8(71)
assert r.transportErrorIndicator == bool(false)
assert r.payloadUnitStartIndicator == bool(false)
assert r.transportPriority == bool(true)
assert r.pid == uint64(33)
assert r.transportScramblingControl == uint64(0)
assert r.adaptationFieldControl == ts_packet_header.payload_only
