// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"runtime/debug"
	"os"
	"testing"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	. "test_formats"
	"github.com/stretchr/testify/assert"
)

func TestBitsSimpleLe(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			debug.PrintStack()
			t.Fatal("unexpected panic:", r)
		}
	}()
	f, err := os.Open("../../src/fixed_struct.bin")
	if err != nil {
		t.Fatal(err)
	}
	s := kaitai.NewStream(f)
	var r BitsSimpleLe
	err = r.Read(s, &r, &r)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 80, r.Byte1)
	assert.EqualValues(t, 65, r.Byte2)
	assert.EqualValues(t, true, r.BitsA)
	assert.EqualValues(t, 1, r.BitsB)
	assert.EqualValues(t, 4, r.BitsC)
	assert.EqualValues(t, 331, r.LargeBits1)
	assert.EqualValues(t, 3, r.Spacer)
	assert.EqualValues(t, 393, r.LargeBits2)
	assert.EqualValues(t, -1, r.NormalS2)
	assert.EqualValues(t, 4407632, r.Byte8910)
	assert.EqualValues(t, 760556875, r.Byte11To14)
	assert.EqualValues(t, int64(1099499455812), r.Byte15To19)
	assert.EqualValues(t, uint64(18446744073709551615), r.Byte20To27)
	tmp1, err := r.TestIfB1()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 123, tmp1)
}
