// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"runtime/debug"
	"os"
	"testing"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	. "test_formats"
	"github.com/stretchr/testify/assert"
)

func TestExprFstring0(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			debug.PrintStack()
			t.Fatal("unexpected panic:", r)
		}
	}()
	f, err := os.Open("../../src/term_strz.bin")
	if err != nil {
		t.Fatal(err)
	}
	s := kaitai.NewStream(f)
	var r ExprFstring0
	err = r.Read(s, &r, &r)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, "foo|b", r.SeqStr)
	assert.EqualValues(t, 97, r.SeqInt)
	tmp1, err := r.Empty()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, "", tmp1)
	tmp2, err := r.Literal()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, "abc", tmp2)
	tmp3, err := r.LiteralWithEscapes()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, "abc\n\tt", tmp3)
	tmp4, err := r.HeadAndIntLiteral()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, "abc=123", tmp4)
	tmp5, err := r.HeadAndStrLiteral()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, "abc=foo", tmp5)
	tmp6, err := r.HeadAndInt()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, "abc=97", tmp6)
	tmp7, err := r.HeadAndStr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, "abc=foo|b", tmp7)
}
