// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"runtime/debug"
	"os"
	"testing"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	. "test_formats"
	"github.com/stretchr/testify/assert"
)

func TestExprIoTernary(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			debug.PrintStack()
			t.Fatal("unexpected panic:", r)
		}
	}()
	f, err := os.Open("../../src/if_struct.bin")
	if err != nil {
		t.Fatal(err)
	}
	s := kaitai.NewStream(f)
	var r ExprIoTernary
	err = r.Read(s, &r, &r)
	if err != nil {
		t.Fatal(err)
	}

	tmp1, err := r.OneOrTwoIoSize1()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 8, tmp1)
	tmp2, err := r.OneOrTwoIoSize2()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 8, tmp2)
	tmp3, err := r.OneOrTwoIoSizeAdd3()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 11, tmp3)
}
