# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import EosExceptionSizedModule
using KaitaiStruct

@testset "EosExceptionSized test" begin
    @test_throws ErrorException EosExceptionSizedModule.from_file("src/term_strz.bin")
end
