# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import ProcessCoerceUsertype2Module

@testset "ProcessCoerceUsertype2 test" begin
    r = ProcessCoerceUsertype2Module.from_file("src/process_coerce_bytes.bin")


    @test r.records[1].flag == 0
    @test r.records[1].buf.value == 1094795585
    @test r.records[2].flag == 1
    @test r.records[2].buf.value == 1111638594
end
