# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import ParamsEnumModule

@testset "ParamsEnum test" begin
    r = ParamsEnumModule.from_file("src/enum_0.bin")


    @test r.one == ParamsEnumModule.params_enum_animal__cat
    @test r.invoke_with_param.is_cat == true
end
