# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import FloatToIModule

@testset "FloatToI test" begin
    r = FloatToIModule.from_file("src/floating_points.bin")


    @test r.single_value ≈ 0.5 atol=10^(-6)
    @test r.double_value ≈ 0.25 atol=10^(-6)
    @test r.single_i == 0
    @test r.double_i == 0
    @test r.float1_i == 1
    @test r.float2_i == 1
    @test r.float3_i == 1
    @test r.float4_i == -2
end
