# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import NavParentSwitchModule

@testset "NavParentSwitch test" begin
    r = NavParentSwitchModule.from_file("src/nav_parent_switch.bin")


    @test r.category == 1
    @test r.content.foo == 66
    @test r.content.subelement.bar == 255
end
