# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import BitsShiftByB64LeModule

@testset "BitsShiftByB64Le test" begin
    r = BitsShiftByB64LeModule.from_file("src/bits_shift_by_b64_le.bin")


    @test r.a == 18446744073709551615
    @test r.b == 0
end
