# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import ImportsRel1Module

@testset "ImportsRel1 test" begin
    r = ImportsRel1Module.from_file("src/fixed_struct.bin")


    @test r.one == 80
    @test r.two.one == 65
    @test r.two.two.one == 67
end
