# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import ValidOptionalIdModule

@testset "ValidOptionalId test" begin
    r = ValidOptionalIdModule.from_file("src/fixed_struct.bin")


    
end
