# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import RepeatEosU4Module

@testset "RepeatEosU4 test" begin
    r = RepeatEosU4Module.from_file("src/repeat_eos_struct.bin")


    @test r.numbers == [0, 66, 66, 2069]
end
