# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import TermStrzModule

@testset "TermStrz test" begin
    r = TermStrzModule.from_file("src/term_strz.bin")


    @test r.s1 == "foo"
    @test r.s2 == "bar"
    @test r.s3 == "|baz@"
end
