# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import ExprModModule

@testset "ExprMod test" begin
    r = ExprModModule.from_file("src/fixed_struct.bin")


    @test r.int_u == 1262698832
    @test r.int_s == -52947
    @test r.mod_pos_const == 9
    @test r.mod_neg_const == 4
    @test r.mod_pos_seq == 5
    @test r.mod_neg_seq == 2
end
