# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import InstanceIoUserModule

@testset "InstanceIoUser test" begin
    r = InstanceIoUserModule.from_file("src/instance_io.bin")


    @test r.qty_entries == 3
    @test r.entries[1].name == "the"
    @test r.entries[2].name == "rainy"
    @test r.entries[3].name == "day it is"
end
