# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import BitsEnumModule

@testset "BitsEnum test" begin
    r = BitsEnumModule.from_file("src/fixed_struct.bin")


    @test r.one == BitsEnumModule.bits_enum_animal__platypus
    @test r.two == BitsEnumModule.bits_enum_animal__horse
    @test r.three == BitsEnumModule.bits_enum_animal__cat
end
