# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import ExprIoEofModule

@testset "ExprIoEof test" begin
    r = ExprIoEofModule.from_file("src/fixed_struct.bin")


    @test r.substream1.one == 1262698832
    @test r.substream1.two === nothing
    @test r.substream2.one == 4294914349
    @test r.substream2.two == 1262698832
end
