# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import UserTypeModule

@testset "UserType test" begin
    r = UserTypeModule.from_file("src/repeat_until_s4.bin")


    @test r.one.width == 66
    @test r.one.height == 4919
end
