# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import SwitchManualStrModule

@testset "SwitchManualStr test" begin
    r = SwitchManualStrModule.from_file("src/switch_opcodes.bin")


    @test Base.size(r.opcodes, 1) == 4
    @test r.opcodes[1].code == "S"
    @test r.opcodes[1].body.value == "foobar"
    @test r.opcodes[2].code == "I"
    @test r.opcodes[2].body.value == 66
    @test r.opcodes[3].code == "I"
    @test r.opcodes[3].body.value == 55
    @test r.opcodes[4].code == "S"
    @test r.opcodes[4].body.value == ""
end
