# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import NestedSameNameModule

@testset "NestedSameName test" begin
    r = NestedSameNameModule.from_file("src/repeat_n_struct.bin")


    @test r.main_data.main_size == 2
    @test r.main_data.foo.data == Vector{UInt8}([16, 0, 0, 0])
end
