# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import ExprIoPosModule

@testset "ExprIoPos test" begin
    r = ExprIoPosModule.from_file("src/expr_io_pos.bin")


    @test r.substream1.my_str == "CURIOSITY"
    @test r.substream1.body == Vector{UInt8}([17, 34, 51, 68])
    @test r.substream1.number == 66
    @test r.substream2.my_str == "KILLED"
    @test r.substream2.body == Vector{UInt8}([97, 32, 99, 97, 116])
    @test r.substream2.number == 103
end
