# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import NavParentOverrideModule

@testset "NavParentOverride test" begin
    r = NavParentOverrideModule.from_file("src/nav_parent_codes.bin")


    @test r.child_size == 3
    @test r.child_1.data == Vector{UInt8}([73, 49, 50])
    @test r.mediator_2.child_2.data == Vector{UInt8}([51, 66, 98])
end
