# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import ValidFailRangeBytesModule
using KaitaiStruct

@testset "ValidFailRangeBytes test" begin
    @test_throws KaitaiStruct.ValidationGreaterThanError ValidFailRangeBytesModule.from_file("src/fixed_struct.bin")
end
