# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import CombineBoolModule

@testset "CombineBool test" begin
    r = CombineBoolModule.from_file("src/enum_negative.bin")


    @test r.bool_bit == true
    @test r.bool_calc_bit == false
end
