# Autogenerated from KST: please remove this line if doing any edits by hand!

using Test
import IfValuesModule

@testset "IfValues test" begin
    r = IfValuesModule.from_file("src/fixed_struct.bin")


    @test r.codes[1].opcode == 80
    @test r.codes[1].half_opcode == 40
    @test r.codes[2].opcode == 65
    @test r.codes[2].half_opcode === nothing
    @test r.codes[3].opcode == 67
    @test r.codes[3].half_opcode === nothing
end
